#include "gfx/atlas.h"

#include <citro3d.h>
#include <tex3ds.h>

#include "atlas_t3x.h"   // generated by tex3ds from gfx/atlas.t3s

static C3D_Tex s_tex;

bool atlasInit(void)
{
	// vram = true. The atlas is a 16x1024 strip at RGBA5551 (2 bytes/texel), so it costs
	// 32 KB of the ~6 MB VRAM budget. It was 128x128 (32 KB) up to v1.5.1, 64x64 (8 KB)
	// before TILE_PLANKS needed a tenth cell, and 256x256 RGBA8888 (256 KB) before step
	// 9.3. All four figures are computed from the sheet, not measured on-device. The size
	//
	// 2026-09-02: the first sentence said 16x256 and 8 KB, and had been wrong by 4x since
	// the sheet was made tall enough to hold 64 slots. Corrected against the constants that
	// actually govern it: ATLAS_W_PX 16 and ATLAS_H_PX 1024 in world/atlas_uv.h:48-49, which
	// give ATLAS_TILE_SLOTS 64 at atlas_uv.h:76. Worth knowing that the corrected figure
	// collides with a number already in this comment: the v1.5.1 128x128 sheet ALSO cost
	// 32 KB, so "32 KB" alone does not identify which sheet is being discussed. The size
	// itself is not read from here — it comes out of the .t3x — but ATLAS_W_PX/ATLAS_H_PX
	// in world/atlas_uv.h and uvScale in BOTH shaders/world.v.pica and
	// shaders/world_dynamic.v.pica must match the PNG that tools/make_atlas.py writes.
	// Texture reads out of VRAM are the cheap ones on this GPU.
	// The 30,936 -> 30,680 KB linear-free delta this comment used to quote was
	// measured with vram=false at the old 256x256 RGBA8888 size; it has NOT been
	// re-measured at the new size — that needs an actual boot.
	Tex3DS_Texture t3x = Tex3DS_TextureImport(atlas_t3x, atlas_t3x_size, &s_tex, NULL, true);
	if (!t3x)
		return false;

	// The t3x descriptor only describes the layout; the pixels now live in the
	// C3D_Tex, so it can go straight away.
	Tex3DS_TextureFree(t3x);

	// Nearest on both filters, and no mipmaps: this is pixel art and the whole look
	// depends on the pixels staying square. Neither filter here is a GPU_*_MIPMAP_*
	// mode, and gfx/atlas.t3s asks tex3ds for none (-f rgba5551 -z auto, no -m), so the
	// built build/atlas.t3x carries mipmapLevels = 0 — measured out of its header. That
	// is load-bearing now the 2px inter-tile border is gone: with the strip layout the
	// slots are directly adjacent in V, and a mip chain would average across the seam
	// and bleed one tile into the next at distance, which is exactly what the border
	// used to prevent.
	C3D_TexSetFilter(&s_tex, GPU_NEAREST, GPU_NEAREST);

	// GPU_REPEAT in U, GPU_CLAMP_TO_EDGE in V. This is the whole point of the strip: the
	// sheet is exactly one tile wide, so the U repeat period IS one tile and a greedy-
	// merged quad can run u past 16 and have every block of the run show a complete,
	// correct tile. On the old 128px-wide grid REPEAT wrapped over eight tiles instead,
	// which is why merging was impossible there. V stays clamped — the slots are stacked,
	// so wrapping v would show the next block's art, and merging is U-only for that
	// reason. See world/atlas_uv.h.
	C3D_TexSetWrap(&s_tex, GPU_REPEAT, GPU_CLAMP_TO_EDGE);
	atlasBind();
	return true;
}

void atlasExit(void)
{
	C3D_TexDelete(&s_tex);
}

void atlasBind(void)
{
	C3D_TexBind(0, &s_tex);
}

C3D_Tex* atlasTexture(void)
{
	return &s_tex;
}

AtlasRect atlasTile(int tile)
{
	return atlasRect(tile);   // world/atlas_uv.h — shared with the mesher
}
