#include "gfx/crackatlas.h"

#include <citro3d.h>
#include <tex3ds.h>

#include "crackatlas_t3x.h"   // generated by tex3ds from gfx/crackatlas.t3s

static C3D_Tex s_tex;
static bool    s_ready;

bool crackAtlasInit(void)
{
	if (s_ready)
		return true;

	// vram = true, same as the world atlas and for the same reason: texture reads out of
	// VRAM are the cheap ones on this GPU. 16x128 at RGBA5551 (2 bytes/texel) is 4,096
	// bytes of the ~6 MB budget — half what the world's 16x256 strip costs. That figure is
	// computed from the sheet, not measured on-device.
	Tex3DS_Texture t3x = Tex3DS_TextureImport(crackatlas_t3x, crackatlas_t3x_size, &s_tex, NULL, true);
	if (!t3x)
		return false;

	// The t3x descriptor only describes the layout; the pixels now live in the C3D_Tex.
	Tex3DS_TextureFree(t3x);

	// Nearest on both filters and no mipmaps, exactly as gfx/atlas.c asks for. This is
	// pixel art and the look depends on the pixels staying square; more to the point, the
	// eight stages are directly adjacent in V with no gutter between them, so a mip chain
	// would average across the boundary and bleed one stage's cracks into the next.
	// gfx/crackatlas.t3s passes tex3ds only "-f rgba5551 -z auto" with no -m, and neither
	// filter here is a GPU_*_MIPMAP_* mode, so no level beyond the base is ever sampled.
	C3D_TexSetFilter(&s_tex, GPU_NEAREST, GPU_NEAREST);

	// CLAMP_TO_EDGE on BOTH axes, which is where this differs from the world atlas.
	// gfx/atlas.c wants GPU_REPEAT in U so a greedy-merged quad can run u past one tile;
	// nothing merges here. scene/crackoverlay.c draws one unit cube per break, its UVs
	// never leave [0,1] in U or the stage's own row in V, and REPEAT would only turn a
	// future arithmetic slip into a plausible-looking tiled crack instead of an obvious
	// smear. V is clamped for the reason the world sheet clamps it: the stages are
	// stacked, so wrapping v shows a different stage's art.
	C3D_TexSetWrap(&s_tex, GPU_CLAMP_TO_EDGE, GPU_CLAMP_TO_EDGE);

	// No bind here — see the note on crackAtlasInit() in the header. Binding at init would
	// leave the crack sheet on texture unit 0 for the first world frame.
	s_ready = true;
	return true;
}

void crackAtlasExit(void)
{
	if (!s_ready)
		return;
	C3D_TexDelete(&s_tex);
	s_ready = false;
}

void crackAtlasBind(void)
{
	if (!s_ready)
		return;
	C3D_TexBind(0, &s_tex);
}

C3D_Tex* crackAtlasTexture(void)
{
	return s_ready ? &s_tex : NULL;
}
