#include "gfx/fogtex.h"

#include <citro3d.h>
#include <tex3ds.h>

#include "fogramp_t3x.h"   // generated by tex3ds from gfx/fogramp.t3s

static C3D_Tex s_tex;

bool fogTexInit(void)
{
	// vram = true, same as the atlas. 128x8 at A8 is 1,024 bytes of the ~6 MB VRAM budget,
	// which is under a third of a percent of what the atlas costs there, and this texture is
	// sampled once per fragment of the world so it wants the fast heap. NOT MEASURED on a
	// console — nothing since v1.2.5 has run on hardware — but the size is arithmetic from the
	// sheet, not an estimate.
	Tex3DS_Texture t3x = Tex3DS_TextureImport(fogramp_t3x, fogramp_t3x_size, &s_tex, NULL, true);
	if (!t3x)
		return false;
	Tex3DS_TextureFree(t3x);

	// GPU_LINEAR on both filters, which is the opposite of the atlas and for the opposite
	// reason: the atlas is pixel art whose whole look depends on the texels staying square,
	// and this is a continuous function sampled at 128 points. GPU_NEAREST here would quantise
	// the fade to 128 steps across the visible world — about a fifth of a block per step at
	// radius 3 — and put visible contour rings on the ground. Neither filter is a
	// GPU_*_MIPMAP_* mode and gfx/fogramp.t3s asks tex3ds for no mip chain, so only the base
	// level is ever sampled.
	C3D_TexSetFilter(&s_tex, GPU_LINEAR, GPU_LINEAR);

	// GPU_CLAMP_TO_EDGE on BOTH axes, and both matter.
	//
	//   U — the shader emits u < 0 for anything nearer than the fade's start and u > 1 for
	//       anything past its end, deliberately, because that is cheaper than clamping in the
	//       vertex shader and the sampler does it for free. GPU_REPEAT here would wrap the far
	//       distance back to CLEAR, i.e. the horizon would punch a hole through the fog.
	//   V — the shader writes the fog coordinate into both components of texcoord1 (all 8 rows
	//       of this sheet are identical, so v means nothing), which puts v out of 0..1 for the
	//       same distances. Clamping makes that a no-op; repeating would still be a no-op
	//       today and would stop being one the moment anything is ever put in a second row.
	C3D_TexSetWrap(&s_tex, GPU_CLAMP_TO_EDGE, GPU_CLAMP_TO_EDGE);

	fogTexBind();
	return true;
}

void fogTexExit(void)
{
	C3D_TexDelete(&s_tex);
}

void fogTexBind(void)
{
	// Unit 1. Unit 0 is the atlas in the world pass and the font sheet in the UI batch; unit 2
	// is still unused.
	//
	// citro3d has no unbind, so once this runs the unit stays enabled for every later draw in
	// the frame — the UI batch included, whose TEV never reads it. That costs those fragments a
	// texture fetch whose result is discarded, and it cannot go wrong: the coordinate those
	// passes leave on texcoord1 is undefined, but GPU_CLAMP_TO_EDGE means no coordinate can
	// address outside this 1 KB, and no TEV stage in those passes sources GPU_TEXTURE1. The
	// four non-world passes each reset TEV stage 1 explicitly so that second half stays true.
	// NOT MEASURED: the cost of that discarded fetch. It is a handful of thousand fragments of
	// UI a frame against a full-screen world pass, so it is stated as small rather than as
	// nothing.
	C3D_TexBind(1, &s_tex);
}
