#include "gfx/font.h"

#include <math.h>     // floorf, for the pixel snap in fontDraw
#include <stdarg.h>
#include <stdio.h>

#include <tex3ds.h>

#include "gfx/sprite.h"

#include "font_t3x.h"   // generated by tex3ds from gfx/font.t3s

// Must agree with tools/make_font.py. Duplicated rather than generated because these five
// numbers have not changed since the font was drawn and a generated header for them would
// be more build machinery than the constants are worth — but make_font.py's check() does
// assert the same invariants (glyphs exactly 5x7, cell strictly larger), so a change there
// that broke these would fail loudly on the tool side.
#define FONT_CELL_PX 8
#define FONT_COLS    16
#define FONT_TEX_W   128
#define FONT_TEX_H   64
#define FONT_FIRST   32
#define FONT_LAST    126

static C3D_Tex s_tex;
static bool    s_ready;

bool fontInit(void)
{
	if (s_ready) return true;

	// vram = false, unlike the block atlas. The atlas is sampled by every one of the
	// thousands of world triangles per frame, so it earns its VRAM; the font is sampled
	// by a few hundred UI pixels and would be spending 32 KB of a ~6 MB VRAM budget to
	// save a bandwidth cost that does not exist at that pixel count.
	Tex3DS_Texture t3x = Tex3DS_TextureImport(font_t3x, font_t3x_size, &s_tex, NULL, false);
	if (!t3x) return false;
	Tex3DS_TextureFree(t3x);

	// Nearest, like the atlas, and for the same reason with more force: a glyph is five
	// pixels wide, so any filtering at all turns a stroke into a smear.
	C3D_TexSetFilter(&s_tex, GPU_NEAREST, GPU_NEAREST);
	C3D_TexSetWrap(&s_tex, GPU_CLAMP_TO_EDGE, GPU_CLAMP_TO_EDGE);

	s_ready = true;
	return true;
}

void fontExit(void)
{
	if (!s_ready) return;
	C3D_TexDelete(&s_tex);
	s_ready = false;
}

C3D_Tex* fontTexture(void)
{
	return s_ready ? &s_tex : NULL;
}

void fontDraw(float x, float y, int scale, uint32_t colour, const char* text)
{
	if (!s_ready || !text || scale < 1) return;

	const float w = (float)(FONT_GLYPH_W * scale);
	const float h = (float)(FONT_GLYPH_H * scale);

	// Snapped to whole pixels, and this is a bug fix rather than tidiness. A glyph is a 5x7
	// grid of pixels sampled GPU_NEAREST; put its top edge on a half pixel and the quad spans
	// y+0.5 .. y+7.5, which covers only six pixel centres instead of seven, so the topmost
	// source row is never sampled and simply is not drawn.
	//
	// The failure is quiet in exactly the way the V-flip below is: every glyph still resolves
	// to *a* glyph, so the screen fills with plausible text. Measured on the step 8.4 options
	// screen, whose rows centre their labels with (row_h - FONT_GLYPH_H) * 0.5f — 30 and 7
	// give 11.5 — and which rendered "RENDER DIST" as "KENDEK DISI", "ON" as "UN" and "1.00"
	// as "1.UU": an R without its top loop is a K, an O without its top is a U, a T without
	// its top bar is an I. The header on that same screen, drawn at an integer y, was correct
	// throughout, which is what identified the cause rather than the scale.
	//
	// Rounded rather than truncated, so a centred label lands on the nearer pixel instead of
	// always drifting one up, and applied here rather than at each caller because there is no
	// caller for whom a half-pixel glyph is the intent — this is the layer that knows the text
	// is a pixel grid. Callers already passing integers are unaffected, which is why step 8.3's
	// verified font screen does not move.
	const float ox = floorf(x + 0.5f);
	float pen_x = ox, pen_y = floorf(y + 0.5f);

	for (const unsigned char* p = (const unsigned char*)text; *p; p++) {
		if (*p == '\n') {
			pen_x = ox;
			pen_y += (float)(FONT_LINE * scale);
			continue;
		}

		// Space is in the table as a blank glyph, but skipping the draw saves a quad in
		// every line of text — and text is the thing the batch holds most of.
		if (*p != ' ' && *p >= FONT_FIRST && *p <= FONT_LAST) {
			const int idx = *p - FONT_FIRST;
			const float px = (float)((idx % FONT_COLS) * FONT_CELL_PX);
			const float py = (float)((idx / FONT_COLS) * FONT_CELL_PX);

			// V is flipped, and this is not cosmetic. PICA200 texture space has its origin
			// at the BOTTOM-left while the sheet make_font.py draws — and every cell index
			// computed above — is top-down, so v = py/H samples the mirror image of the row
			// that was wanted. Measured, not reasoned: drawing the whole sheet as one
			// UV 0..1 quad rendered it upside down, with cell row 0 ('!' onward) along the
			// bottom edge and each glyph individually inverted inside its cell.
			//
			// It went unnoticed because the failure is quiet — every glyph still resolves to
			// *a* glyph, so the screen fills with plausible-looking text. 'B' (cell row 2,
			// col 2) came out as a vertically mirrored 'r' (cell row 5, same column), which
			// reads as a font bug rather than a coordinate bug.
			const float v_top = 1.0f - py / FONT_TEX_H;
			const float v_bot = 1.0f - (py + FONT_GLYPH_H) / FONT_TEX_H;

			spriteQuad(pen_x, pen_y, w, h,
			           px / FONT_TEX_W, v_top,
			           (px + FONT_GLYPH_W) / FONT_TEX_W, v_bot,
			           colour);
		}

		pen_x += (float)(FONT_ADVANCE * scale);
	}
}

void fontDrawf(float x, float y, int scale, uint32_t colour, const char* fmt, ...)
{
	char buf[128];
	va_list ap;

	va_start(ap, fmt);
	vsnprintf(buf, sizeof(buf), fmt, ap);
	va_end(ap);

	fontDraw(x, y, scale, colour, buf);
}

int fontTextWidth(const char* text, int scale)
{
	if (!text || scale < 1) return 0;

	int best = 0, run = 0;

	for (const unsigned char* p = (const unsigned char*)text; *p; p++) {
		if (*p == '\n') {
			if (run > best) best = run;
			run = 0;
			continue;
		}
		run++;
	}
	if (run > best) best = run;

	return best * FONT_ADVANCE * scale;
}
