#include "gfx/sprite.h"

#include <string.h>

#include "sprite_shbin.h"   // generated by picasso from source/shaders/sprite.v.pica

// 24 bytes. Position as three floats rather than two shorts because z is a layer and
// because the UI is laid out in fractional pixels in places (a centred label on an odd
// width); texcoord as floats because the font's cells are eighths and sixteenths of the
// texture and a fixed-point UV would quantise them; colour as four bytes because it is
// the one field where eight bits per channel is the whole range the hardware has.
typedef struct {
	float    x, y, z;
	float    u, v;
	uint32_t rgba;
} SpriteVertex;

// Quads the buffer holds for a whole FRAME — not for one batch. Every batch a frame opens
// takes a fresh region (see spriteFrameBegin in the header for why they cannot share one),
// so this has to cover all of them added together.
//
// 1024 is not a guess. The inventory figure below was WRONG until v1.8.7 — it said "9x5 slots,
// 45 slots, 180 quads", a grid this game has never had. The real one is world/inventory.h's
// INV_SLOT_COUNT of 24: an 8-slot hotbar plus an INV_MAIN_COLS x INV_MAIN_ROWS main grid of
// 8x2 = 16. Correcting it makes the budget LARGER, not smaller, which is why the error was
// harmless and also why it survived — an over-estimate of the worst case never overflows.
//
// The worst frame the game can draw, recounted against the real layout: the bottom screen with
// the inventory overlay open is 24 slot panels, at most one four-quad "picked" border, up to two
// count digits a slot, 24 icon quads in the atlas pass and the crafting panel's four rows and
// title — under 200 all together (gfx/font.c emits one quad per PRINTABLE NON-SPACE character,
// so the text is cheaper than its length suggests). On top of that the pause menu, and over it
// the remap or debug screen, are each their own pass on the same screen: call the bottom screen
// 450. The top screen is the name tags — one quad per character at NETWORLD_MAX_REMOTE (15)
// players and 11 characters a label, so 165 — plus a four-quad reticle, and it is drawn TWICE
// when the 3D slider is up, so 338. That is roughly 790 of 1024 for a frame that has never
// actually occurred, and it is arithmetic over the draw sites rather than a measurement.
//
// Deliberately NOT shrunk to fit that. A UI redesign is planned for v1.8.19 and shrinking a
// constant now in order to grow it again later is churn against the one buffer in this file
// whose overflow silently draws one batch's geometry in another's place.
//
// The cost is 1024 * 4 * 24 = 96 KB of linear memory, up from 48 KB. That is affordable
// against a measured app heap of 0.26-0.49 MB in a 12.00 MB cap, and it is the cheap half
// of the trade: overflowing wraps the cursor and puts one batch's geometry into another,
// which is the very fault this file was corrected for.
#define SPRITE_MAX_QUADS 1024
#define SPRITE_MAX_VERTS (SPRITE_MAX_QUADS * 4)
#define SPRITE_MAX_IDX   (SPRITE_MAX_QUADS * 6)

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;

static SpriteVertex* s_verts;
static uint16_t*     s_indices;
static bool          s_ready;

static int      s_base;           // first quad slot this frame's pending batch owns
static int      s_quads;          // pending, not yet submitted, counted from s_base
static C3D_Tex* s_tex;            // currently bound

static int s_frame_quads;         // total for the whole frame, not just the pending batch — see spriteFrameQuads

static C3D_Mtx s_projection;

bool spriteInit(void)
{
	if (s_ready) return true;

	s_dvlb = DVLB_ParseFile((u32*)sprite_shbin, sprite_shbin_size);
	if (!s_dvlb) return false;

	shaderProgramInit(&s_program);
	shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);
	s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");

	// linearAlloc, not malloc: the GPU reads these directly and needs physically
	// contiguous memory. Both buffers live for the whole run — a UI that reallocated
	// per frame would fragment the linear heap, which cannot be defragmented.
	s_verts   = (SpriteVertex*)linearAlloc(SPRITE_MAX_VERTS * sizeof(SpriteVertex));
	s_indices = (uint16_t*)linearAlloc(SPRITE_MAX_IDX * sizeof(uint16_t));
	if (!s_verts || !s_indices) {
		if (s_verts)   linearFree(s_verts);
		if (s_indices) linearFree(s_indices);
		s_verts = NULL;
		s_indices = NULL;
		shaderProgramFree(&s_program);
		DVLB_Free(s_dvlb);
		s_dvlb = NULL;
		return false;
	}

	// Filled once and never again. Every quad has the same six-index pattern relative to
	// its own four vertices, so the index buffer is a constant — rebuilding it per frame
	// would be 3 KB of pointless writes.
	for (int q = 0; q < SPRITE_MAX_QUADS; q++) {
		const uint16_t v = (uint16_t)(q * 4);
		uint16_t* i = &s_indices[q * 6];
		i[0] = v;     i[1] = (uint16_t)(v + 1); i[2] = (uint16_t)(v + 2);
		i[3] = v;     i[4] = (uint16_t)(v + 2); i[5] = (uint16_t)(v + 3);
	}

	// linearAlloc memory is CACHED. The GPU is a separate bus master and reads physical RAM
	// directly, so everything written above is still sitting in the ARM11's data cache and the
	// GPU would read whatever the linear heap happened to hold beforehand. One flush covers the
	// whole buffer because it is never written again.
	//
	// This is the bug that froze real consoles from v1.1.0 to v1.1.8 and never once reproduced
	// in an emulator: emulators have no CPU data cache to be stale. See scene/chunk_render.c
	// for the copy that actually did the freezing — the GPU followed stale indices out of the
	// vertex buffer and stopped, mid command list, forever.
	GSPGPU_FlushDataCache(s_indices, SPRITE_MAX_IDX * sizeof(uint16_t));

	s_ready = true;
	return true;
}

void spriteExit(void)
{
	if (!s_ready) return;
	linearFree(s_verts);
	linearFree(s_indices);
	s_verts = NULL;
	s_indices = NULL;
	shaderProgramFree(&s_program);
	DVLB_Free(s_dvlb);
	s_dvlb = NULL;
	s_ready = false;
}

// Submits the pending quads and empties the batch. Does nothing when there is nothing
// pending, so it is safe to call from anywhere that might be a boundary.
//
// The index run starts at this batch's own base rather than at zero, and the cursor then
// advances past what was just submitted — the submitted quads stay claimed for the rest of
// the frame, because the GPU has not read them yet (see spriteFrameBegin in the header).
// The index buffer holds absolute vertex numbers, so an offset run needs no fixups.
static void flush(void)
{
	if (!s_ready || s_quads == 0) return;

	// These vertices were written by the CPU moments ago and are still in the data cache. Only
	// this batch's own range needs flushing, not the whole buffer: the quads before s_base were
	// flushed by an earlier flush() this frame, and the ones after it have not been written yet.
	GSPGPU_FlushDataCache(&s_verts[s_base * 4], (size_t)s_quads * 4u * sizeof(SpriteVertex));

	C3D_DrawElements(GPU_TRIANGLES, s_quads * 6, C3D_UNSIGNED_SHORT, &s_indices[s_base * 6]);
	s_base += s_quads;
	s_quads = 0;
}

void spriteFrameBegin(void)
{
	s_base = 0;
	s_frame_quads = 0;
}

void spriteBegin(int w, int h)
{
	if (!s_ready) return;

	s_quads = 0;
	s_tex = NULL;

	C3D_BindProgram(&s_program);

	// Top-left origin with y increasing downwards: `bottom` is h and `top` is 0, which is
	// the pair the other way round from the usual GL call. The final `true` is the tilt —
	// every 3DS framebuffer is stored rotated 90 degrees, and this is where that is paid
	// for so no caller ever sees it.
	Mtx_OrthoTilt(&s_projection, 0.0f, (float)w, (float)h, 0.0f, 0.0f, 1.0f, true);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, &s_projection);

	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);          // v0 position
	AttrInfo_AddLoader(attr, 1, GPU_FLOAT, 2);          // v1 texcoord
	AttrInfo_AddLoader(attr, 2, GPU_UNSIGNED_BYTE, 4);  // v2 colour

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(SpriteVertex), 3, 0x210);

	// Texture colour modulated by the vertex colour, and the same for alpha. That one
	// stage is what makes a single white font texture able to draw text in any colour and
	// at any opacity: the texture carries the *shape*, the vertex carries the *ink*.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
	C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

	// v1.9.0. TEV stage 1 and the fog unit, both explicitly OWNED here instead of inherited
	// from the world pass. This is the one of the four that would actually have shown.
	//
	// The pre-existing bug: nothing in the tree called GPU_NO_FOG before v1.9.0, so every UI
	// batch was drawn with the terrain's hardware fog live. It never tinted anything, and the
	// reason is a coincidence rather than a decision — this batch draws through an ORTHO
	// projection, so every vertex has w = 1, the fog LUT is indexed by 1/w, and w = 1 lands
	// around entry 23 of 128, which the v1.8.5 table holds at fully clear. Move the table's
	// clear point inward by twenty entries and the entire HUD would have gone sky blue with
	// nothing in this file changed.
	//
	// v1.9.0's fade is a TEV stage instead, and a leaked one is worse than the old leak was:
	// it would INTERPOLATE every glyph and panel toward the sky colour by whatever texture
	// unit 1 returned for a texcoord1 this shader never writes — i.e. by an undefined amount,
	// which is a bug that looks different every frame. Both halves are claimed explicitly:
	// stage 1 back to citro3d's REPLACE(previous) passthrough, and the fixed-function unit
	// off. Unit 1 stays BOUND (citro3d has no unbind — see gfx/fogtex.c) but is now sourced by
	// no stage, so nothing samples it here.
	C3D_TexEnv* fog = C3D_GetTexEnv(1);
	C3D_TexEnvInit(fog);
	C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);

	// Straight alpha blending, and depth off. The UI is drawn in submission order on top
	// of a finished world; a depth test would need every panel to carry a z that agreed
	// with the order it was written in, which is a bug waiting to happen for no gain.
	C3D_AlphaBlend(GPU_BLEND_ADD, GPU_BLEND_ADD, GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA,
	               GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA);
	C3D_DepthTest(false, GPU_ALWAYS, GPU_WRITE_COLOR);
	C3D_CullFace(GPU_CULL_NONE);
}

void spriteTexture(C3D_Tex* tex)
{
	if (!s_ready || tex == s_tex) return;
	flush();
	s_tex = tex;
	C3D_TexBind(0, tex);
}

void spriteQuad(float x, float y, float w, float h,
                float u0, float v0, float u1, float v1, uint32_t colour)
{
	if (!s_ready) return;

	// Flushing rather than dropping. A dropped quad is a hole in the UI that nothing
	// reports; an extra draw call is only an extra draw call.
	//
	// Wrapping past the end is the one case with no good answer: the frame has asked for
	// more quads than exist, and every slot from here on is still claimed by a batch the
	// GPU has not drawn yet. Wrapping keeps drawing (a wrong picture) where refusing would
	// silently lose a screen of UI. v1.8.7 removed the counter that used to record it — see
	// gfx/sprite.h on why, and on what putting one back would have to involve.
	if (s_base + s_quads >= SPRITE_MAX_QUADS) {
		flush();
		if (s_base >= SPRITE_MAX_QUADS)
			s_base = 0;
	}

	SpriteVertex* v = &s_verts[(s_base + s_quads) * 4];
	const float x1 = x + w, y1 = y + h;

	// Clockwise from the top-left in screen space. Winding does not matter — culling is
	// off for the whole pass — but a consistent order does, because the index buffer is
	// built once and assumes it.
	v[0] = (SpriteVertex){x,  y,  0.0f, u0, v0, colour};
	v[1] = (SpriteVertex){x1, y,  0.0f, u1, v0, colour};
	v[2] = (SpriteVertex){x1, y1, 0.0f, u1, v1, colour};
	v[3] = (SpriteVertex){x,  y1, 0.0f, u0, v1, colour};

	s_quads++;
	s_frame_quads++;  // whole-frame total; counted here so a wrap above still counts, not just the common case
}

int spriteFrameQuads(void)
{
	return s_frame_quads;
}

void spriteRect(float x, float y, float w, float h, uint32_t colour)
{
	// The middle of the solid cell, as a single point rather than the cell's edges: the
	// quad is stretched across whatever size the caller asked for, so one texel sampled
	// with GPU_NEAREST fills it exactly and can never pick up a neighbour.
	//
	// The numbers are the solid cell's centre in the 128x64 font texture — cell 95 of a
	// 16-wide grid of 8px cells, so pixel (124, 44). Kept as a fraction rather than a
	// symbol because gfx/ does not otherwise know the font's layout, and a rectangle
	// primitive that depended on the font's cell size would be the wrong coupling.
	//
	// V is measured from the BOTTOM because that is where PICA200 texture space starts,
	// while the 44.5 above is a top-down pixel row. Without the flip this sampled y 19.5
	// instead — pixel (124, 19), which is the right-hand stroke of the letter 'O' in cell
	// 47. That is opaque white, so every panel in the game still drew correctly and the
	// bug stayed invisible: rectangles were being filled from a one-pixel-wide piece of a
	// glyph, and any change to the font sheet or to UV rounding would have turned them
	// transparent for no apparent reason.
	const float u = 124.5f / 128.0f;
	const float v = 1.0f - 44.5f / 64.0f;
	spriteQuad(x, y, w, h, u, v, u, v, colour);
}

void spriteEnd(void)
{
	flush();
}
