#include "debug/biomeborder_draw.h"

#include <math.h>
#include <stdint.h>
#include <string.h>

#include "debug/biomeborder.h"
#include "scene/chunk_render.h"   // the world's projection and camera, which this must match

#include "highlight_shbin.h"   // generated by picasso from source/shaders/highlight.v.pica

// ── The shader is BORROWED, not written ──────────────────────────────────────────────
//
// source/shaders/highlight.v.pica is already exactly this pass: a position-only float3
// attribute, a projection and a modelView, a fogParams the caller drives, and a colour that
// comes from a TEV constant rather than from the vertex. scene/playermodel.c is the second
// module to reuse it verbatim and this is the third, so the pattern is the tree's own.
//
// It was reused rather than a biomeborder.v.pica added, for two concrete reasons and not for
// tidiness. First, source/shaders/world_dynamic.v.pica now spends 86 of the PICA200's 96
// vertex uniform registers after the biome-tint work — measured, a 17-row palette assembles
// and an 18-row one fails picasso — and a fourth program is free of that pressure only if it
// exists; a new .pica also has to be compiled by picasso into build/, and this change may not
// run a console build. Second, a shader this file added would be a fourth copy of the same
// twelve instructions to keep in step with the fog work that already had to touch three.
//
// Each consumer keeps its OWN DVLB_s and shaderProgram_s parsed from the same shbin, as
// playermodel.c does, so nothing is shared at runtime and no two of them can disturb each
// other's uniform locations.
static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;
static int             s_uloc_fogparams;

// One program for the whole process, built the first time and never torn down. Init/Exit run
// per session — join a world, leave, join again — and shaderProgramFree does not null
// program->vertexShader while citro3d separately caches a pointer to the last program it
// bound. Freeing and rebuilding this static across a rejoin is the exact use-after-free that
// hard-crashes the console, already paid for once in this project.
static bool s_shader_ready;

typedef struct { float x, y, z; } BbVertex;

// ── ATTRIBUTE ALIGNMENT, CHECKED RATHER THAN ASSUMED ─────────────────────────────────
//
// A 3-component attribute placed before a 4-component one lands UNALIGNED on this hardware
// and FREEZES a real console while every emulator shrugs. It is worth writing down that this
// buffer cannot hit that, and why:
//
//   * There is exactly ONE attribute. AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3) below is the
//     only loader added, so there is no second attribute for this one to be misaligned
//     against — the hazard needs two.
//   * The stride is sizeof(BbVertex) == 12, a multiple of the 4-byte component size, so every
//     vertex begins on a 4-byte boundary relative to the buffer base.
//   * linearAlloc returns memory aligned well past 4.
//
// This is byte-for-byte the vertex format scene/highlight.c and scene/playermodel.c already
// submit with this same shader, so it is a format the tree has been shipping, not a new one.
// The _Static_assert makes the stride claim a build failure rather than a comment.
_Static_assert(sizeof(BbVertex) == 12, "the one float3 attribute must be tightly packed");
_Static_assert((sizeof(BbVertex) % 4) == 0, "vertex stride must keep every float 4-aligned");

#define BB_MAX_VERTS (BB_MAX_SEGS * BB_VERTS_PER_SEG)

static BbVertex* s_verts;
static bool      s_ready;

// ── The cached fence ─────────────────────────────────────────────────────────────────

static BiomeBorderSeg s_segs[BB_MAX_SEGS];

// One contiguous run of vertices per neon colour, so the whole overlay is at most BIOME_COUNT
// draw calls no matter how many segments it holds.
typedef struct { int first, count; uint32_t colour; } BbRun;
static BbRun s_runs[BIOME_COUNT];
static int   s_nruns;

// Which column the cached fence was built around. s_have is the "is it valid" flag rather
// than a sentinel column value, because there is no column coordinate that cannot occur.
static bool    s_have;
static int32_t s_px, s_pz;

void biomeBorderDrawInvalidate(void) { s_have = false; s_nruns = 0; }

bool biomeBorderDrawInit(void)
{
	if (!s_shader_ready) {
		s_dvlb = DVLB_ParseFile((u32*)highlight_shbin, highlight_shbin_size);
		if (!s_dvlb)
			return false;
		shaderProgramInit(&s_program);
		shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);

		s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
		s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
		s_uloc_fogparams  = shaderInstanceGetUniformLocation(s_program.vertexShader, "fogParams");
		s_shader_ready = true;
	}

	s_verts = (BbVertex*)linearAlloc(sizeof(BbVertex) * BB_MAX_VERTS);
	if (!s_verts)
		return false;

	biomeBorderDrawInvalidate();
	s_ready = true;
	return true;
}

void biomeBorderDrawExit(void)
{
	if (s_verts)
		linearFree(s_verts);
	s_verts = NULL;
	s_ready = false;
	biomeBorderDrawInvalidate();

	// The shader is deliberately not freed — see s_shader_ready above.
}

// Rebuilds the vertex buffer around column (px, pz). Runs only when the toggle is ON and the
// player has stepped into a different column, so a standing player pays nothing and a walking
// one pays it about once a second.
static void rebuild(const WorldGen* g, int32_t px, int32_t pz)
{
	s_nruns = 0;
	s_px = px; s_pz = pz; s_have = true;

	const int n = biomeBorderBuild(g, px, pz, BB_RADIUS, s_segs, BB_MAX_SEGS);
	if (n <= 0)
		return;

	// One bucket per neon colour, filtered straight out of the segment list so the runs come
	// out contiguous with no second array to sort into. See biomeborder.h.
	int used = 0;
	for (int key = 0; key < BIOME_COUNT; key++) {
		float* dst = (float*)s_verts + (size_t)used * 3;
		const int cap = (BB_MAX_VERTS - used) * 3;
		const int wrote = biomeBorderVerts(g, s_segs, n, key, dst, cap);
		if (wrote <= 0)
			continue;   // no segments in this bucket, or no room left for all of them

		const int verts = wrote / 3;
		s_runs[s_nruns].first  = used;
		s_runs[s_nruns].count  = verts;
		s_runs[s_nruns].colour = biomeBorderBiomeColour((BiomeId)key);
		s_nruns++;
		used += verts;
	}

	// Built by the CPU, read from RAM by the GPU. linearAlloc memory is cached, so without
	// this the GPU reads whatever the linear heap held before rebuild ran — the same flush
	// scene/highlight.c does after buildCage, and for the same reason.
	if (used > 0)
		GSPGPU_FlushDataCache(s_verts, sizeof(BbVertex) * (size_t)used);
}

void biomeBorderDraw(const C3D_Mtx* view)
{
	// THE OFF PATH. Everything the feature costs when the toggle is off is this line: a load
	// of one byte from .bss and a branch. No build, no GPU state, no draw call — so the frame
	// is byte-for-byte the frame drawn before this overlay existed.
	if (!biomeBorderEnabled())
		return;

	if (!s_ready)
		return;   // failed init degrades to "no overlay", not a crash

	const WorldGen* g = biomeBorderWorldGen();
	if (!g)
		return;   // nothing handed the world over; draw no fence rather than a guessed one

	// The player's column, taken from the renderer's own camera so the overlay is centred on
	// what is actually being drawn rather than on a second copy of the player position that
	// could drift from it. floorf and not a cast: a cast truncates toward zero, which would
	// put every column in x < 0 one step east of where the player stands, and the seam would
	// sit one block off on exactly half the map. Silent, and only visible as "it looks right
	// near spawn".
	float ex, ey, ez;
	chunkRenderCamera(&ex, &ey, &ez);
	(void)ey;
	const int32_t px = (int32_t)floorf(ex);
	const int32_t pz = (int32_t)floorf(ez);

	if (!s_have || px != s_px || pz != s_pz)
		rebuild(g, px, pz);

	if (s_nruns == 0)
		return;

	// Nothing below is put back afterwards, deliberately: chunkRenderDraw re-establishes its
	// whole pipeline at the top of every call precisely so a second pass like this one does
	// not have to carry a duplicate copy of the world's state in order to restore it. Same
	// contract scene/highlight.c and scene/playermodel.c draw under.
	C3D_BindProgram(&s_program);

	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(BbVertex), 1, 0x0);

	// Flat constant colour through TEV stage 0, no texture and no blending. GPU_REPLACE and
	// not GPU_MODULATE: the fence must be an emitted light, not the terrain shading tinted,
	// or it would fade out over dark ground exactly where a seam is hardest to see.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_CONSTANT, 0, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

	// TEV stage 1 and the fog unit, OWNED here rather than inherited from the world pass —
	// the same ownership scene/highlight.c took in v1.9.0. pipelineBind leaves stage 1
	// interpolating toward the sky colour by texture unit 1, for which this shader writes no
	// coordinate at all, so a fence drawn without resetting it would be shaded by an unwritten
	// texcoord. A debug marker that fades with distance would also be worse than useless: the
	// far end of a seam is the part worth seeing.
	C3D_TexEnv* fog = C3D_GetTexEnv(1);
	C3D_TexEnvInit(fog);
	C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);

	// The vertex half of the same. (0, 0) drives the ramp coordinate to 0 at every vertex,
	// which samples texel 0, which gfx/fogramp.c pins at exactly 0. An upload rather than a
	// comment about a default: uniform registers are global GPU state and scene/playermodel.c
	// writes real values into this one whenever a remote player is on screen, so leaving it
	// unwritten would make the fence fog or not depending on whether anyone else was visible.
	C3D_FVUnifSet(GPU_VERTEX_SHADER, s_uloc_fogparams, 0.0f, 0.0f, 0.0f, 0.0f);

	// A fence is one quad thick and is looked at from both sides — from inside either biome.
	C3D_CullFace(GPU_CULL_NONE);

	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, chunkRenderProjection());

	// The vertices are ABSOLUTE world block coordinates, so the model matrix is the identity
	// and the modelView is the view itself. scene/highlight.c multiplies in a translate only
	// because its cage is built at the origin and moved to the block; this geometry is built
	// where it stands, because a seam is not at any one block.
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, view);

	// One draw per colour. The TEV constant is the only thing that changes between them.
	for (int i = 0; i < s_nruns; i++) {
		C3D_TexEnvColor(env, s_runs[i].colour);
		C3D_DrawArrays(GPU_TRIANGLES, s_runs[i].first, s_runs[i].count);
	}
}
