#include "scene/chunk_render.h"

#include <math.h>
#include <string.h>

#include "app/drawprobe.h"
#include "app/watchdog.h"
#include "debug/metrics.h"
#include "gfx/atlas.h"
#include "world/dirtyq.h"
#include "world/light.h"
#include "world/mesher.h"
#include "world/remesh.h"
#include "scene/frustum.h"
#include "scene/render_dist.h"
#include "world/scratch.h"
#include "world/visgraph.h"
#include "world_shbin.h"   // generated by picasso from source/shaders/world.v.pica
#include "world_dynamic_shbin.h"   // picasso, source/shaders/world_dynamic.v.pica

// Step 7.1, overridable so the check can go red: -DBS_FRUSTUM=0 draws every live slot, and
// the two builds must produce a pixel-identical frame or the cull is eating visible geometry.
#ifndef BS_FRUSTUM
#define BS_FRUSTUM 1
#endif

// Step 7.2, same idea: -DBS_SORT=0 draws in slot order. The frame must be identical either
// way — this is opaque geometry behind a depth test — so the thing that has to differ
// between the two builds is chunkRenderSortMoved(), not the pixels.
#ifndef BS_SORT
#define BS_SORT 1
#endif

// The deliberate stall that proves the draw-stage breadcrumb can report a freeze inside a
// pass. Defined here rather than only at the use site so the default is visible next to the
// other build switches. See the block it guards, in the opaque loop of chunkRenderDraw.
#ifndef BS_DRAW_HANG_TEST
#define BS_DRAW_HANG_TEST 0
#endif

// Validates every chunk draw before it is issued, and refuses the ones that are not safe.
// See drawSane() for what it checks and why those four things and not others.
//
// It is a diagnostic first: a console that freezes with this on has hang.txt say whether a
// bad draw was ever seen, which is the difference between "the GPU was handed an address it
// could not read" and "the commands were fine and it stopped for some other reason". Refusing
// the draw as well as recording it is not a guess at the fix — a draw that reaches outside the
// buffer bound for it has no correct behaviour to fall back on.
//
// Off by default:  make EXTRA_CFLAGS="-DBS_DRAW_GUARD=1"
#ifndef BS_DRAW_GUARD
#define BS_DRAW_GUARD 0
#endif

// Deliberately corrupts one draw so the guard above can be seen going red. See drawIndices.
#ifndef BS_DRAW_GUARD_REDTEST
#define BS_DRAW_GUARD_REDTEST 0
#endif

// Step 7.3, cave culling. -DBS_CAVECULL=0 skips the walk entirely and draws whatever the
// frustum kept. Unlike the two above, this one is not merely an instrumentation switch: the
// frame must still be identical between the two builds, and if it ever is not, this flag is
// how the difference gets bisected without reverting anything.
#ifndef BS_CAVECULL
#define BS_CAVECULL 1
#endif

// Step 9.2, face-direction buckets. -DBS_FACEMASK=0 draws each chunk's whole opaque run as
// one call, which is what shipped before. Same rule as the three above: the two builds must
// produce a pixel-identical frame. They must NOT produce the same triangle count — that is
// the point of the step, and a build where `tris` did not move would mean the mask is
// selecting everything and the optimisation is not running.
#ifndef BS_FACEMASK
#define BS_FACEMASK 1
#endif

// Step 9.3, cull once per frame instead of once per eye. -DBS_CULLCACHE=0 re-culls on every
// chunkRenderDraw, i.e. twice in a 3D frame. Identical frame either way; the difference is
// chunkRenderCullRuns(), which is 1 in a 3D frame with this on and 2 with it off.
#ifndef BS_CULLCACHE
#define BS_CULLCACHE 1
#endif

// Step 9.1e, horizon culling: a candidate chunk whose whole box sits below the silhouette a
// nearer, taller column already casts (roughly the same bearing from the camera, top elevation
// angle already higher) cannot be on screen, whatever the frustum and the sight walk think.
// -DBS_HORIZON=0 skips the test and draws whatever 7.1/7.3 kept — same rule as BS_CAVECULL:
// the frame must be pixel-identical either way, and chunkRenderHorizonCulled() is how the
// measurement is told apart from a rendering difference.
#ifndef BS_HORIZON
#define BS_HORIZON 1
#endif

// Baked per-face brightness, the values Phase 1 proved on the single cube: a high sun
// leaning south-east, no two faces sharing a value, so a wrong normal index shows up as
// an obviously wrong wall instead of a subtle one. Written by name so the face order in
// world/block.h is enforced by the compiler here rather than by a comment.
static const float kFaceShade[BLOCK_FACES] = {
	[FACE_EAST]   = 0.78f,   // +X
	[FACE_WEST]   = 0.66f,   // -X
	[FACE_TOP]    = 1.00f,   // +Y
	[FACE_BOTTOM] = 0.48f,   // -Y
	[FACE_SOUTH]  = 0.86f,   // +Z
	[FACE_NORTH]  = 0.72f,   // -Z
};

typedef struct {
	// Step 9.2b. No per-slot index buffer any more. meshChunk's emitFace always advances
	// vert_count by exactly 4 per quad, in the same order it writes that quad's six indices
	// (base, base+1, base+2, base, base+2, base+3 — see mesher.c), so quad k of ANY chunk
	// occupies vertices [4k, 4k+4) and produces those identical six values regardless of
	// which face-direction bucket or opaque/transparent pass it fell in. One buffer sized for
	// the largest slot (s_shared_indices, built once in chunkRenderInit) is therefore correct
	// for every slot at once, and this struct only needs to remember counts and offsets into
	// it — face_start below, plus index_count and opaque_index_count.
	MeshVertex* verts;

	// Step 9.2c. How big *this* slot's `verts` buffer actually is, in vertices — 2048, 4096
	// or 8192 depending which of the three tiers this slot index belongs to (see
	// TIER_S/M/L_FACES). Not always MESH_SLOT_VERTS any more: that used to be true for
	// every slot because there was only one size. Read by acquireSlot to decide whether an
	// already-owned slot still fits a chunk that just grew.
	uint32_t vert_cap;

	int      cx, cy, cz;
	uint32_t vert_count;
	uint32_t index_count;

	// Step 7.5. Where the opaque run ends and the transparent one begins inside the same
	// index buffer. Faces in [0, opaque_index_count) are drawn in the first pass and the
	// rest in the second, alpha-tested one. Equal to index_count when the chunk has no
	// transparent geometry, which is most of them.
	uint32_t opaque_index_count;

	// Step 9.2. The mesher's face_start, carried through unchanged: where each of the six
	// face buckets starts inside the opaque run, plus a closing entry equal to
	// opaque_index_count. Indexed by bucket slot — slot i holds the direction kFaceOrder[i].
	// See mesher.h for the layout and drawOpaque for what reads it.
	uint32_t face_start[BLOCK_FACES + 1];

	bool     used;         // owns a chunk (even if that chunk meshed to nothing)

	// Step 7.3. Which of this chunk's six faces sight can pass between, computed once when
	// the chunk is meshed rather than once per frame — it is a flood fill over 4,096 cells
	// and the chunk it describes usually survives for thousands of frames.
	uint16_t vis_mask;
} MeshSlot;

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;
static int             s_uloc_faceshade;

// v1.5.0 adaptive lighting. Which shbin chunkRenderInit parsed into s_program:
// the baked one everywhere, the dynamic one on a New 3DS only. The choice is made
// once here and never again — every uniform location below is fetched from
// whichever program was parsed, so nothing downstream knows or cares which
// variant is bound, and an Old 3DS's draw path is instruction-for-instruction
// what it always was.
static bool            s_dynamic;
static int             s_uloc_daylevel;

bool chunkRenderDynamicLighting(void) { return s_dynamic; }

// Step 7.7. The clip planes and the fog now come from the render distance setting instead of
// being constants here, because they are functions of it — see render_dist.h, where the whole
// relationship and the reason `near` has to move with distance are written down. Held in one
// struct so the projection and the fog LUT cannot be built from different numbers, which is
// the failure step 6.4 warned about: feed FogLut_Exp a different near or far than the
// projection uses and the fog lands at distances the depth buffer never produces.
//
// Zero until chunkRenderInit calls chunkRenderSetDistance, which it does before returning and
// before any frame can be drawn. Nothing reads it in between — a projection built from a
// zeroed near and far would be degenerate, so the ordering inside chunkRenderInit is load
// bearing rather than tidy.
static RenderDist s_dist;

// Step 6.4. Fog is free on this GPU — a fixed-function stage after the TEV, no fragment
// shader involved, since the PICA200 has not got one — and it is what makes a small mesh
// ring liveable: terrain fades into the sky instead of the load boundary popping in.
//
// The numbers are chosen against where the hardware can actually *put* a knot, which is the
// whole trick. The fog LUT is 128 entries indexed by 1/w, so entry i sits at view distance
// far*near/(i/128*(far-near)+near) — hyperbolic, and with near 0.1 that is:
//
//   entry 0 -> 200.00 blocks    entry 3 -> 4.18
//   entry 1 ->  12.03           entry 4 -> 3.15
//   entry 2 ->   6.21           entry 8 -> 1.59
//
// Everything between 12 blocks and the far plane is ONE linear segment. Step 6.4 hardcoded a
// density that reached 0.5% visibility right at entry 1; step 7.7 derives it instead, from
// the render distance and against the *interpolated* curve rather than the exponential —
// renderDistFor() in render_dist.c, which is where all of that reasoning now lives and where
// the host suite can check it.
//
// Overridable so the check can go red: -DFOG_DENSITY=0.0f makes every LUT entry exp(-0) = 1,
// which is "no fog" through this exact code path rather than a different one. The override
// replaces the derived value; there is deliberately no override for the gradient, which is
// constant across the whole distance range anyway.
#ifndef FOG_DENSITY
#define FOG_DENSITY  (s_dist.fog_density)
#endif

// Step 7.6. The field of view lives here now instead of inline in chunkRenderInit, because
// the mono and the two stereo projections must all be built from the same one — an eye
// matrix a degree off the other would read as eye strain rather than as a bug.
#define VIEW_FOV_DEG  65.0f

// How far apart the eyes are, in blocks, at the 3D slider's maximum, and how far away the
// plane that lands *on* the screen is. Both are comfort settings rather than physical ones:
// the real interocular distance would be about 0.065 m, and a block is nominally a metre, so
// 0.20 is a little over three times human separation — the exaggeration is deliberate and
// standard for a handheld, because the screen is small and a physically correct separation
// reads as almost flat on it. The focal length is what decides how much of the world sits
// *behind* the screen rather than in front of it; 4 blocks puts the convergence plane a bit
// beyond arm's reach, so terrain recedes into the screen and nothing painful pokes out of it.
//
// These are the two numbers to change if the effect reads wrong, and they are the only ones.
#define STEREO_MAX_IOD    0.20f
#define STEREO_FOCAL_LEN  4.0f

static C3D_FogLut s_fog_lut;

static C3D_Mtx  s_projection;

// Step 9.3. The mono projection, kept alongside the per-eye one. The cull runs from this and
// never from s_projection, so a 3D frame culls once against a shape both eyes fit inside
// instead of twice against two shapes that differ by a fifth of a block. Rebuilt whenever the
// render distance moves the clip planes; nothing else can change it.
static C3D_Mtx  s_mono_projection;

// Step 9.2b. ONE index buffer shared by every slot, replacing what used to be MESH_SLOTS
// separate 24 KB linearAlloc's — see the comment on MeshSlot for why one buffer is correct
// for all of them. Filled once in chunkRenderInit and never written again: it has to be
// linear memory because C3D_DrawElements DMAs straight out of it, but nothing about its
// content depends on any chunk, so "once" is not a simplification here, it is the whole
// content.
static uint16_t* s_shared_indices;

// Step 9.2c. Every slot used to reserve MESH_SLOT_VERTS (2048 faces, 64 KB) regardless of
// what the chunk in it actually needed — the comment on slotFor below is what this step was
// named for. Measured on the host (world/mesher.c and world/worldgen.c are <3ds.h>-free, so
// this ran as real terrain generation + meshing on the PC, not a guess) across six worldgen
// seeds at the pool's own ring size (25 columns, matching how MESH_SLOTS is derived): the
// worst single chunk observed used 68.8 % of a slot, but the average was 20–25 %, and 58–66 %
// of every live slot's bytes were unused. Full numbers in the vault log for this step.
//
// Three fixed-size tiers fix it without touching what makes the flat pool safe under the
// player's load/unload churn: every slot *inside one tier* is still bit-identical in size
// and recycled in place, exactly like the old single-size pool always was — nothing here can
// fragment, because nothing here ever splits or coalesces a buffer. A chunk that needs more
// than its tier holds does not grow in place; it moves to a slot in a bigger tier and the old
// one goes back to its own tier's pool, same operation as claiming any other free slot.
//
// Cut points and slot counts are measured, not round numbers picked by eye: the same host
// sample put 58–64 % of live chunks under 512 faces, 97.6–99.2 % under 1024, and never above
// 1409 of the 2048-face absolute cap (worldgen's cave carving is what keeps any single chunk
// from ever reaching the pathological checkerboard MESH_SLOT_FACES is sized against). Tier L's
// cap is MESH_SLOT_FACES itself, so a pathological world is refused exactly as before —
// nothing about the absolute worst case regresses.
//
// ── v1.6.0 task 12: re-cut for RENDER_DIST_MAX 3 ────────────────────────────────────────
//
// Sizing a tier at a time is WRONG here, and the old 70/60/20 comment above hid that by
// quoting a per-tier occupancy (64/56/9). acquireSlot() below spills UPWARD ONLY: a chunk
// needing more than 1024 faces can only be served by L, one needing more than 512 by M or L,
// and any chunk at all by S, M or L. So what the pool has to satisfy is a SUFFIX constraint —
//
//     L      >= max simultaneous chunks over 1024 faces
//     M + L  >= max simultaneous chunks over  512 faces
//     S+M+L  >= max simultaneous meshed chunks
//
// — and that is also sufficient, because smallest-fit with upward spill is optimal against it
// (it is Hall's condition on the tier suffixes: if every suffix's capacity covers its own
// demand, no arrival order can strand a chunk).
//
// Measured with the REAL mesher and the REAL worldgen on the host, the way step 9.2c's own
// numbers were taken and the way tools/run_greedy_probe.sh links: 8 seeds (1337, 2026, 42,
// 99991, 7, 123456, 8675309, 55) x 5 area centres far apart in the world (0,0 / 400,-270 /
// -1130,640 / 2900,3100 / -4210,-1750), 17x17 columns generated at each so every measured
// column has all eight neighbours present, then the radius-3 ring slid over the resulting
// face-count grid at 81 positions per area. 9,000 columns, 37,682 chunk meshes, 3,240 ring
// positions. Worst case over all of them:
//
//     all meshed chunks in one radius-3 ring   242
//     of those, over  512 faces                103
//     of those, over 1024 faces                  8
//     largest single chunk                    1371 faces  (cap is 2048)
//
// The radius-2 control from the same run is 125 / 59 / 6, against the 129 / 65 / 9 implied by
// the 64/56/9 this file used to record. SAID OUT LOUD rather than overridden: the older figure
// is HIGHER than this one in every bucket, its raw sample could not be reconstructed, and a
// tail is a volume question — so it is treated here as evidence that the true tail is at least
// as long as measured, and the margins below are set against the older number, not this one.
//
// Hence 158/120/16 out of MESH_SLOTS = 294:
//
//     L     = 16  vs   8 measured (2.0x), vs ~12 scaling the older radius-2 figure to 49 columns
//     M + L = 136 vs 103 measured (1.32x)
//     total = 294 vs 242 measured (1.21x)
//
// Total bytes 7,593,984 (7.24 MB) including the shared index buffer, against 4,448,256
// (4.24 MB) before — +3.00 MB exactly, out of the 25.83 MB of linear heap the one hardware
// reading on record shows free. Minimising bytes subject to those margins is what picks the
// split: at a fixed 294 slots the cost is 4,816,896 + 16384*M + 49152*L, so every slot moved
// down a tier is a straight saving and the margins above are the only thing holding it up.
//
// ── v1.7.0: re-measured on the density generator, and the TOTAL had gone under ────────────
//
// Re-run with the real mesher on the real new worldgen — 4 seeds (1337, 4242, 90210, 5150) x
// 81 radius-3 ring positions on an 11-column stride, 324 rings, each ring generated in its own
// world with a one-column margin so no chunk meshes against unloaded-as-air. 90210 is in the
// sample deliberately: it is the ocean-heavy seed, water does not occlude, and the seabed
// under an ocean is still meshed, which is the likeliest single way this pool overruns.
//
//     all meshed chunks in one radius-3 ring   298   (was 242 — OVER the 294 the pool held)
//     of those, over  512 faces                 87   (was 103)
//     of those, over 1024 faces                  3   (was   8)
//     largest single chunk                    1262   (was 1371; cap is still 2048)
//     worst meshed chunks in one column          7   (was 5, against a constant of 6)
//
// The two directions cancel the wrong way round. Greedy merging made each chunk smaller — both
// tail buckets FELL, and so did the largest single chunk — but the density field's caves made
// more chunks non-empty, and the total is what the pool is sized by. 298 > 294, so the
// released v1.6.0 pool is four slots short of a ring the player will actually walk into, and a
// slot that cannot be supplied means acquireSlot returns NULL, s_refusals ticks, and the chunk
// is never meshed: a hole in the terrain, not a slow frame.
//
// The total is fixed at the source rather than here — scene/render_dist.h now derives
// RENDER_DIST_SLOTS_PER_COLUMN from COLUMN_CHUNKS, so MESH_SLOTS is 392 and covers a ring in
// which every chunk of every column is meshed, for any terrain any future generator produces.
// That makes TIER_MEASURED_WORST_ALL below a formality rather than the thing holding the roof
// up, which is the point: it was a measured floor, and a measured floor is what just failed.
//
// The two tail buckets keep the OLDER, HIGHER numbers (103 and 8, not 87 and 3), for the same
// reason the paragraph above keeps the radius-2 figure: a tail is a volume question, 324 rings
// is a tenth of the 3,240 the old sample walked, and slack in M and L is nearly free here.
// Deliberately NOT taken: recutting M from 120 to ~100 on the strength of the new 87. It would
// save 327,680 bytes out of 25.83 MB free while trading away a documented margin, and the
// standing rule on this project is that a margin is not spent for a saving nobody needs.
//
// Hence 256/120/16 out of MESH_SLOTS = 392:
//
//     L     = 16  vs   8 (2.0x)     — unchanged, and now 5.3x the new measurement
//     M + L = 136 vs 103 (1.32x)    — unchanged, and now 1.56x the new measurement
//     total = 392 vs 298 (1.32x)    — and structurally unbeatable, not a margin
//
// Total bytes 9,199,616 (8.77 MB), +1,605,632 on 7,593,984. Every added slot is S tier, the
// cheapest at 16,384 bytes; the cost formula at a fixed 392 slots is 6,422,528 + 16384*M +
// 49152*L, so the split arithmetic above is unchanged apart from its constant term.
#define TIER_S_FACES  512
#define TIER_M_FACES  1024
#define TIER_L_FACES  MESH_SLOT_FACES   // 2048 — unchanged absolute worst case

#define TIER_S_SLOTS  256
#define TIER_M_SLOTS  120
#define TIER_L_SLOTS  (MESH_SLOTS - TIER_S_SLOTS - TIER_M_SLOTS)   // 16 at MESH_SLOTS=392

_Static_assert(TIER_S_SLOTS + TIER_M_SLOTS + TIER_L_SLOTS == MESH_SLOTS,
               "tier slot counts must add up to the whole pool");
_Static_assert(TIER_L_SLOTS > 0, "tier sizes leave nothing for the largest tier");

// v1.6.0 task 12. The suffix constraint above, asserted HERE — next to the constants it
// constrains — rather than in a test. The tier counts are file-private #defines, so a test
// could only check its own copy of them, which is the exact failure this project has recorded
// twice (tests/battery_test.c and tests/sleep_test.c both passed with the real module
// deleted). A _Static_assert cannot be checked against a copy and cannot be forgotten to run:
// it is the console build.
//
// The three numbers are the measured worst radius-3 ring from the host probe described above.
// Raising RENDER_DIST_MAX again without re-measuring will not fail these — they are a floor on
// a KNOWN ring, not a prediction about a wider one — so re-measure, then move them.
//
// v1.7.0 read that warning the hard way: RENDER_DIST_MAX did not move, the WORLDGEN did, and a
// floor on a known ring is equally blind to that. ALL is now the v1.7.0 density measurement
// (298, up from 242); the two tail buckets keep the older higher figures on purpose, see the
// long comment above. The total no longer depends on any of it — MESH_SLOTS is derived from
// COLUMN_CHUNKS in scene/render_dist.h and structurally covers every possible ring.
#define TIER_MEASURED_WORST_ALL    298   // meshed chunks in one radius-3 ring, density gen
#define TIER_MEASURED_WORST_512    103   // ...of those, over TIER_S_FACES  (density says 87)
#define TIER_MEASURED_WORST_1024     8   // ...of those, over TIER_M_FACES  (density says  3)

_Static_assert(TIER_L_SLOTS >= TIER_MEASURED_WORST_1024,
               "acquireSlot spills upward only, so a chunk over TIER_M_FACES can be served by "
               "tier L alone: L must cover every such chunk the widest ring can hold at once");
_Static_assert(TIER_M_SLOTS + TIER_L_SLOTS >= TIER_MEASURED_WORST_512,
               "a chunk over TIER_S_FACES can only be served by M or L, so their combined "
               "count must cover every such chunk the widest ring can hold at once");
_Static_assert(TIER_S_SLOTS + TIER_M_SLOTS + TIER_L_SLOTS >= TIER_MEASURED_WORST_ALL,
               "the whole pool must cover every meshed chunk the widest ring can hold at once");

// And the cut points themselves, because the measured numbers above are counts of chunks
// "over TIER_S_FACES" and "over TIER_M_FACES" — they mean nothing if those two move without
// the measurement being redone.
_Static_assert(TIER_S_FACES == 512 && TIER_M_FACES == 1024,
               "the tier occupancy measurement is stated against these two cut points; "
               "re-measure before changing either");

static const int kTierFaces[3] = { TIER_S_FACES, TIER_M_FACES, TIER_L_FACES };
static const int kTierSlots[3] = { TIER_S_SLOTS, TIER_M_SLOTS, TIER_L_SLOTS };

// One linearAlloc per tier, carved into kTierSlots[t] equal pieces of kTierFaces[t]*4
// vertices each — see chunkRenderInit. s_tier_start/s_tier_count say which range of
// s_slots[] belongs to which tier; set once at init and never moved.
static MeshVertex* s_tier_arena[3];
static int         s_tier_start[3];
static int         s_tier_count[3];

static MeshSlot s_slots[MESH_SLOTS];

// Step 9.2c. Where meshChunk writes vertices now, instead of straight into a slot: the
// tiered pool cannot pick a slot until it knows out.vert_count, and that does not exist
// until meshChunk has already run. Plain BSS and not linearAlloc, exactly like
// s_index_scratch below and for the same reason — the GPU never reads this, only the
// memcpy in chunkRenderBuild does, once, into whichever tier's slot gets picked.
static MeshVertex s_vert_scratch[MESH_SLOT_VERTS];

// Which tier a chunk needing this many vertices belongs in, smallest that fits.
// need_verts can be 0 (an all-air chunk) up to MESH_SLOT_VERTS (meshChunk's own cap,
// passed as out.vert_cap below) — never more, so this always resolves to 0, 1 or 2.
static int tierForVerts(uint32_t need_verts)
{
	if (need_verts <= (uint32_t)TIER_S_FACES * 4) return 0;
	if (need_verts <= (uint32_t)TIER_M_FACES * 4) return 1;
	return 2;
}

// Step 9.2b. meshChunk's interface (world/mesher.h) always writes six index values per quad
// into its caller's buffer — that contract belongs to a file this step does not own, so it is
// unchanged. Every value it writes is always exactly what s_shared_indices already holds (see
// the comment on MeshSlot), so this is a write-only landing pad: chunkRenderBuild points
// meshChunk at it and only keeps the *counts* meshChunk also produces (vert_count,
// index_count, opaque_index_count, face_start). Plain BSS and not linearAlloc — the GPU never
// reads it, so it costs ordinary FCRAM and not the linear heap this step exists to shrink.
static uint16_t s_index_scratch[MESH_SLOT_INDICES];
static int      s_culled;        // chunks the frustum rejected on the last draw
static int      s_sort_moved;    // step 7.2: chunks the sort took out of slot order
static bool     s_sort_ok;       // ...and whether the emitted order really is near-to-far
static int      s_cave_culled;

// Step 7.5's evidence. Reported rather than inferred, for the same reason the cave-cull
// count is: "the canopy looks see-through" and "the second pass ran" are different claims,
// and a pass that silently drew nothing would look exactly like a chunk with no leaves in it.
static uint32_t s_alpha_tris;
static int      s_alpha_draws;

// The alpha test threshold for the transparent pass. See the draw loop for why it is the
// midpoint and not 0.
#define ALPHA_CUTOFF  127   // step 7.3: chunks no sight line reached
static bool     s_cave_ran;      // ...and whether the walk ran at all this frame
static int      s_refusals;
static size_t   s_bytes;

// Step 7.3's working memory, ~37 KB and ~18 KB. Static for the same reason MeshScratch is:
// the linear heap cannot be defragmented and the main thread's stack is 32 KB, so neither of
// these may be a local or an allocation.
static VisWalk    s_walk;
static VisScratch s_vis_scratch;

// Step 9.1e's working memory: one entry per column currently holding a live slot. Sized off
// RENDER_DIST_MAX_COLUMNS with margin rather than exactly at it, because a slot in flight
// during a distance change can briefly belong to a column outside the current radius. A column
// past the cap simply does not participate as a blocker — the safe direction, per the
// file-header rule every cull here follows: this may under-cull, it must never over-cull.
//
// v1.6.0 task 12. This was the literal 40, hand-derived from the 25 columns of
// RENDER_DIST_MAX 2. At MAX 3 the ring is 49 columns, so the literal was BELOW the ring it is
// supposed to cover — every ring position would have silently dropped at least nine columns
// from the blocker set. It degrades safely (that is the whole point of the paragraph above),
// which is exactly why it would never have been noticed: horizon culling would just have got
// quietly weaker at the render distance where it matters most, with nothing to see and no
// counter to read.
//
// Derived from RENDER_DIST_MAX_COLUMNS now rather than restated, so the next ceiling change
// cannot leave it behind the same way. +16 keeps the old margin's intent (40 was 25 + 15).
#define HZN_MAX_COLUMNS  (RENDER_DIST_MAX_COLUMNS + 16)

_Static_assert(HZN_MAX_COLUMNS > RENDER_DIST_MAX_COLUMNS,
               "the horizon blocker set must cover the whole widest ring, with room for a "
               "slot still in flight from a distance change");

typedef struct {
	int   cx, cz;
	float top_y;   // world-space y of the highest meshed chunk's ceiling in this column
} HznCol;

static HznCol s_hzn_cols[HZN_MAX_COLUMNS];
static int    s_hzn_n;
static int    s_horizon_culled;

// The camera position the walk used, recovered from the view matrix. Reported because that
// recovery is an inversion that is either exactly right or completely wrong, and comparing it
// against the camera main.c already holds is the only way to tell which — a walk started from
// the wrong chunk would still look plausible and cull the wrong half of the world.
static float s_cam_x, s_cam_y, s_cam_z;

// Step 9.3. The visible set, computed once per frame and consumed by each eye.
//
// The cache is keyed on the view matrix itself rather than on a frame counter the caller has
// to remember to tick. citro3d's stereo puts the eye offset in the *projection*, so both eyes
// of a 3D frame are handed the same view — a byte compare is therefore an exact answer to
// "is this the second eye of the frame I already culled?", and it cannot go stale the way a
// flag someone has to clear can. Moving the camera changes the matrix and re-culls; standing
// perfectly still does not, and the answer would be identical anyway. The one thing a view
// compare cannot see is the world changing underneath a still camera, so meshing, releasing
// and moving the clip planes all clear s_cull_valid explicitly.
static C3D_Mtx s_cull_view;
static bool    s_cull_valid;
static int     s_vis_list[MESH_SLOTS];
static float   s_vis_depth[MESH_SLOTS];
static int     s_vis_n;
static int     s_cull_runs;          // culls performed on the last frame: 1 in 3D, not 2

// Step 9.3, the other half: the sight walk depends only on which *chunk* the camera is in, so
// it survives every frame the player spends inside one — which at walking pace is most of
// them. Rotating the camera invalidates the frustum and not this, which is why the two are
// cached separately rather than under one flag.
static bool s_walk_valid;
static int  s_walk_cx, s_walk_cy, s_walk_cz;
static int  s_walk_runs;             // sight walks actually performed on the last frame

// The remesh backlog: one flag per slot in s_slots, parallel by index. A flag per slot
// rather than a list of coordinates, because it makes dedup free and impossible to get
// wrong — touching the same chunk twenty times in one frame sets the same bool twenty
// times, and the queue can never overflow because it cannot hold more entries than there
// are slots. A flag is only ever set while that slot's `used` is also true:
// chunkRenderTouch only queues chunks that already own a slot.
//
// The accounting lives in world/dirtyq.c and not here, which is not tidiness — this file
// includes <3ds.h> and citro3d, so nothing in it can be host-tested, and the count being
// three loose statics in this file is exactly how it shipped a double-decrement that
// silently stopped the world re-meshing. See world/dirtyq.h.
static DirtyQ s_dirty;

// Split profile of a remesh. "A chunk remesh costs 3.7 ms" is not actionable until it
// says which half is spending it: the scratch fill copies from up to 27 chunks, the
// mesher walks 4,096 cells and does the AO reads.
static u64 s_scratch_ticks;
static u64 s_mesh_ticks;
static u64 s_vis_ticks;      // step 7.3's flood fill, the cost this step adds to a remesh
static int s_build_count;

// One scratch for every chunk meshed — 5,832 bytes, reused, never per-chunk.
static MeshScratch s_scratch;

// Step 9.3. Everything the per-frame cull cached is now suspect. Called from wherever the
// *world* changes under a camera that may not have moved: the view-matrix compare cannot see
// a remesh, an unload, or a clip plane moving, and each of those can change which chunks are
// visible without the player touching the stick.
static void cullInvalidate(void)
{
	s_cull_valid = false;
	s_walk_valid = false;
}

// The buried-solid-rock skip that step 9.4 originally added lived here, and it is deliberately
// gone. The idea was sound — a chunk opaque all the way through with six opaque face neighbours
// meshes to exactly nothing — but the terrain this game generates never produces one. A census
// over an 11x11-column area on eight seeds (scratchpad/buryprobe.c, 2026-08-18) found 4,356
// chunks, 296 of them opaque all the way through, and **zero** with six opaque face neighbours:
// the step 5.4 cave noise perforates the deep rock everywhere, so a fully enclosed opaque
// neighbourhood does not occur. The test cost a 4,096-byte scan on every non-air chunk build to
// answer "no" every time, so it was strictly a loss. If the cave parameters ever change enough
// that solid regions appear, this is worth reinstating — the reasoning is in the vault log.

// Does chunk (cx,cy,cz) already own a slot? Pure lookup, independent of size — used both to
// recycle a slot in place and, when a chunk has outgrown its current tier, to know which
// slot must eventually be handed back.
static MeshSlot* findSlot(int cx, int cy, int cz)
{
	for (int i = 0; i < MESH_SLOTS; i++) {
		MeshSlot* s = &s_slots[i];
		if (s->used && s->cx == cx && s->cy == cy && s->cz == cz)
			return s;
	}
	return NULL;
}

// Claims a slot with room for need_verts, preferring the smallest tier that fits and
// borrowing from a bigger one only if that tier has nothing free. `exclude`, when not NULL,
// is a slot never to return — the chunk's own current (too-small) slot, so a tier upgrade
// cannot "claim" the very slot it is trying to replace out from under itself.
//
// Within one tier this is exactly the old single-pool slotFor's loop body: a slot nobody
// has ever claimed first, and only if there is none of those, a claimed slot whose chunk
// meshed to nothing (see the comment that used to sit here about not holding memory
// hostage from a dug-out chunk — the reasoning did not change, it just now applies inside
// each tier rather than across one pool).
static MeshSlot* acquireSlot(uint32_t need_verts, const MeshSlot* exclude)
{
	const int min_tier = tierForVerts(need_verts);

	for (int t = min_tier; t < 3; t++) {
		MeshSlot* empty_slot = NULL;
		const int start = s_tier_start[t];
		const int end   = start + s_tier_count[t];
		for (int i = start; i < end; i++) {
			MeshSlot* s = &s_slots[i];
			if (s == exclude) continue;
			if (!s->used) return s;
			if (s->index_count == 0 && !empty_slot) empty_slot = s;
		}
		if (empty_slot) return empty_slot;
	}
	return NULL;
}

// Everything the world draw needs the GPU to be set to. Called once at init and then
// again at the top of every chunkRenderDraw, deliberately, rather than being left
// standing from init: step 4.2's highlight binds its own shader program and its own
// vertex format, and on the PICA200 the vertex shader's float uniform bank is shared
// hardware — a second program's uniforms land in the same registers and quietly
// overwrite faceShade. Re-establishing state per frame costs a handful of register
// writes and makes "who broke the lighting" a question that cannot be asked.
static void pipelineBind(void)
{
	C3D_BindProgram(&s_program);

	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	// FOUR components on attribute 0, not three, and the fourth is MeshVertex.pad — a byte the
	// shader never reads. It is declared solely so that attribute 1 begins at byte offset 4
	// instead of byte offset 3.
	//
	// citro3d has no per-attribute offset. The PICA200 derives each attribute's offset inside the
	// vertex from the running total of the sizes declared before it, so `3 signed bytes` followed
	// by `4 unsigned bytes` puts a four-byte fetch on offset 3 of an 8-byte stride, on every
	// vertex, forever. That is what shipped from v1.1.0 to v1.2.4 and it is the freeze: an x86
	// host does unaligned loads without noticing, which is why twelve builds of this never once
	// reproduced in Azahar, while the real GPU wedged on the first world frame. Read straight out
	// of the hardware capture of the hung frame: ATTRIBBUFFERS_FORMAT_LOW = 0x000000d8.
	//
	// gfx/sprite.c declares 3 floats + 2 floats + 4 unsigned bytes = every attribute 4-byte
	// aligned, and its draws land correctly on the console in the very frames the chunk draw
	// hangs. That was the control that identified this.
	//
	// 4 + 4 now also equals the 8-byte stride exactly, so there is no longer any byte of the
	// vertex the attribute configuration does not account for.
	//
	// The dynamic path reads pad back (sky<<4 | block), and pad reaches 255 — so when
	// s_dynamic, attribute 0 must be fetched UNSIGNED. GPU_BYTE is a signed fetch
	// (libctru enums.h: GPU_BYTE = 0, GPU_UNSIGNED_BYTE = 1), and a signed read of 0xF0
	// hands the shader -16: every sunlit surface would unpack as unlit. Positions are
	// chunk-local 0..16, all non-negative, so the wider type changes nothing about them;
	// the baked path keeps GPU_BYTE exactly as it has always been.
	AttrInfo_AddLoader(attr, 0, s_dynamic ? GPU_UNSIGNED_BYTE : GPU_BYTE, 4); // v0 = position, + pad to align v1
	AttrInfo_AddLoader(attr, 1, GPU_UNSIGNED_BYTE, 4);   // v1 = u, v, normal, ao

	// The atlas, rebound here for exactly the reason the comment above gives about shader
	// uniforms: the texture binding is one more piece of shared global state, and step 8.3's
	// sprite batch takes unit 0 for the font sheet. Binding once inside atlasInit was correct
	// only while nothing else in the program ever bound a texture.
	atlasBind();

	// No fragment shader: TEV stage 0 multiplies the atlas sample by the vertex
	// colour, which is where the baked face shade and AO land.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

	C3D_DepthTest(true, GPU_GREATER, GPU_WRITE_ALL);
	C3D_CullFace(GPU_CULL_BACK_CCW);

	// Off here and turned on only for step 7.5's second pass. Global GPU state again, so
	// leaving it on would alpha-test the opaque world against an alpha channel that is 255
	// everywhere — harmless today, and exactly the kind of thing that stops being harmless
	// the moment another tile grows a hole.
	C3D_AlphaTest(false, GPU_ALWAYS, 0);

	// Fog, re-established per frame for the same reason everything else here is: this is
	// global GPU state, not per-program state, and the moment a second pass touches it there
	// is no owner. The gas mode argument is only read when the fog mode is GPU_GAS, and the
	// zFlip argument is false because Mtx_PerspTilt is fed the same near/far the LUT was
	// built from — flipping it would run the curve backwards, fogging the player's hands and
	// leaving the horizon sharp, which is what this was checked against.
	C3D_FogGasMode(GPU_FOG, GPU_PLAIN_DENSITY, false);
	C3D_FogColor(SKY_FOG_BGR);
	C3D_FogLutBind(&s_fog_lut);

	for (int f = 0; f < BLOCK_FACES; f++) {
		const float s = kFaceShade[f];
		C3D_FVUnifSet(GPU_VERTEX_SHADER, s_uloc_faceshade + f, s, s, s, 1.0f);
	}

	// The dynamic shader's day-night multiplier. No cycle exists yet (v1.5.0 scope
	// honesty), so it is pinned to full day: max(sky*1, block)/15 is exactly the
	// baked look wherever sky light is 15 and only underground does it fall.
	if (s_dynamic)
		C3D_FVUnifSet(GPU_VERTEX_SHADER, s_uloc_daylevel, 1.0f, 1.0f, 1.0f, 1.0f);
}

bool chunkRenderInit(void)
{
	// Fails if the pool ever outgrows DIRTYQ_MAX, at startup, rather than writing past
	// the flag array the first time a chunk in a high slot is edited.
	//
	// "At startup" was too late, and v1.6.0 proved it: DIRTYQ_MAX was left at 150 when
	// MESH_SLOTS went to 294, so this line returned false on the released build and main.c
	// printed "shader/atlas/pool init FAILED" instead of starting the game. See the long
	// comment on DIRTYQ_MAX in world/dirtyq.h. The runtime check below stays, but the
	// mismatch it guards against is now caught by the compiler in the one translation unit
	// that can see both constants — dirtyq.h cannot include chunk_render.h (it must stay
	// free of <3ds.h>), so this is the only place the two can be compared at all.
	_Static_assert(DIRTYQ_MAX >= MESH_SLOTS,
	               "the remesh backlog needs one flag per mesh slot: DIRTYQ_MAX in "
	               "world/dirtyq.h is a hand-maintained copy of MESH_SLOTS and has gone "
	               "under it, which makes chunkRenderInit fail and the game refuse to boot");
	if (!dirtyqInit(&s_dirty, MESH_SLOTS))
		return false;

	// v1.5.0 adaptive lighting. The console model decides which shader variant is
	// parsed into s_program — the baked one or the dynamic one that unpacks the
	// mesher's pad byte — and whether world/light.c's engine ever allocates or
	// propagates anything. Asked here rather than passed down from main.c because
	// this is the one place that already owns the shader program's lifetime, and
	// it runs before workerStart, so the gate is published before the thread that
	// reads it exists.
	//
	// On an Old 3DS none of this runs: the baked shbin is parsed exactly as
	// before, lightEngineInit never enables, and every lighting branch in the
	// mesher and the worker is dead code behind a false flag.
	bool n3ds = false;
	APT_CheckNew3DS(&n3ds);
	if (n3ds) {
		s_dvlb = DVLB_ParseFile((u32*)world_dynamic_shbin, world_dynamic_shbin_size);
		if (!s_dvlb)
			return false;
		s_dynamic = true;
		lightEngineInit(true);
	} else {
		s_dvlb = DVLB_ParseFile((u32*)world_shbin, world_shbin_size);
		if (!s_dvlb)
			return false;
	}
	shaderProgramInit(&s_program);
	shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);
	C3D_BindProgram(&s_program);

	s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
	s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
	s_uloc_faceshade  = shaderInstanceGetUniformLocation(s_program.vertexShader, "faceShade");
	if (s_dynamic)
		s_uloc_daylevel = shaderInstanceGetUniformLocation(s_program.vertexShader, "dayLevel");

	// Step 9.2b. The one shared index buffer every slot draws from, built once and never
	// written again — see the comment on s_shared_indices. Every quad's pattern is
	// {v, v+1, v+2, v, v+2, v+3} relative to its own base vertex v = 4 * (quad's position in
	// the slot), the same fill sprite.c already uses for its one shared quad buffer.
	s_shared_indices = (uint16_t*)linearAlloc(sizeof(uint16_t) * MESH_SLOT_INDICES);
	if (!s_shared_indices)
		return false;
	for (int q = 0; q < MESH_SLOT_FACES; q++) {
		const uint16_t v   = (uint16_t)(q * 4);
		uint16_t*      idx = &s_shared_indices[q * 6];
		idx[0] = v;     idx[1] = (uint16_t)(v + 1); idx[2] = (uint16_t)(v + 2);
		idx[3] = v;     idx[4] = (uint16_t)(v + 2); idx[5] = (uint16_t)(v + 3);
	}
	// Written by the CPU, read by the GPU, never written again — so one flush here, and the
	// indices in RAM match the indices in the cache for the rest of the run. See the flush in
	// chunkRenderBuild for what happens without one.
	GSPGPU_FlushDataCache(s_shared_indices, sizeof(uint16_t) * MESH_SLOT_INDICES);
	s_bytes += sizeof(uint16_t) * MESH_SLOT_INDICES;   // once, not once per slot

	// Step 9.2c. The vertex buffers, one linearAlloc per TIER now rather than per slot —
	// see the comment on TIER_S_FACES for the measurement this sizing comes from. Each
	// tier's arena is carved into kTierSlots[t] equal pieces up front, same as the old
	// per-slot loop did for one uniform size; what changed is that there are three sizes
	// instead of one; If the console cannot give us this much linear memory we want to
	// know at startup, not when the player walks somewhere new — same rule as before.
	int next_slot = 0;
	for (int t = 0; t < 3; t++) {
		const uint32_t cap_verts = (uint32_t)kTierFaces[t] * 4;
		const size_t   bytes     = sizeof(MeshVertex) * (size_t)cap_verts * (size_t)kTierSlots[t];

		s_tier_arena[t] = (MeshVertex*)linearAlloc(bytes);
		if (!s_tier_arena[t])
			return false;
		s_bytes += bytes;

		s_tier_start[t] = next_slot;
		s_tier_count[t] = kTierSlots[t];
		for (int i = 0; i < kTierSlots[t]; i++) {
			s_slots[next_slot + i].verts    = s_tier_arena[t] + (size_t)i * cap_verts;
			s_slots[next_slot + i].vert_cap = cap_verts;
		}
		next_slot += kTierSlots[t];
	}

	if (!atlasInit())
		return false;

	// Step 7.7. The fog LUT and the projection both come from here, and both have to exist
	// before the first frame. Radius 1 rather than the console's default: main.c owns the
	// default (it is the one that can ask APT_CheckNew3DS) and calls this again with it.
	chunkRenderSetDistance(RENDER_DIST_MIN);

	pipelineBind();
	return true;
}

// Step 7.7. Points the renderer at a render distance: rebuilds the fog LUT for it and rebuilds
// the projection, which has a different near plane at each distance.
//
// Both, together, always. The LUT's knots are placed by `near` (see render_dist.h), so a fog
// table built for one near plane and a projection built for another put the fade at distances
// that do not exist — which is the exact failure 6.4's comment warned about, made reachable
// by the setting becoming variable.
//
// Called before the first frame and again on every change. Cost is 128 exponentials and a
// matrix, on a player action, so there is nothing to defer.
void chunkRenderSetDistance(int radius)
{
	s_dist = renderDistFor(radius);

	// 512 bytes of exponentials, and nothing about it changes per frame — only the three
	// register writes that point the GPU at it are repeated, in pipelineBind.
	FogLut_Exp(&s_fog_lut, FOG_DENSITY, s_dist.fog_gradient, s_dist.near_plane,
	           s_dist.far_plane);
	C3D_FogLutBind(&s_fog_lut);

	// The mono projection, which is also what a 2D frame uses. A 3D frame overwrites it twice
	// per frame from drawEye anyway, so there is no eye state to preserve here.
	chunkRenderSetEye(0.0f);

	// Step 9.3. Kept separately from s_projection because the cull reads it every frame and
	// s_projection is whichever eye was drawn last. Built here rather than in chunkRenderSetEye
	// so it can only ever be the mono one.
	Mtx_PerspTilt(&s_mono_projection, C3D_AngleFromDegrees(VIEW_FOV_DEG), 400.0f / 240.0f,
	              s_dist.near_plane, s_dist.far_plane, false);

	// The clip planes just moved, so anything the last frame decided was off-screen may not be.
	cullInvalidate();
}

const RenderDist* chunkRenderDistance(void)
{
	return &s_dist;
}

// Step 7.6. Rebuilds the projection for one eye, and everything downstream — the frustum
// test, the sight walk, the draw, and the highlight, which reads this same matrix — follows
// it without knowing which eye it is looking through.
//
// iod 0 takes the mono branch rather than passing 0 to the stereo call. The two agree
// mathematically, but "2D is bit-for-bit the matrix it was before 7.6" is worth having as a
// fact rather than as an argument, given 2D is the default and the mode the game is judged in.
void chunkRenderSetEye(float iod)
{
	if (iod == 0.0f) {
		Mtx_PerspTilt(&s_projection, C3D_AngleFromDegrees(VIEW_FOV_DEG), 400.0f / 240.0f,
		              s_dist.near_plane, s_dist.far_plane, false);
		return;
	}
	Mtx_PerspStereoTilt(&s_projection, C3D_AngleFromDegrees(VIEW_FOV_DEG), 400.0f / 240.0f,
	                    s_dist.near_plane, s_dist.far_plane, iod, STEREO_FOCAL_LEN, false);
}

float chunkRenderMaxIod(void)
{
	return STEREO_MAX_IOD;
}

// The world's projection matrix, so the highlight can line its cage up with the blocks
// rather than carrying a second copy of the field of view and near/far planes that would
// silently drift out of step with this one.
const C3D_Mtx* chunkRenderProjection(void)
{
	return &s_projection;
}

void chunkRenderExit(void)
{
	atlasExit();
	// Step 9.2c. Three arenas now, not MESH_SLOTS individual allocations — every slot's
	// `verts` pointer is an offset into one of these, so freeing per-slot would free the
	// same block up to kTierSlots[t] times.
	for (int t = 0; t < 3; t++)
		linearFree(s_tier_arena[t]);
	linearFree(s_shared_indices);
	shaderProgramFree(&s_program);
	DVLB_Free(s_dvlb);
}

bool chunkRenderBuild(const World* w, int cx, int cy, int cz)
{
	// Step 9.2c. Looked up before anything else and independent of size: whether this
	// chunk already owns a slot decides both the empty-chunk path below and, in the
	// meshed path further down, whether a rebuild can recycle its slot in place or has to
	// move to a different tier. NULL just means "this chunk has never been drawn before".
	MeshSlot* existing = findSlot(cx, cy, cz);

	// Deliberately does not touch the dirty queue. Clearing the flag here looks like
	// tidiness and is how this shipped a bug for about three hours: the drain already
	// clears it, so a clear here decremented the count twice per drained chunk until it
	// went negative and the drain's early-out latched on. dirtyqClear is now idempotent,
	// so a repeat of that mistake costs nothing — but queueing is still the drain's
	// business and this function only meshes.
	// An all-air chunk cannot produce geometry: meshChunk emits faces only for solid cells
	// inside the chunk, and reads the neighbours purely for occlusion. So the 27-chunk
	// scratch fill and the 4,096-cell mesher walk are both pure waste here, and skipping
	// them is exact rather than an approximation. This became worth doing the moment a
	// dug-out chunk started keeping its slot: those chunks are now queued and remeshed
	// like any other, and every one of them was paying ~335 us to produce nothing. A chunk
	// with no storage at all is air by definition and takes the same path.
	const Chunk* chunk = worldChunk(w, cx, cy, cz);
	if (!chunk || chunkIsAllAir(chunk)) {
		// Zero vertices needed, so any slot this chunk already owns fits trivially — reuse
		// it in place, same as before. Only a brand-new chunk asks acquireSlot for
		// anything, and it always lands in the smallest tier (0 <= TIER_S_FACES*4).
		MeshSlot* s = existing ? existing : acquireSlot(0, NULL);
		if (!s) {
			s_refusals++;
			return false;
		}
		s->cx = cx; s->cy = cy; s->cz = cz;
		s->vert_count = s->index_count = s->opaque_index_count = 0;
		memset(s->face_start, 0, sizeof(s->face_start));
		s->used = true;
		cullInvalidate();

		// Nothing to draw, but sight still has to get through it — an all-air chunk joins
		// every pair of its faces. Skipping the flood fill here is exact, not an
		// approximation, and it matters: these are the chunks a player digs out and they
		// are re-meshed on every edit.
		s->vis_mask = VIS_ALL_CONNECTED;
		return true;
	}

	// Step 7.3, computed here and not per frame: it is a flood fill over 4,096 cells, and it
	// can only change when the chunk's blocks change — which is exactly when this runs.
	// Timed separately rather than folded into the scratch or mesh bucket, because it is new
	// cost added to a path that already has a measured budget, and a number that hides inside
	// another number cannot be argued with later.
	const u64 tv = svcGetSystemTick();
	const uint16_t vis_mask = visChunkConnectivity(chunk, &s_vis_scratch);
	s_vis_ticks += svcGetSystemTick() - tv;

	const u64 t0 = svcGetSystemTick();
	scratchFill(&s_scratch, w, cx, cy, cz);
	// v1.5.0: the light band alongside the blocks, only when the engine is on.
	// The mesher reads s_scratch.light behind the same gate, so when this is
	// skipped the band is never looked at and pad comes out zero as always.
	if (lightEnabled())
		scratchFillLight(&s_scratch, w, cx, cy, cz);
	const u64 t1 = svcGetSystemTick();

	// Step 9.2c. Meshed into s_vert_scratch, not a slot's own buffer any more: which slot
	// this chunk belongs in depends on out.vert_count, which does not exist until meshChunk
	// has already run — so there is no slot to mesh into yet. The index buffer is still NOT
	// the slot's — s_index_scratch is a write-only landing pad meshChunk fills and this
	// function throws away; see the comment on s_index_scratch for why that is exact, not a
	// shortcut. vert_cap stays MESH_SLOT_VERTS, meshChunk's own absolute cap — unchanged
	// from before this step, so a pathological chunk overflows exactly as it always did.
	MeshOut out = {0};
	out.verts     = s_vert_scratch;
	out.indices   = s_index_scratch;
	out.vert_cap  = MESH_SLOT_VERTS;
	out.index_cap = MESH_SLOT_INDICES;
	meshChunk(&out, &s_scratch);

	s_scratch_ticks += t1 - t0;
	s_mesh_ticks    += svcGetSystemTick() - t1;
	s_build_count++;

	if (out.overflow) {
		s_refusals++;
		// Matches what the flat pool always did here: an overflowing remesh must not go on
		// showing a chunk that no longer matches its own blocks, so a slot this chunk
		// already owned is blanked rather than left showing stale geometry. A chunk that
		// never had a slot simply continues not to have one — there is nothing to blank.
		if (existing) {
			existing->used = false;
			existing->vert_count = existing->index_count = existing->opaque_index_count = 0;
			memset(existing->face_start, 0, sizeof(existing->face_start));
			cullInvalidate();
		}
		return false;
	}

	// The common case: the chunk already has a slot and it is still big enough (an edit
	// that removed geometry, or added only a little, never crosses a tier boundary) — reuse
	// it in place, no different from the flat pool's "recycle in place: no allocation, no
	// free". Only a chunk that is brand new, or has just outgrown its tier, calls
	// acquireSlot at all.
	MeshSlot* s;
	if (existing && existing->vert_cap >= out.vert_count) {
		s = existing;
	} else {
		s = acquireSlot(out.vert_count, existing);
		if (!s) {
			// Pool full even after trying every tier from the smallest that fits upward.
			// `existing`, if this chunk had a slot, is left exactly as it was — it keeps
			// showing its last successfully built mesh instead of a hole, the same
			// principle the overflow branch above uses for the same reason.
			s_refusals++;
			return false;
		}
		if (existing) {
			existing->used = false;
			existing->vert_count = existing->index_count = existing->opaque_index_count = 0;
			memset(existing->face_start, 0, sizeof(existing->face_start));
		}
	}

	// Payload first, metadata second. The counts below are what chunkRenderDraw turns into a
	// draw call, so publishing them before the vertices they describe have landed would, for
	// the window between the two, advertise a mesh whose bytes are still the previous
	// occupant's. Today both halves run on the main thread with no draw between them, so this
	// ordering is not load-bearing — it is written this way so it stays correct if that ever
	// stops being true, and so it cannot be mistaken for the real race, which was one level up
	// in main.c's frame loop (see gpuWaitPrevFrame there).
	//
	// Only the vertices actually used, not the whole tier's capacity — copying vert_cap
	// bytes every remesh would put back exactly the waste this step exists to remove.
	if (out.vert_count) {
		memcpy(s->verts, s_vert_scratch, (size_t)out.vert_count * sizeof(MeshVertex));

		// This memcpy goes through the ARM11's data cache; the GPU is a separate bus master
		// and reads physical RAM. Without this flush the GPU can be handed a pointer to a mesh
		// that, as far as RAM is concerned, has not been written yet.
		//
		// Read the history here carefully, because it was got wrong once. v1.2.0 added this
		// flush — the codebase had none — on the theory that a stale read was THE freeze. It
		// was not: steve booted v1.2.0 on his own console and it froze exactly as before, in
		// single player and in multiplayer. The missing flush was a real defect on hardware
		// that has no coherency between the CPU cache and the GPU's bus, and it stays for that
		// reason alone. It was never the cause. The cause was the frame loop overwriting these
		// same buffers while the previous frame's draw was still fetching from them, which
		// v1.2.1 fixes in main.c. If anything, flushing sooner made that race land harder.
		GSPGPU_FlushDataCache(s->verts, (size_t)out.vert_count * sizeof(MeshVertex));
	}

	s->cx = cx; s->cy = cy; s->cz = cz;
	s->vert_count  = out.vert_count;
	s->index_count = out.index_count;
	s->opaque_index_count = out.opaque_index_count;
	memcpy(s->face_start, out.face_start, sizeof(s->face_start));
	s->vis_mask = vis_mask;
	cullInvalidate();

	// Claimed even when the chunk meshed to nothing. This used to be `out.faces > 0` — an
	// all-air chunk handed its slot straight back — and that was a bug you could reach by
	// playing: chunkRenderTouch only queues chunks that already own a slot, so a chunk dug
	// out to nothing became permanently unqueueable, and a block placed back into it would
	// exist in the World and never be drawn. The buffer is not wasted — acquireSlot takes
	// an empty slot ahead of refusing, so the memory is still recoverable under pressure;
	// it is only reserved while nothing else needs it, and since 9.2c a dug-out chunk's
	// empty slot is the smallest tier rather than always the largest.
	s->used = true;

	return true;
}

int chunkRenderReleaseColumn(int cx, int cz)
{
	int released = 0;
	for (int i = 0; i < MESH_SLOTS; i++) {
		MeshSlot* s = &s_slots[i];
		if (!s->used || s->cx != cx || s->cz != cz) continue;

		// The dirty flag goes with the slot. A flag left set on a released slot would send
		// the next drain to chunkRenderBuild with this slot's stale coordinates, which is
		// exactly the "meshes a chunk that is no longer in the world" case above — and it
		// would also consume the drain's budget doing it.
		dirtyqClear(&s_dirty, i);

		s->used = false;
		s->vert_count = s->index_count = s->opaque_index_count = 0;
		memset(s->face_start, 0, sizeof(s->face_start));
		released++;
	}

	// Slots left the pool, so the sight walk's box and the visible list are both describing a
	// world that no longer exists.
	if (released) cullInvalidate();
	return released;
}

int chunkRenderTouch(const World* w, int x, int y, int z)
{
	// w is not needed to queue a chunk — only to mesh one — but the signature is kept
	// as-is so callers do not have to special-case this from chunkRenderBuild, and so
	// the world reference is already in hand on the day this needs to inspect block
	// state (e.g. to prioritise the queue) rather than just chunk coordinates.
	(void)w;

	ChunkCoord list[REMESH_MAX];
	const int n = remeshList(x, y, z, list);

	int queued = 0;
	for (int i = 0; i < n; i++) {
		// Only chunks that already have a mesh. A chunk with no slot is not on screen,
		// so meshing it here would be inventing a streaming policy — that is Phase 5,
		// and doing it early would also let one edit eat the pool.
		for (int k = 0; k < MESH_SLOTS; k++) {
			MeshSlot* s = &s_slots[k];
			if (!s->used || s->cx != list[i].cx || s->cy != list[i].cy || s->cz != list[i].cz)
				continue;

			if (dirtyqMark(&s_dirty, k))
				queued++;
			break;   // slots are one-to-one with chunk coordinates; nothing else can match
		}
	}
	return queued;
}

int chunkRenderDrainDirty(const World* w, float budget_ms, int max_chunks)
{
	// <= 0 rather than == 0. The count cannot go negative now that dirtyqClear owns it,
	// but an exact-equality early-out is what turned last night's miscount from a wrong
	// number into a world that stopped updating: at -3 the drain still ran, and the
	// moment three fresh edits brought it to exactly 0 it latched off for good.
	if (dirtyqCount(&s_dirty) <= 0) return 0;

	const u64  t0 = svcGetSystemTick();
	const float ticks_per_ms = (float)(SYSCLOCK_ARM11 / 1000);
	// A non-positive budget is clamped to zero rather than left negative, so the tick
	// comparison below behaves the same way "no time left" always does: the loop still
	// completes its first (guaranteed) chunk and then stops, instead of doing something
	// undefined with a negative tick count.
	const u64 budget_ticks = (budget_ms > 0.0f) ? (u64)(budget_ms * ticks_per_ms) : 0;

	int completed = 0;
	for (int i = 0; i < MESH_SLOTS; i++) {
		MeshSlot* s = &s_slots[i];
		if (!dirtyqIsMarked(&s_dirty, i)) continue;

		// chunkRenderBuild may decide the chunk is now all-air and hand the slot back
		// (s->used = false); either way the chunk this entry named has been dealt
		// with, so the dirty flag clears regardless of the outcome.
		chunkRenderBuild(w, s->cx, s->cy, s->cz);
		dirtyqClear(&s_dirty, i);
		completed++;

		// Checked after the rebuild, never before: a budget that is already spent (or
		// was zero/negative to begin with) must still let the chunk above complete, or
		// the queue would never drain and the world would visibly stop updating. Every
		// subsequent chunk in this call is genuinely optional against the budget.
		const u64 elapsed = svcGetSystemTick() - t0;
		if (elapsed >= budget_ticks) break;

		// The count cap, checked in the same place and for the same reason. A clock can
		// only stop the loop once a chunk has already overrun; the count stops it before
		// the *next* one starts, which is what makes the worst case a number that can be
		// written down (max_chunks x ~2.1 ms) rather than one that depends on how long a
		// chunk happened to take.
		if (completed >= max_chunks) break;

		if (dirtyqCount(&s_dirty) <= 0) break;
	}
	return completed;
}

int chunkRenderDirtyCount(void) { return dirtyqCount(&s_dirty); }
int chunkRenderDirtyPeak(void)  { return dirtyqPeak(&s_dirty); }

void chunkRenderDirtyResetPeak(void) { dirtyqResetPeak(&s_dirty); }

// The camera, recovered from the view matrix rather than passed in. cameraView builds it as
// rotations then a translation, so it is rigid: V = [R | -R*c], and c = -R^T * t. That keeps
// chunkRenderDraw's signature honest — one matrix in, and no second copy of the camera that
// could drift out of step with the one the vertices are transformed by.
//
// Hoisted out of caveWalk in step 9.2, because the face-bucket mask needs the camera position
// too and it must be right even in a -DBS_CAVECULL=0 build, where the walk never runs.
static void cameraFromView(const C3D_Mtx* view)
{
	const C3D_FVec* r0 = &view->r[0];
	const C3D_FVec* r1 = &view->r[1];
	const C3D_FVec* r2 = &view->r[2];

	s_cam_x = -(r0->x * r0->w + r1->x * r1->w + r2->x * r2->w);
	s_cam_y = -(r0->y * r0->w + r1->y * r1->w + r2->y * r2->w);
	s_cam_z = -(r0->z * r0->w + r1->z * r1->w + r2->z * r2->w);
}

// Which chunk a world coordinate falls in. floorf and not a cast: a cast truncates towards
// zero, so everything in the first chunk west of the origin would answer 0 along with the
// chunk east of it, and the walk cache would then miss a chunk boundary crossing exactly
// where the world is most likely to be wrong.
static int chunkOfFloat(float v)
{
	return (int)floorf(v / (float)CHUNK_DIM);
}

#if BS_CAVECULL
// Step 7.3, once per frame: box up every live slot, then walk sight outward from the camera.
// Sets s_cave_ran, which is what the draw loop consults — a walk that could not run must let
// everything through, because "the box was too big" is a missing optimisation and skipping
// chunks anyway would be a hole in the world.
static void caveWalk(void)
{
	// Step 9.3. The walk's answer is a function of the camera's *chunk* and the pool's
	// contents, and nothing else — not the camera's position inside that chunk, and not where
	// it is looking. So while the player stays in one chunk the previous frame's result is
	// exactly the result this frame would compute, and at walking pace that is most frames.
	// Anything that changes the pool clears s_walk_valid (see cullInvalidate), so the only
	// thing left to check here is the boundary crossing.
	const int cam_cx = chunkOfFloat(s_cam_x);
	const int cam_cy = chunkOfFloat(s_cam_y);
	const int cam_cz = chunkOfFloat(s_cam_z);

	if (s_walk_valid && cam_cx == s_walk_cx && cam_cy == s_walk_cy && cam_cz == s_walk_cz) {
		s_cave_ran = true;   // the cached walk is still the answer, so the cull may use it
		return;
	}

	// Dropped before anything can fail. Every path out of here from this point on is either a
	// completed walk, which sets it back at the end, or a refusal — and a refusal must not
	// leave a stale walk looking valid.
	s_walk_valid = false;

	int min_x = 0, min_y = 0, min_z = 0;
	int max_x = 0, max_y = 0, max_z = 0;
	bool any = false;

	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used) continue;
		if (!any) {
			min_x = max_x = s->cx; min_y = max_y = s->cy; min_z = max_z = s->cz;
			any = true;
			continue;
		}
		if (s->cx < min_x) min_x = s->cx;
		if (s->cx > max_x) max_x = s->cx;
		if (s->cy < min_y) min_y = s->cy;
		if (s->cy > max_y) max_y = s->cy;
		if (s->cz < min_z) min_z = s->cz;
		if (s->cz > max_z) max_z = s->cz;
	}
	if (!any) return;

	if (!visWalkBegin(&s_walk, min_x, min_y, min_z,
	                  max_x - min_x + 1, max_y - min_y + 1, max_z - min_z + 1))
		return;

	// Every claimed slot, including the ones that meshed to nothing: a chunk the player has
	// dug out draws no triangles but still has to let sight through, and leaving it out would
	// make it a hole in the box — which reads as open sky, so in this direction the mistake
	// would be harmless. Putting it in is still right, because its real connectivity is what
	// the walk should use the day step 7.5 gives an "empty" chunk water in it.
	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used) continue;
		visWalkSet(&s_walk, s->cx, s->cy, s->cz, s->vis_mask, s->index_count != 0);
	}

	visWalkRun(&s_walk, s_cam_x, s_cam_y, s_cam_z);
	s_cave_ran = true;
	s_walk_runs++;

	// Only now, after a walk that actually completed. An early return above — the box did not
	// fit, or there is nothing loaded — must leave the cache invalid, or the next frame would
	// reuse a walk that was never run and cull against whatever the last successful one said.
	s_walk_valid = true;
	s_walk_cx = cam_cx; s_walk_cy = cam_cy; s_walk_cz = cam_cz;
}
#endif

#if BS_HORIZON
#define HZN_PI  3.14159265f

// Step 9.1e, half of 9.1a's effect read back out: 9.1a never allocates a chunk above a
// column's real terrain, so the highest *meshed, non-empty* slot in a column already IS that
// column's silhouette height, at chunk resolution, for free — no second heightmap, no call
// into worldgen's noise. `index_count == 0` slots (a dug-out chunk that kept its slot, see
// chunkRenderBuild) are skipped: they draw nothing, so they cast nothing.
//
// Built once per cullFrame from the live pool, same rate as caveWalk's box — cheap because the
// candidate set this step matters to is the same handful of columns the render distance
// setting already caps at 25 (RENDER_DIST_MAX_COLUMNS).
static void horizonBuild(void)
{
	s_hzn_n = 0;
	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used || s->index_count == 0) continue;

		const float top = (float)((s->cy + 1) * CHUNK_DIM);

		int found = -1;
		for (int c = 0; c < s_hzn_n; c++) {
			if (s_hzn_cols[c].cx == s->cx && s_hzn_cols[c].cz == s->cz) { found = c; break; }
		}
		if (found >= 0) {
			if (top > s_hzn_cols[found].top_y) s_hzn_cols[found].top_y = top;
		} else if (s_hzn_n < HZN_MAX_COLUMNS) {
			s_hzn_cols[s_hzn_n].cx = s->cx;
			s_hzn_cols[s_hzn_n].cz = s->cz;
			s_hzn_cols[s_hzn_n].top_y = top;
			s_hzn_n++;
		}
		// A column past HZN_MAX_COLUMNS is silently dropped from the blocker set — see the
		// comment on HZN_MAX_COLUMNS for why that is the safe direction and not a bug.
	}
}

// True only when chunk (cx,cy,cz)'s entire box sits below a nearer column's silhouette, as
// seen from the camera. Two tests, both conservative on purpose:
//
//   1. Bearing alignment: the blocking column N must actually sit in front of the candidate,
//      not merely closer to the camera in some unrelated direction. `half_w` is N's angular
//      half-width shrunk to 35% of its true 8-block half-extent (CHUNK_DIM * 0.5), so a
//      near-miss reads as "not aligned" rather than "aligned" — the failure direction that
//      matches every other cull in this file: this may keep a chunk it did not have to, it
//      must never drop one that could be seen past N's actual silhouette.
//   2. Elevation: N's top must subtend an angle at least as large as the candidate chunk's OWN
//      top, i.e. even the highest point of the candidate cannot clear N's roofline.
static bool horizonHidden(int cx, int cy, int cz)
{
	const float col_x = (float)(cx * CHUNK_DIM) + (float)CHUNK_DIM * 0.5f;
	const float col_z = (float)(cz * CHUNK_DIM) + (float)CHUNK_DIM * 0.5f;
	const float dx     = col_x - s_cam_x, dz = col_z - s_cam_z;
	const float dist   = sqrtf(dx * dx + dz * dz);

	// The camera's own column, or anything closer than a chunk's half-width, cannot be
	// meaningfully "behind" anything else the loop will find — and dividing by a near-zero
	// distance below would otherwise hand back a degenerate bearing.
	if (dist < (float)CHUNK_DIM * 0.5f) return false;

	const float bearing = atan2f(dz, dx);
	const float top_y   = (float)((cy + 1) * CHUNK_DIM);
	const float elev    = atan2f(top_y - s_cam_y, dist);

	for (int c = 0; c < s_hzn_n; c++) {
		if (s_hzn_cols[c].cx == cx && s_hzn_cols[c].cz == cz) continue;   // never self-block

		const float ncx = (float)(s_hzn_cols[c].cx * CHUNK_DIM) + (float)CHUNK_DIM * 0.5f;
		const float ncz = (float)(s_hzn_cols[c].cz * CHUNK_DIM) + (float)CHUNK_DIM * 0.5f;
		const float ndx = ncx - s_cam_x, ndz = ncz - s_cam_z;
		const float ndist = sqrtf(ndx * ndx + ndz * ndz);

		// Must be genuinely nearer, with a full block of margin against two columns at
		// essentially the same distance flickering across the cull from one frame to the next.
		if (ndist >= dist - 1.0f) continue;

		float dbear = atan2f(ndz, ndx) - bearing;
		while (dbear >  HZN_PI) dbear -= 2.0f * HZN_PI;
		while (dbear < -HZN_PI) dbear += 2.0f * HZN_PI;

		const float half_w = atan2f((float)CHUNK_DIM * 0.5f * 0.35f, ndist);
		if (fabsf(dbear) > half_w) continue;

		const float nelev = atan2f(s_hzn_cols[c].top_y - s_cam_y, ndist);
		if (nelev >= elev) return true;
	}
	return false;
}
#endif

#if BS_DRAW_GUARD
// Which slot slotBind last pointed the GPU at. drawIndices needs it to know how many vertices
// the bound buffer actually holds, and the two are deliberately separate calls (a chunk is up
// to three opaque runs plus a transparent one, all sharing one bind).
static const MeshSlot* s_bound;
#endif

// Points the GPU at one chunk: the model matrix that places its chunk-local 0..16 vertices in
// the world, and its vertex buffer. Split out from the draw in step 9.2, because a chunk is
// now up to three opaque runs plus a transparent one and all four share this — setting a
// matrix per run would hand back a good part of what the buckets save.
static void slotBind(const C3D_Mtx* view, const MeshSlot* s)
{
	C3D_Mtx model, mv;
	Mtx_Identity(&model);
	Mtx_Translate(&model, (float)(s->cx * CHUNK_DIM), (float)(s->cy * CHUNK_DIM),
	              (float)(s->cz * CHUNK_DIM), true);
	Mtx_Multiply(&mv, view, &model);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, &mv);

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s->verts, sizeof(MeshVertex), 2, 0x10);
#if BS_DRAW_GUARD
	s_bound = s;
#endif
}

#if BS_DRAW_GUARD
// The first draw that failed validation, kept verbatim so the report is evidence rather than a
// summary. Written once and then left alone: the interesting one is the first, and a console
// that is about to hang has no time to keep a history.
static int      s_guard_code;       // 0 = nothing wrong has been seen
static uint32_t s_guard_first, s_guard_count, s_guard_maxidx, s_guard_cap;
static int      s_guard_slot, s_guard_hits;
static uintptr_t s_guard_verts;

int  chunkRenderGuardCode(void)   { return s_guard_code; }
int  chunkRenderGuardHits(void)   { return s_guard_hits; }
int  chunkRenderGuardSlot(void)   { return s_guard_slot; }
uint32_t chunkRenderGuardFirst(void)  { return s_guard_first; }
uint32_t chunkRenderGuardCount(void)  { return s_guard_count; }
uint32_t chunkRenderGuardMaxIdx(void) { return s_guard_maxidx; }
uint32_t chunkRenderGuardCap(void)    { return s_guard_cap; }
uintptr_t chunkRenderGuardVerts(void) { return s_guard_verts; }

// How many vertices the buffer bound for slot `s` actually holds, or 0 if that pointer is not
// the start of a slot in any tier arena. Derived from the pointer rather than trusted from the
// slot, because "the slot says one thing and the GPU was handed another" is precisely the
// failure being hunted.
static uint32_t boundVertCap(const MeshSlot* s)
{
	if (!s || !s->verts) return 0;
	for (int t = 0; t < 3; t++) {
		if (!s_tier_arena[t]) continue;
		const uint32_t cap   = (uint32_t)kTierFaces[t] * 4;
		const MeshVertex* lo = s_tier_arena[t];
		const MeshVertex* hi = lo + (size_t)cap * (size_t)kTierSlots[t];
		if (s->verts < lo || s->verts >= hi) continue;
		// Must be the *start* of a slot, not somewhere in the middle of one.
		if ((size_t)(s->verts - lo) % cap) return 0;
		return cap;
	}
	return 0;
}

// Everything that has to be true for one C3D_DrawElements to be safe to issue. hang.txt proved
// the CPU finishes the frame and the GPU then never signals, which is what a vertex fetch from
// an address the GPU cannot read looks like from outside — so these are the four ways this
// code could hand the GPU such an address.
//
// The last check is the one worth the trouble. Every slot in a tier holds exactly
// kTierFaces[t]*4 vertices, but the index buffer is shared by every tier and runs to the
// largest, so a run whose indices reach past its own tier's slot reads into the next slot —
// and off the end of the arena entirely if the slot is the last one in it.
static bool drawSane(uint32_t first, uint32_t count)
{
	const uint32_t cap = boundVertCap(s_bound);
	int code = 0;
	uint32_t maxidx = 0;

	if (!cap)                                     code = 1;   // verts NULL / not a slot start
	else if (count % 3u)                          code = 2;   // not whole triangles
	else if (first + count > MESH_SLOT_INDICES)   code = 3;   // runs off the index buffer
	else {
		maxidx = s_shared_indices[first + count - 1u];
		if ((uint32_t)maxidx >= cap)              code = 4;   // reaches past the bound slot
	}

	if (!code) return true;

	s_guard_hits++;
	if (!s_guard_code) {
		s_guard_code   = code;
		s_guard_first  = first;
		s_guard_count  = count;
		s_guard_maxidx = maxidx;
		s_guard_cap    = cap;
		s_guard_slot   = s_bound ? (int)(s_bound - s_slots) : -1;
		s_guard_verts  = (uintptr_t)(s_bound ? s_bound->verts : NULL);
	}
	return false;
}
#endif

// One run out of the shared index buffer. `first` and `count` still come from the bound
// slot's own face_start / opaque_index_count / index_count — only the storage they index
// into is shared now, see s_shared_indices.
static void drawIndices(uint32_t first, uint32_t count)
{
	if (!count) return;
#if BS_DRAW_GUARD_REDTEST
	// The red arm for the guard, and nothing else uses it. A checker that has only ever been
	// seen agreeing with the code it checks has not been tested — so this hands it one draw
	// that is genuinely wrong, on the 300th chunk draw of the session so the frames before it
	// stay a live control that must still come back clean.
	//
	//   =3  a run that ends past the end of the shared index buffer
	//   =4  a run whose indices reach past the vertex buffer bound for it
	{
		static int seen = 0;
		if (++seen == 300) {
#if BS_DRAW_GUARD_REDTEST == 3
			first = MESH_SLOT_INDICES - 3u; count = 6u;
#else
			first = 0u; count = MESH_SLOT_INDICES;
#endif
		}
	}
#endif
#if BS_DRAW_GUARD
	if (!drawSane(first, count)) return;
#endif
	C3D_DrawElements(GPU_TRIANGLES, (int)count, C3D_UNSIGNED_SHORT, s_shared_indices + first);
	metricsCountDraw(count / 3);
}

// Step 7.5 pass 2 and step 4.2's neighbours still want the old one-call shape.
static void drawRun(const C3D_Mtx* view, const MeshSlot* s, uint32_t first, uint32_t count)
{
	if (!count) return;
	slotBind(view, s);
	drawIndices(first, count);
}

// Step 9.2. The opaque half of one chunk, minus the face directions that cannot be looking at
// the camera.
//
// The test is the chunk's own slab, one axis at a time. Every +X face in the chunk sits on a
// plane x = bx+1 .. bx+16, and such a face is front-facing only if the camera is on the larger
// side of its plane — so if cam_x <= bx, not one of them can be, and the whole bucket goes. The
// same argument mirrored gives the other five. A camera inside the chunk passes both tests on
// that axis and gets both buckets, which is right: standing in a hollow you can see walls
// facing either way.
//
// This is the same thing the GPU's backface cull does, one frame stage earlier. The GPU's
// version is exact and this one is conservative, but the GPU only reaches it after the vertex
// shader has transformed the vertex — and the vertex stage is the narrow one on a PICA200.
// Roughly half of a chunk's opaque vertices never leave the index buffer now.
static void drawOpaque(const C3D_Mtx* view, const MeshSlot* s)
{
	if (!s->opaque_index_count) return;
	slotBind(view, s);

#if BS_FACEMASK
	const float bx = (float)(s->cx * CHUNK_DIM);
	const float by = (float)(s->cy * CHUNK_DIM);
	const float bz = (float)(s->cz * CHUNK_DIM);
	const float e  = (float)CHUNK_DIM;

	bool want[BLOCK_FACES];
	want[FACE_EAST]   = s_cam_x >  bx;
	want[FACE_WEST]   = s_cam_x <  bx + e;
	want[FACE_TOP]    = s_cam_y >  by;
	want[FACE_BOTTOM] = s_cam_y <  by + e;
	want[FACE_SOUTH]  = s_cam_z >  bz;
	want[FACE_NORTH]  = s_cam_z <  bz + e;

	// Buckets that survive next to each other in the index buffer go out as one call. Which
	// ones are neighbours is the mesher's kFaceOrder, not the enum order, and that ordering is
	// chosen so this loop merges as often as it can: no two adjacent buckets are opposite faces
	// of one axis, and opposite faces are exactly the pair that never both survive from outside
	// the chunk. Three surviving directions therefore average 1.75 draws instead of 2.5.
	// Merging costs a loop and saves command-buffer space, which is a fixed 0x40000 bytes a
	// frame on this hardware and something step 7 has already had to watch.
	int f = 0;
	while (f < BLOCK_FACES) {
		if (!want[kFaceOrder[f]]) { f++; continue; }
		int g = f;
		while (g + 1 < BLOCK_FACES && want[kFaceOrder[g + 1]]) g++;
		drawIndices(s->face_start[f], s->face_start[g + 1] - s->face_start[f]);
		f = g + 1;
	}
#else
	drawIndices(0, s->opaque_index_count);
#endif
}

// Step 9.3. Everything that decides *what* to draw, hoisted out of the draw so a 3D frame pays
// for it once instead of once per eye. Frustum, sight walk, and the front-to-back sort are all
// functions of the camera and the pool, and citro3d puts the eye offset in the projection —
// both eyes are handed the same view matrix — so there was never a second answer to compute.
//
// The frustum comes from the *mono* projection, widened by the eye offset when the boxes are
// tested, so the one list is a superset of what either eye can see.
static void cullFrame(const C3D_Mtx* view)
{
	s_cull_runs++;
	s_culled = 0;
	s_cave_culled = 0;
	s_cave_ran = false;
	s_horizon_culled = 0;

	cameraFromView(view);

	// Step 7.1. Built from the mono projection and the view the draw uses, in the same order,
	// so the cull and the rasteriser cannot disagree about where the screen edge is.
	Frustum frustum;
	C3D_Mtx vp;
	Mtx_Multiply(&vp, &s_mono_projection, view);
	frustumFromMatrix(&frustum, &vp);

#if BS_CAVECULL
	caveWalk();
#endif

#if BS_HORIZON
	// Step 9.1e, at the same rate as caveWalk: a function of the pool's contents and the
	// camera position, so it is rebuilt every cull rather than cached against a chunk
	// boundary the way the sight walk is — the column table is a handful of entries and a
	// single pass over MESH_SLOTS, nowhere near what the walk's box justifies caching for.
	horizonBuild();
#endif

	// The slack that makes one frustum answer for two eyes. Mtx_PerspStereoTilt moves the
	// apex sideways by iod and re-aims at the focal plane, which translates the view volume
	// and does not reshape it — so a box grown by the largest offset in every axis is a
	// superset of both eyes' volumes. 0.2 blocks against a 16-block chunk: in 2D it keeps a
	// handful of chunks a hair past the edge that the old per-eye test would have dropped,
	// which costs a draw of geometry that is about to scroll on screen anyway.
	const float slack = STEREO_MAX_IOD;

	s_vis_n = 0;

	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used || s->index_count == 0) continue;

		// The chunk's world-space box. Exactly CHUNK_DIM on a side: the mesher never emits
		// a vertex outside the chunk it was asked for, so the only skin here is the eye
		// offset above, and adding any more "to be safe" would keep chunks that are
		// genuinely off-screen.
		const float bx = (float)(s->cx * CHUNK_DIM);
		const float by = (float)(s->cy * CHUNK_DIM);
		const float bz = (float)(s->cz * CHUNK_DIM);

#if BS_FRUSTUM
		if (!frustumTestAABB(&frustum, bx - slack, by - slack, bz - slack,
		                     bx + (float)CHUNK_DIM + slack,
		                     by + (float)CHUNK_DIM + slack,
		                     bz + (float)CHUNK_DIM + slack)) {
			s_culled++;
			continue;
		}
#endif

#if BS_CAVECULL
		// Step 7.3. After the frustum, not before: the frustum test is four multiplies and
		// this is an array lookup, so the order barely matters for cost — but counting them
		// separately only means anything if each number is "what this test rejected that the
		// previous one had kept".
		if (s_cave_ran && !visWalkVisible(&s_walk, s->cx, s->cy, s->cz)) {
			s_cave_culled++;
			continue;
		}
#endif

#if BS_HORIZON
		// Step 9.1e. After frustum and cave, same reasoning as their own ordering comments:
		// counted last so its number is "what this test rejected that the other two had
		// kept", not an overlapping claim.
		if (horizonHidden(s->cx, s->cy, s->cz)) {
			s_horizon_culled++;
			continue;
		}
#endif

		// Step 7.2's sort key: the chunk centre's clip-space w, which for this projection
		// is exactly its distance in front of the camera. Row 3 of the same view-projection
		// the frustum came from, so there is no second copy of the camera to keep in step —
		// one dot product, no square root, no camera position threaded through the API.
		// Row 3 is untouched by the eye offset, so the mono matrix gives the same order the
		// per-eye ones would.
		const float h = (float)CHUNK_DIM * 0.5f;
		s_vis_depth[s_vis_n] = vp.r[3].x * (bx + h) + vp.r[3].y * (by + h) +
		                       vp.r[3].z * (bz + h) + vp.r[3].w;
		s_vis_list[s_vis_n] = i;
		s_vis_n++;
	}

	const int n = s_vis_n;

#if BS_SORT
	// Insertion sort, nearest first. Insertion rather than anything cleverer because n is at
	// most MESH_SLOTS (392) and in practice a bit over a hundred after the frustum has run,
	// and because the order barely changes between frames — a nearly-sorted input is the case
	// insertion sort is linear on, which is exactly what walking through a world produces.
	for (int i = 1; i < n; i++) {
		const float d = s_vis_depth[i];
		const int   v = s_vis_list[i];
		int j = i - 1;
		while (j >= 0 && s_vis_depth[j] > d) {
			s_vis_depth[j + 1] = s_vis_depth[j];
			s_vis_list[j + 1]  = s_vis_list[j];
			j--;
		}
		s_vis_depth[j + 1] = d;
		s_vis_list[j + 1]  = v;
	}
#endif

	// Proof that the order is what it claims to be, cheap enough to leave in: how many
	// chunks the sort actually moved out of slot order, and whether the emitted sequence is
	// really non-decreasing in depth. Without the first number, "the sort works" and "the
	// sort is a no-op" look identical on screen — the frame is meant to be unchanged either
	// way, since this is opaque geometry behind a depth test.
	s_sort_moved = 0;
	s_sort_ok    = true;
	for (int k = 0; k < n; k++) {
		if (k > 0 && s_vis_depth[k] < s_vis_depth[k - 1]) s_sort_ok = false;
		if (k > 0 && s_vis_list[k] < s_vis_list[k - 1]) s_sort_moved++;
	}

	s_cull_view  = *view;
	s_cull_valid = true;
}

void chunkRenderDraw(const C3D_Mtx* view)
{
#if BS_DRAW_PROBE
	// Round 2 of the draw bisect. Round 1 (in main.c) narrowed the hardware freeze to this one
	// call: on a real console every arm froze except the one that skipped chunkRenderDraw
	// entirely. The arms below split what is inside it, and the first question they answer is
	// the one that cannot be answered from outside — whether the console is stuck in the GPU
	// or stuck in the CPU, which look identical from the watchdog's seat because either way
	// the main thread stops beating.
	//
	// arm 1 skips the whole call, which is the surviving control repeated: if this one ever
	// freezes, the bisect itself is wrong and nothing below it means anything.
	// arm 2 runs cullFrame and then leaves without issuing a single GPU command. It is the
	// deciding arm. Freezing here means the CPU is spinning inside the cull (the horizon
	// wrap loops at hznDelta are the standing suspect — they never terminate on a NaN or an
	// infinity). Surviving here means the cull is innocent and the hang is in the draw.
	const int probe_arm = bsProbeArm();
	if (probe_arm == 1) return;

	// The breadcrumb trail. This is the part that does not need a whole round of boots: the
	// watchdog thread prints the last stage reached into hang.txt, so the very first freeze
	// says whether the main thread died on the CPU (CULL) or waiting on the GPU (anything
	// after it), and in a pass, which chunk it was on. The arms above stay as corroboration.
	watchdogDrawStage(WD_DRAW_ENTER, -1, -1);
	watchdogDrawStage(WD_DRAW_CULL, -1, -1);
#endif

	// Step 9.3. Cull, unless this is the second eye of a frame already culled. The key is the
	// view matrix itself: both eyes are handed the same one, so a byte compare answers the
	// question exactly and without the caller having to remember to tick anything. Anything
	// that changes the world rather than the camera clears s_cull_valid directly.
#if BS_CULLCACHE
	if (!s_cull_valid || memcmp(&s_cull_view, view, sizeof(C3D_Mtx)) != 0)
		cullFrame(view);
#else
	cullFrame(view);
#endif

	const int n = s_vis_n;

#if BS_DRAW_PROBE
	// arm 2: all of the CPU work above, not one GPU command below. Returning before
	// pipelineBind is deliberate — binding the shader and writing a uniform are themselves
	// GPU commands, so leaving them in would make this arm no longer a clean CPU-only cut.
	if (probe_arm == 2) return;
	watchdogDrawStage(WD_DRAW_BIND, -1, -1);
#endif

	pipelineBind();   // see pipelineBind: the highlight leaves the GPU set up for itself
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, &s_projection);

	// Step 7.5, pass 1: the opaque run of every visible chunk, nearest first, which is the
	// order step 7.2 just put them in — minus, since step 9.2, the face directions pointing
	// away from the camera.
#if BS_DRAW_PROBE
	// arms 4 and 5 have no opaque pass. arm 4 keeps the transparent one, so it still draws;
	// arm 5 keeps the state setup above and nothing else.
	if (probe_arm != 4 && probe_arm != 5)
#endif
	for (int k = 0; k < n; k++) {
		const MeshSlot* s = &s_slots[s_vis_list[k]];
#if BS_DRAW_PROBE
		watchdogDrawStage(WD_DRAW_OPAQUE, k, s_vis_list[k]);
#if BS_DRAW_HANG_TEST
		// The red arm for the breadcrumb above, in the same spirit as BS_HANG_TEST in main.c:
		// stop the main thread dead in the middle of the opaque pass and see whether hang.txt
		// names the stage and the chunk. A report that says "opaque pass, loop index 3" when
		// the stall was planted at index 3 is a breadcrumb that works; a report that still says
		// DONE is a breadcrumb that was never wired up, and the freeze data would have been
		// meaningless. Never in a release build:
		//   make EXTRA_CFLAGS="-DBS_DRAW_PROBE=1 -DBS_DRAW_HANG_TEST=4"
		// stalls at the (BS_DRAW_HANG_TEST-1)th chunk of the opaque pass, once the world has
		// had 200 frames to settle so the stall lands in the game loop and not the loader.
		{
			static int hang_frames = 0;
			if (k == BS_DRAW_HANG_TEST - 1 && ++hang_frames >= 200)
				for (;;) svcSleepThread(1000000000ULL);
		}
#endif
#endif
		drawOpaque(view, s);
	}

	// Pass 2: the transparent run, farthest first and with the alpha test on.
	//
	// Farthest first, i.e. backwards through the same array, because this pass draws
	// geometry the depth buffer cannot sort for it. With a cutout canopy and depth writes
	// still on, order happens not to matter — a discarded fragment writes nothing and a
	// kept one is fully opaque — but the moment anything here is genuinely translucent it
	// does, and an ordering that is only correct by accident is not one to leave in.
	//
	// GPU_GREATER against 127 rather than "not zero": the atlas is authored with alpha at 0
	// or 255 and nothing between (see tools/make_atlas.py), so the midpoint is the widest
	// possible margin against a filtered sample landing just off the extreme.
	s_alpha_tris = 0;
	s_alpha_draws = 0;
	C3D_AlphaTest(true, GPU_GREATER, ALPHA_CUTOFF);
#if BS_DRAW_PROBE
	// arms 3 and 5 have no transparent pass. Only the loop is cut, not the alpha-test pair
	// around it: those two calls are render state rather than draws, and leaving them in
	// every arm keeps the GPU in the same configuration on the way out no matter which arm
	// ran, so a difference between arms can only be the drawing itself.
	if (probe_arm != 3 && probe_arm != 5)
#endif
	for (int k = n - 1; k >= 0; k--) {
		const MeshSlot* s = &s_slots[s_vis_list[k]];
		const uint32_t  count = s->index_count - s->opaque_index_count;
		if (!count) continue;

#if BS_DRAW_PROBE
		watchdogDrawStage(WD_DRAW_TRANSPARENT, k, s_vis_list[k]);
#endif
		drawRun(view, s, s->opaque_index_count, count);
		s_alpha_tris += count / 3;
		s_alpha_draws++;
	}

	// Left off for whatever draws next. This is global GPU state, not per-program state,
	// and the highlight pass in scene/highlight.c never sets it.
	C3D_AlphaTest(false, GPU_ALWAYS, 0);

#if BS_DRAW_PROBE
	watchdogDrawStage(WD_DRAW_DONE, -1, -1);
#endif
}

int chunkRenderMeshes(void)
{
	// Slots holding geometry, which since the empty-slot fix is no longer the same as
	// slots claimed: a chunk dug out to nothing keeps its slot so it can be re-queued,
	// but it is not a mesh and reporting it as one would make the figure drift upwards
	// every time someone cleared a chunk.
	int n = 0;
	for (int i = 0; i < MESH_SLOTS; i++)
		if (s_slots[i].used && s_slots[i].index_count) n++;
	return n;
}

uint32_t chunkRenderTris(void)
{
	uint32_t t = 0;
	for (int i = 0; i < MESH_SLOTS; i++)
		if (s_slots[i].used) t += s_slots[i].index_count / 3;
	return t;
}

uint32_t chunkRenderChecksum(void)
{
	// XOR-combined per-slot hashes, so the result does not depend on which slot a chunk
	// happens to occupy — only on the geometry actually sitting in the pool. The chunk
	// coordinates are folded in, so two chunks swapping meshes would not cancel out.
	uint32_t total = 0;

	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		// vert_count, not `used`: a claimed slot holding no geometry contributes nothing
		// the GPU ever reads, so folding its coordinates in would change the checksum
		// according to which chunks happen to be empty rather than according to what is
		// drawn — and the whole point of this hash is the second thing.
		if (!s->used || s->vert_count == 0) continue;

		uint32_t h = 2166136261u;
		const int coords[3] = { s->cx, s->cy, s->cz };
		for (int c = 0; c < 3; c++) { h ^= (uint32_t)coords[c]; h *= 16777619u; }

		// Every byte the GPU reads: position, uv, normal index and AO. AO is the reason
		// this exists — a missed neighbour remesh usually loses a shadow without
		// changing a single triangle, so a triangle count cannot see it.
		const uint8_t* bytes = (const uint8_t*)s->verts;
		const uint32_t n = s->vert_count * (uint32_t)sizeof(MeshVertex);
		for (uint32_t b = 0; b < n; b++) { h ^= bytes[b]; h *= 16777619u; }

		total ^= h;
	}
	return total;
}

void chunkRenderProfileReset(void)
{
	s_scratch_ticks = s_mesh_ticks = 0;
	s_build_count = 0;
}

void chunkRenderProfile(float* scratch_us, float* mesh_us, int* builds)
{
	const float per_us = (float)(SYSCLOCK_ARM11 / 1000000);
	const int   n      = s_build_count ? s_build_count : 1;

	if (scratch_us) *scratch_us = (float)s_scratch_ticks / per_us / (float)n;
	if (mesh_us)    *mesh_us    = (float)s_mesh_ticks    / per_us / (float)n;
	if (builds)     *builds     = s_build_count;
}

// Step 9.3's evidence, and the only way to tell the cache from a coincidence. Both are
// cumulative since boot, so the claim they support is a ratio: cull runs against frames drawn
// should be 1:1 in 2D and — the whole point — still 1:1 in 3D, where it was 2:1 before. Sight
// walks against frames should sit far below 1, because the player crosses a chunk boundary
// every sixteen blocks and not every frame.
uint32_t chunkRenderCullRuns(void) { return (uint32_t)s_cull_runs; }
uint32_t chunkRenderWalkRuns(void) { return (uint32_t)s_walk_runs; }

int    chunkRenderCulled(void)     { return s_culled; }
int    chunkRenderSortMoved(void)  { return s_sort_moved; }
bool   chunkRenderSortOk(void)     { return s_sort_ok; }
int    chunkRenderCaveCulled(void) { return s_cave_culled; }
bool   chunkRenderCaveRan(void)    { return s_cave_ran; }
int    chunkRenderHorizonCulled(void) { return s_horizon_culled; }

void chunkRenderCamera(float* x, float* y, float* z)
{
	if (x) *x = s_cam_x;
	if (y) *y = s_cam_y;
	if (z) *z = s_cam_z;
}

float chunkRenderVisUs(void)
{
	const float per_us = (float)(SYSCLOCK_ARM11 / 1000000);
	const int   n      = s_build_count ? s_build_count : 1;
	return (float)s_vis_ticks / per_us / (float)n;
}
int    chunkRenderRefusals(void) { return s_refusals; }
size_t chunkRenderBytes(void)    { return s_bytes; }

// Step 7.5. Triangles and draw calls the alpha-tested pass actually submitted on the last
// chunkRenderDraw. Zero for both means the second pass drew nothing at all, which is a
// different situation from "the canopy is off screen" only in that the first is a bug.
uint32_t chunkRenderAlphaTris(void)  { return s_alpha_tris; }
int      chunkRenderAlphaDraws(void) { return s_alpha_draws; }
