#include "scene/chunk_render.h"

#include <string.h>

#include "debug/metrics.h"
#include "gfx/atlas.h"
#include "world/dirtyq.h"
#include "world/mesher.h"
#include "world/remesh.h"
#include "scene/frustum.h"
#include "world/scratch.h"
#include "world/visgraph.h"
#include "world_shbin.h"   // generated by picasso from source/shaders/world.v.pica

// Step 7.1, overridable so the check can go red: -DBS_FRUSTUM=0 draws every live slot, and
// the two builds must produce a pixel-identical frame or the cull is eating visible geometry.
#ifndef BS_FRUSTUM
#define BS_FRUSTUM 1
#endif

// Step 7.2, same idea: -DBS_SORT=0 draws in slot order. The frame must be identical either
// way — this is opaque geometry behind a depth test — so the thing that has to differ
// between the two builds is chunkRenderSortMoved(), not the pixels.
#ifndef BS_SORT
#define BS_SORT 1
#endif

// Step 7.3, cave culling. -DBS_CAVECULL=0 skips the walk entirely and draws whatever the
// frustum kept. Unlike the two above, this one is not merely an instrumentation switch: the
// frame must still be identical between the two builds, and if it ever is not, this flag is
// how the difference gets bisected without reverting anything.
#ifndef BS_CAVECULL
#define BS_CAVECULL 1
#endif

// Baked per-face brightness, the values Phase 1 proved on the single cube: a high sun
// leaning south-east, no two faces sharing a value, so a wrong normal index shows up as
// an obviously wrong wall instead of a subtle one. Written by name so the face order in
// world/block.h is enforced by the compiler here rather than by a comment.
static const float kFaceShade[BLOCK_FACES] = {
	[FACE_EAST]   = 0.78f,   // +X
	[FACE_WEST]   = 0.66f,   // -X
	[FACE_TOP]    = 1.00f,   // +Y
	[FACE_BOTTOM] = 0.48f,   // -Y
	[FACE_SOUTH]  = 0.86f,   // +Z
	[FACE_NORTH]  = 0.72f,   // -Z
};

typedef struct {
	MeshVertex* verts;
	uint16_t*   indices;

	int      cx, cy, cz;
	uint32_t vert_count;
	uint32_t index_count;
	bool     used;         // owns a chunk (even if that chunk meshed to nothing)

	// Step 7.3. Which of this chunk's six faces sight can pass between, computed once when
	// the chunk is meshed rather than once per frame — it is a flood fill over 4,096 cells
	// and the chunk it describes usually survives for thousands of frames.
	uint16_t vis_mask;
} MeshSlot;

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;
static int             s_uloc_faceshade;

// Clip planes, named rather than written inline because step 6.4's fog LUT has to be built
// with the *same* two numbers the projection uses. FogLut_Exp maps a LUT entry to a view
// distance with far*near/(i/128*(far-near)+near); feed it a different near or far and the
// fog lands at distances the depth buffer never produces.
#define VIEW_NEAR  0.1f
#define VIEW_FAR   200.0f

// Step 6.4. Fog is free on this GPU — a fixed-function stage after the TEV, no fragment
// shader involved, since the PICA200 has not got one — and it is what makes a small mesh
// ring liveable: terrain fades into the sky instead of the load boundary popping in.
//
// The two numbers are chosen against where the hardware can actually *put* a knot, which is
// the whole trick. The fog LUT is 128 entries indexed by 1/w, so entry i sits at view
// distance far*near/(i/128*(far-near)+near) — hyperbolic, and with near 0.1 that is:
//
//   entry 0 -> 200.00 blocks    entry 3 -> 4.18
//   entry 1 ->  12.03           entry 4 -> 3.15
//   entry 2 ->   6.21           entry 8 -> 1.59
//
// Everything between 12 blocks and the far plane is ONE linear segment. So there is no
// point asking for a curve that fades out at, say, 30 blocks: the hardware would draw a
// straight line through it. Instead the curve is set to reach opaque *at entry 1* — density
// 0.1646, gradient 2.44 gives 0.5% visibility at 12.03 blocks — which makes everything from
// 12 blocks outward uniformly sky-coloured, with real knots at 6.2, 4.2, 3.2 and 2.1 doing
// the near ramp. Measured off the curve: 4% fogged at 2.1 blocks, 33% at 4.2, 65% at 6.2.
//
// Matched to render distance, as the step asks: GEN_MESH_RADIUS is 1, so three columns of
// 16 blocks are meshed and the load boundary is never closer than 16 blocks from the player
// (worst case, standing exactly on a column edge). Opaque at 12 is inside that with room to
// spare, so the boundary cannot be seen at any position. When step 7.7 makes render distance
// a setting, these two constants are what moves with it.
//
// Overridable so the check can go red: -DFOG_DENSITY=0.0f makes every LUT entry
// exp(-0) = 1, which is "no fog" through this exact code path rather than a different one.
#ifndef FOG_DENSITY
#define FOG_DENSITY   0.1646f
#endif
#ifndef FOG_GRADIENT
#define FOG_GRADIENT  2.44f
#endif

static C3D_FogLut s_fog_lut;

static C3D_Mtx  s_projection;
static MeshSlot s_slots[MESH_SLOTS];
static int      s_culled;        // chunks the frustum rejected on the last draw
static int      s_sort_moved;    // step 7.2: chunks the sort took out of slot order
static bool     s_sort_ok;       // ...and whether the emitted order really is near-to-far
static int      s_cave_culled;   // step 7.3: chunks no sight line reached
static bool     s_cave_ran;      // ...and whether the walk ran at all this frame
static int      s_refusals;
static size_t   s_bytes;

// Step 7.3's working memory, ~37 KB and ~18 KB. Static for the same reason MeshScratch is:
// the linear heap cannot be defragmented and the main thread's stack is 32 KB, so neither of
// these may be a local or an allocation.
static VisWalk    s_walk;
static VisScratch s_vis_scratch;

// The camera position the walk used, recovered from the view matrix. Reported because that
// recovery is an inversion that is either exactly right or completely wrong, and comparing it
// against the camera main.c already holds is the only way to tell which — a walk started from
// the wrong chunk would still look plausible and cull the wrong half of the world.
static float s_cam_x, s_cam_y, s_cam_z;

// The remesh backlog: one flag per slot in s_slots, parallel by index. A flag per slot
// rather than a list of coordinates, because it makes dedup free and impossible to get
// wrong — touching the same chunk twenty times in one frame sets the same bool twenty
// times, and the queue can never overflow because it cannot hold more entries than there
// are slots. A flag is only ever set while that slot's `used` is also true:
// chunkRenderTouch only queues chunks that already own a slot.
//
// The accounting lives in world/dirtyq.c and not here, which is not tidiness — this file
// includes <3ds.h> and citro3d, so nothing in it can be host-tested, and the count being
// three loose statics in this file is exactly how it shipped a double-decrement that
// silently stopped the world re-meshing. See world/dirtyq.h.
static DirtyQ s_dirty;

// Split profile of a remesh. "A chunk remesh costs 3.7 ms" is not actionable until it
// says which half is spending it: the scratch fill copies from up to 27 chunks, the
// mesher walks 4,096 cells and does the AO reads.
static u64 s_scratch_ticks;
static u64 s_mesh_ticks;
static u64 s_vis_ticks;      // step 7.3's flood fill, the cost this step adds to a remesh
static int s_build_count;

// One scratch for every chunk meshed — 5,832 bytes, reused, never per-chunk.
static MeshScratch s_scratch;

static MeshSlot* slotFor(int cx, int cy, int cz)
{
	MeshSlot* free_slot  = NULL;
	MeshSlot* empty_slot = NULL;   // claimed, but its chunk meshed to nothing

	for (int i = 0; i < MESH_SLOTS; i++) {
		MeshSlot* s = &s_slots[i];
		if (s->used && s->cx == cx && s->cy == cy && s->cz == cz)
			return s;                      // recycle in place: no allocation, no free
		if (!s->used && !free_slot)
			free_slot = s;
		if (s->used && s->index_count == 0 && !empty_slot)
			empty_slot = s;
	}

	// A slot whose chunk holds no geometry is the right thing to take when the pool is
	// otherwise full, and the wrong thing to take before that. Keeping it claimed is what
	// lets chunkRenderTouch find the chunk again after a player digs it out — see the
	// comment on `used` in chunkRenderBuild — but a dug-out chunk must not be allowed to
	// hold 88 KB hostage from a chunk that has something to draw.
	return free_slot ? free_slot : empty_slot;
}

// Everything the world draw needs the GPU to be set to. Called once at init and then
// again at the top of every chunkRenderDraw, deliberately, rather than being left
// standing from init: step 4.2's highlight binds its own shader program and its own
// vertex format, and on the PICA200 the vertex shader's float uniform bank is shared
// hardware — a second program's uniforms land in the same registers and quietly
// overwrite faceShade. Re-establishing state per frame costs a handful of register
// writes and makes "who broke the lighting" a question that cannot be asked.
static void pipelineBind(void)
{
	C3D_BindProgram(&s_program);

	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_BYTE, 3);            // v0 = position
	AttrInfo_AddLoader(attr, 1, GPU_UNSIGNED_BYTE, 4);   // v1 = u, v, normal, ao

	// No fragment shader: TEV stage 0 multiplies the atlas sample by the vertex
	// colour, which is where the baked face shade and AO land.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

	C3D_DepthTest(true, GPU_GREATER, GPU_WRITE_ALL);
	C3D_CullFace(GPU_CULL_BACK_CCW);

	// Fog, re-established per frame for the same reason everything else here is: this is
	// global GPU state, not per-program state, and the moment a second pass touches it there
	// is no owner. The gas mode argument is only read when the fog mode is GPU_GAS, and the
	// zFlip argument is false because Mtx_PerspTilt is fed the same near/far the LUT was
	// built from — flipping it would run the curve backwards, fogging the player's hands and
	// leaving the horizon sharp, which is what this was checked against.
	C3D_FogGasMode(GPU_FOG, GPU_PLAIN_DENSITY, false);
	C3D_FogColor(SKY_FOG_BGR);
	C3D_FogLutBind(&s_fog_lut);

	for (int f = 0; f < BLOCK_FACES; f++) {
		const float s = kFaceShade[f];
		C3D_FVUnifSet(GPU_VERTEX_SHADER, s_uloc_faceshade + f, s, s, s, 1.0f);
	}
}

bool chunkRenderInit(void)
{
	// Fails if the pool ever outgrows DIRTYQ_MAX, at startup, rather than writing past
	// the flag array the first time a chunk in a high slot is edited.
	if (!dirtyqInit(&s_dirty, MESH_SLOTS))
		return false;

	s_dvlb = DVLB_ParseFile((u32*)world_shbin, world_shbin_size);
	shaderProgramInit(&s_program);
	shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);
	C3D_BindProgram(&s_program);

	s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
	s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
	s_uloc_faceshade  = shaderInstanceGetUniformLocation(s_program.vertexShader, "faceShade");

	// The whole pool, claimed once. If the console cannot give us this much linear
	// memory we want to know at startup, not when the player walks somewhere new.
	for (int i = 0; i < MESH_SLOTS; i++) {
		s_slots[i].verts   = (MeshVertex*)linearAlloc(sizeof(MeshVertex) * MESH_SLOT_VERTS);
		s_slots[i].indices = (uint16_t*)linearAlloc(sizeof(uint16_t) * MESH_SLOT_INDICES);
		if (!s_slots[i].verts || !s_slots[i].indices)
			return false;
		s_bytes += sizeof(MeshVertex) * MESH_SLOT_VERTS + sizeof(uint16_t) * MESH_SLOT_INDICES;
	}

	if (!atlasInit())
		return false;

	Mtx_PerspTilt(&s_projection, C3D_AngleFromDegrees(65.0f), 400.0f / 240.0f,
	              VIEW_NEAR, VIEW_FAR, false);

	// Built once — it is 512 bytes of exponentials and nothing about it changes per frame.
	// Only the three register writes that point the GPU at it are repeated, in pipelineBind.
	FogLut_Exp(&s_fog_lut, FOG_DENSITY, FOG_GRADIENT, VIEW_NEAR, VIEW_FAR);

	pipelineBind();
	return true;
}

// The world's projection matrix, so the highlight can line its cage up with the blocks
// rather than carrying a second copy of the field of view and near/far planes that would
// silently drift out of step with this one.
const C3D_Mtx* chunkRenderProjection(void)
{
	return &s_projection;
}

void chunkRenderExit(void)
{
	atlasExit();
	for (int i = 0; i < MESH_SLOTS; i++) {
		linearFree(s_slots[i].indices);
		linearFree(s_slots[i].verts);
	}
	shaderProgramFree(&s_program);
	DVLB_Free(s_dvlb);
}

bool chunkRenderBuild(const World* w, int cx, int cy, int cz)
{
	MeshSlot* s = slotFor(cx, cy, cz);
	if (!s) {
		s_refusals++;
		return false;
	}

	// Deliberately does not touch the dirty queue. Clearing the flag here looks like
	// tidiness and is how this shipped a bug for about three hours: the drain already
	// clears it, so a clear here decremented the count twice per drained chunk until it
	// went negative and the drain's early-out latched on. dirtyqClear is now idempotent,
	// so a repeat of that mistake costs nothing — but queueing is still the drain's
	// business and this function only meshes.
	// An all-air chunk cannot produce geometry: meshChunk emits faces only for solid cells
	// inside the chunk, and reads the neighbours purely for occlusion. So the 27-chunk
	// scratch fill and the 4,096-cell mesher walk are both pure waste here, and skipping
	// them is exact rather than an approximation. This became worth doing the moment a
	// dug-out chunk started keeping its slot: those chunks are now queued and remeshed
	// like any other, and every one of them was paying ~335 us to produce nothing. A chunk
	// with no storage at all is air by definition and takes the same path.
	const Chunk* chunk = worldChunk(w, cx, cy, cz);
	if (!chunk || chunkIsAllAir(chunk)) {
		s->cx = cx; s->cy = cy; s->cz = cz;
		s->vert_count = s->index_count = 0;
		s->used = true;

		// Nothing to draw, but sight still has to get through it — an all-air chunk joins
		// every pair of its faces. Skipping the flood fill here is exact, not an
		// approximation, and it matters: these are the chunks a player digs out and they
		// are re-meshed on every edit.
		s->vis_mask = VIS_ALL_CONNECTED;
		return true;
	}

	// Step 7.3, computed here and not per frame: it is a flood fill over 4,096 cells, and it
	// can only change when the chunk's blocks change — which is exactly when this runs.
	// Timed separately rather than folded into the scratch or mesh bucket, because it is new
	// cost added to a path that already has a measured budget, and a number that hides inside
	// another number cannot be argued with later.
	const u64 tv = svcGetSystemTick();
	s->vis_mask = visChunkConnectivity(chunk, &s_vis_scratch);
	s_vis_ticks += svcGetSystemTick() - tv;

	const u64 t0 = svcGetSystemTick();
	scratchFill(&s_scratch, w, cx, cy, cz);
	const u64 t1 = svcGetSystemTick();

	// Meshed straight into the slot's buffers: no staging copy, and the capacity
	// check inside the mesher is what protects the linear heap.
	MeshOut out = {0};
	out.verts     = s->verts;
	out.indices   = s->indices;
	out.vert_cap  = MESH_SLOT_VERTS;
	out.index_cap = MESH_SLOT_INDICES;
	meshChunk(&out, &s_scratch);

	s_scratch_ticks += t1 - t0;
	s_mesh_ticks    += svcGetSystemTick() - t1;
	s_build_count++;

	if (out.overflow) {
		s_refusals++;
		s->used = false;      // a half-mesh is worse than no mesh
		s->vert_count = s->index_count = 0;
		return false;
	}

	s->cx = cx; s->cy = cy; s->cz = cz;
	s->vert_count  = out.vert_count;
	s->index_count = out.index_count;

	// Claimed even when the chunk meshed to nothing. This used to be `out.faces > 0` — an
	// all-air chunk handed its slot straight back — and that was a bug you could reach by
	// playing: chunkRenderTouch only queues chunks that already own a slot, so a chunk dug
	// out to nothing became permanently unqueueable, and a block placed back into it would
	// exist in the World and never be drawn. The buffer is not wasted — slotFor takes an
	// empty slot ahead of refusing, so the memory is still recoverable under pressure; it
	// is only reserved while nothing else needs it.
	s->used = true;

	return true;
}

int chunkRenderReleaseColumn(int cx, int cz)
{
	int released = 0;
	for (int i = 0; i < MESH_SLOTS; i++) {
		MeshSlot* s = &s_slots[i];
		if (!s->used || s->cx != cx || s->cz != cz) continue;

		// The dirty flag goes with the slot. A flag left set on a released slot would send
		// the next drain to chunkRenderBuild with this slot's stale coordinates, which is
		// exactly the "meshes a chunk that is no longer in the world" case above — and it
		// would also consume the drain's budget doing it.
		dirtyqClear(&s_dirty, i);

		s->used = false;
		s->vert_count = s->index_count = 0;
		released++;
	}
	return released;
}

int chunkRenderTouch(const World* w, int x, int y, int z)
{
	// w is not needed to queue a chunk — only to mesh one — but the signature is kept
	// as-is so callers do not have to special-case this from chunkRenderBuild, and so
	// the world reference is already in hand on the day this needs to inspect block
	// state (e.g. to prioritise the queue) rather than just chunk coordinates.
	(void)w;

	ChunkCoord list[REMESH_MAX];
	const int n = remeshList(x, y, z, list);

	int queued = 0;
	for (int i = 0; i < n; i++) {
		// Only chunks that already have a mesh. A chunk with no slot is not on screen,
		// so meshing it here would be inventing a streaming policy — that is Phase 5,
		// and doing it early would also let one edit eat the pool.
		for (int k = 0; k < MESH_SLOTS; k++) {
			MeshSlot* s = &s_slots[k];
			if (!s->used || s->cx != list[i].cx || s->cy != list[i].cy || s->cz != list[i].cz)
				continue;

			if (dirtyqMark(&s_dirty, k))
				queued++;
			break;   // slots are one-to-one with chunk coordinates; nothing else can match
		}
	}
	return queued;
}

int chunkRenderDrainDirty(const World* w, float budget_ms, int max_chunks)
{
	// <= 0 rather than == 0. The count cannot go negative now that dirtyqClear owns it,
	// but an exact-equality early-out is what turned last night's miscount from a wrong
	// number into a world that stopped updating: at -3 the drain still ran, and the
	// moment three fresh edits brought it to exactly 0 it latched off for good.
	if (dirtyqCount(&s_dirty) <= 0) return 0;

	const u64  t0 = svcGetSystemTick();
	const float ticks_per_ms = (float)(SYSCLOCK_ARM11 / 1000);
	// A non-positive budget is clamped to zero rather than left negative, so the tick
	// comparison below behaves the same way "no time left" always does: the loop still
	// completes its first (guaranteed) chunk and then stops, instead of doing something
	// undefined with a negative tick count.
	const u64 budget_ticks = (budget_ms > 0.0f) ? (u64)(budget_ms * ticks_per_ms) : 0;

	int completed = 0;
	for (int i = 0; i < MESH_SLOTS; i++) {
		MeshSlot* s = &s_slots[i];
		if (!dirtyqIsMarked(&s_dirty, i)) continue;

		// chunkRenderBuild may decide the chunk is now all-air and hand the slot back
		// (s->used = false); either way the chunk this entry named has been dealt
		// with, so the dirty flag clears regardless of the outcome.
		chunkRenderBuild(w, s->cx, s->cy, s->cz);
		dirtyqClear(&s_dirty, i);
		completed++;

		// Checked after the rebuild, never before: a budget that is already spent (or
		// was zero/negative to begin with) must still let the chunk above complete, or
		// the queue would never drain and the world would visibly stop updating. Every
		// subsequent chunk in this call is genuinely optional against the budget.
		const u64 elapsed = svcGetSystemTick() - t0;
		if (elapsed >= budget_ticks) break;

		// The count cap, checked in the same place and for the same reason. A clock can
		// only stop the loop once a chunk has already overrun; the count stops it before
		// the *next* one starts, which is what makes the worst case a number that can be
		// written down (max_chunks x ~2.1 ms) rather than one that depends on how long a
		// chunk happened to take.
		if (completed >= max_chunks) break;

		if (dirtyqCount(&s_dirty) <= 0) break;
	}
	return completed;
}

int chunkRenderDirtyCount(void) { return dirtyqCount(&s_dirty); }
int chunkRenderDirtyPeak(void)  { return dirtyqPeak(&s_dirty); }

void chunkRenderDirtyResetPeak(void) { dirtyqResetPeak(&s_dirty); }

#if BS_CAVECULL
// Step 7.3, once per frame: box up every live slot, then walk sight outward from the camera.
// Sets s_cave_ran, which is what the draw loop consults — a walk that could not run must let
// everything through, because "the box was too big" is a missing optimisation and skipping
// chunks anyway would be a hole in the world.
static void caveWalk(const C3D_Mtx* view)
{
	int min_x = 0, min_y = 0, min_z = 0;
	int max_x = 0, max_y = 0, max_z = 0;
	bool any = false;

	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used) continue;
		if (!any) {
			min_x = max_x = s->cx; min_y = max_y = s->cy; min_z = max_z = s->cz;
			any = true;
			continue;
		}
		if (s->cx < min_x) min_x = s->cx;
		if (s->cx > max_x) max_x = s->cx;
		if (s->cy < min_y) min_y = s->cy;
		if (s->cy > max_y) max_y = s->cy;
		if (s->cz < min_z) min_z = s->cz;
		if (s->cz > max_z) max_z = s->cz;
	}
	if (!any) return;

	if (!visWalkBegin(&s_walk, min_x, min_y, min_z,
	                  max_x - min_x + 1, max_y - min_y + 1, max_z - min_z + 1))
		return;

	// Every claimed slot, including the ones that meshed to nothing: a chunk the player has
	// dug out draws no triangles but still has to let sight through, and leaving it out would
	// make it a hole in the box — which reads as open sky, so in this direction the mistake
	// would be harmless. Putting it in is still right, because its real connectivity is what
	// the walk should use the day step 7.5 gives an "empty" chunk water in it.
	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used) continue;
		visWalkSet(&s_walk, s->cx, s->cy, s->cz, s->vis_mask, s->index_count != 0);
	}

	// The camera, recovered from the view matrix rather than passed in. cameraView builds it
	// as rotations then a translation, so it is rigid: V = [R | -R*c], and c = -R^T * t. That
	// keeps chunkRenderDraw's signature honest — one matrix in, and no second copy of the
	// camera that could drift out of step with the one the vertices are transformed by.
	const C3D_FVec* r0 = &view->r[0];
	const C3D_FVec* r1 = &view->r[1];
	const C3D_FVec* r2 = &view->r[2];
	const float cam_x = -(r0->x * r0->w + r1->x * r1->w + r2->x * r2->w);
	const float cam_y = -(r0->y * r0->w + r1->y * r1->w + r2->y * r2->w);
	const float cam_z = -(r0->z * r0->w + r1->z * r1->w + r2->z * r2->w);

	s_cam_x = cam_x; s_cam_y = cam_y; s_cam_z = cam_z;

	visWalkRun(&s_walk, cam_x, cam_y, cam_z);
	s_cave_ran = true;
}
#endif

void chunkRenderDraw(const C3D_Mtx* view)
{
	pipelineBind();   // see pipelineBind: the highlight leaves the GPU set up for itself
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, &s_projection);

	// Step 7.1. Built once per frame from the same two matrices the draw uses, in the same
	// order, so the cull and the rasteriser cannot disagree about where the screen edge is.
	Frustum frustum;
	C3D_Mtx vp;
	Mtx_Multiply(&vp, &s_projection, view);
	frustumFromMatrix(&frustum, &vp);
	s_culled = 0;
	s_cave_culled = 0;
	s_cave_ran = false;

#if BS_CAVECULL
	caveWalk(view);
#endif

	// Visible slots, gathered before anything is drawn so step 7.2 can order them.
	int   visible[MESH_SLOTS];
	float depth[MESH_SLOTS];
	int   n = 0;

	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		if (!s->used || s->index_count == 0) continue;

		// The chunk's world-space box. Exactly CHUNK_DIM on a side: the mesher never emits
		// a vertex outside the chunk it was asked for, so there is no skin to add here, and
		// adding one "to be safe" would keep chunks that are genuinely off-screen.
		const float bx = (float)(s->cx * CHUNK_DIM);
		const float by = (float)(s->cy * CHUNK_DIM);
		const float bz = (float)(s->cz * CHUNK_DIM);

#if BS_FRUSTUM
		if (!frustumTestAABB(&frustum, bx, by, bz, bx + (float)CHUNK_DIM,
		                     by + (float)CHUNK_DIM, bz + (float)CHUNK_DIM)) {
			s_culled++;
			continue;
		}
#endif

#if BS_CAVECULL
		// Step 7.3. After the frustum, not before: the frustum test is four multiplies and
		// this is an array lookup, so the order barely matters for cost — but counting them
		// separately only means anything if each number is "what this test rejected that the
		// previous one had kept".
		if (s_cave_ran && !visWalkVisible(&s_walk, s->cx, s->cy, s->cz)) {
			s_cave_culled++;
			continue;
		}
#endif

		// Step 7.2's sort key: the chunk centre's clip-space w, which for this projection
		// is exactly its distance in front of the camera. Row 3 of the same view-projection
		// the frustum came from, so there is no second copy of the camera to keep in step —
		// one dot product, no square root, no camera position threaded through the API.
		const float h = (float)CHUNK_DIM * 0.5f;
		depth[n] = vp.r[3].x * (bx + h) + vp.r[3].y * (by + h) +
		           vp.r[3].z * (bz + h) + vp.r[3].w;
		visible[n] = i;
		n++;
	}

#if BS_SORT
	// Insertion sort, nearest first. Insertion rather than anything cleverer because n is
	// at most MESH_SLOTS (64) and in practice around a dozen after the frustum has run, and
	// because the order barely changes between frames — a nearly-sorted input is the case
	// insertion sort is linear on, which is exactly what walking through a world produces.
	for (int i = 1; i < n; i++) {
		const float d = depth[i];
		const int   v = visible[i];
		int j = i - 1;
		while (j >= 0 && depth[j] > d) {
			depth[j + 1]   = depth[j];
			visible[j + 1] = visible[j];
			j--;
		}
		depth[j + 1]   = d;
		visible[j + 1] = v;
	}
#endif

	// Proof that the order is what it claims to be, cheap enough to leave in: how many
	// chunks the sort actually moved out of slot order, and whether the emitted sequence is
	// really non-decreasing in depth. Without the first number, "the sort works" and "the
	// sort is a no-op" look identical on screen — the frame is meant to be unchanged either
	// way, since this is opaque geometry behind a depth test.
	s_sort_moved = 0;
	s_sort_ok    = true;
	for (int k = 0; k < n; k++) {
		if (k > 0 && depth[k] < depth[k - 1]) s_sort_ok = false;
		if (k > 0 && visible[k] < visible[k - 1]) s_sort_moved++;
	}

	for (int k = 0; k < n; k++) {
		const MeshSlot* s = &s_slots[visible[k]];

		// Vertices are chunk-local 0..16, so the chunk is placed with a matrix
		// rather than by baking world coordinates into bytes that could not hold
		// them anyway.
		C3D_Mtx model, mv;
		Mtx_Identity(&model);
		Mtx_Translate(&model, (float)(s->cx * CHUNK_DIM), (float)(s->cy * CHUNK_DIM),
		              (float)(s->cz * CHUNK_DIM), true);
		Mtx_Multiply(&mv, view, &model);
		C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, &mv);

		C3D_BufInfo* buf = C3D_GetBufInfo();
		BufInfo_Init(buf);
		BufInfo_Add(buf, s->verts, sizeof(MeshVertex), 2, 0x10);

		C3D_DrawElements(GPU_TRIANGLES, (int)s->index_count, C3D_UNSIGNED_SHORT, s->indices);
		metricsCountDraw(s->index_count / 3);
	}
}

int chunkRenderMeshes(void)
{
	// Slots holding geometry, which since the empty-slot fix is no longer the same as
	// slots claimed: a chunk dug out to nothing keeps its slot so it can be re-queued,
	// but it is not a mesh and reporting it as one would make the figure drift upwards
	// every time someone cleared a chunk.
	int n = 0;
	for (int i = 0; i < MESH_SLOTS; i++)
		if (s_slots[i].used && s_slots[i].index_count) n++;
	return n;
}

uint32_t chunkRenderTris(void)
{
	uint32_t t = 0;
	for (int i = 0; i < MESH_SLOTS; i++)
		if (s_slots[i].used) t += s_slots[i].index_count / 3;
	return t;
}

uint32_t chunkRenderChecksum(void)
{
	// XOR-combined per-slot hashes, so the result does not depend on which slot a chunk
	// happens to occupy — only on the geometry actually sitting in the pool. The chunk
	// coordinates are folded in, so two chunks swapping meshes would not cancel out.
	uint32_t total = 0;

	for (int i = 0; i < MESH_SLOTS; i++) {
		const MeshSlot* s = &s_slots[i];
		// vert_count, not `used`: a claimed slot holding no geometry contributes nothing
		// the GPU ever reads, so folding its coordinates in would change the checksum
		// according to which chunks happen to be empty rather than according to what is
		// drawn — and the whole point of this hash is the second thing.
		if (!s->used || s->vert_count == 0) continue;

		uint32_t h = 2166136261u;
		const int coords[3] = { s->cx, s->cy, s->cz };
		for (int c = 0; c < 3; c++) { h ^= (uint32_t)coords[c]; h *= 16777619u; }

		// Every byte the GPU reads: position, uv, normal index and AO. AO is the reason
		// this exists — a missed neighbour remesh usually loses a shadow without
		// changing a single triangle, so a triangle count cannot see it.
		const uint8_t* bytes = (const uint8_t*)s->verts;
		const uint32_t n = s->vert_count * (uint32_t)sizeof(MeshVertex);
		for (uint32_t b = 0; b < n; b++) { h ^= bytes[b]; h *= 16777619u; }

		total ^= h;
	}
	return total;
}

void chunkRenderProfileReset(void)
{
	s_scratch_ticks = s_mesh_ticks = 0;
	s_build_count = 0;
}

void chunkRenderProfile(float* scratch_us, float* mesh_us, int* builds)
{
	const float per_us = (float)(SYSCLOCK_ARM11 / 1000000);
	const int   n      = s_build_count ? s_build_count : 1;

	if (scratch_us) *scratch_us = (float)s_scratch_ticks / per_us / (float)n;
	if (mesh_us)    *mesh_us    = (float)s_mesh_ticks    / per_us / (float)n;
	if (builds)     *builds     = s_build_count;
}

int    chunkRenderCulled(void)     { return s_culled; }
int    chunkRenderSortMoved(void)  { return s_sort_moved; }
bool   chunkRenderSortOk(void)     { return s_sort_ok; }
int    chunkRenderCaveCulled(void) { return s_cave_culled; }
bool   chunkRenderCaveRan(void)    { return s_cave_ran; }

void chunkRenderCamera(float* x, float* y, float* z)
{
	if (x) *x = s_cam_x;
	if (y) *y = s_cam_y;
	if (z) *z = s_cam_z;
}

float chunkRenderVisUs(void)
{
	const float per_us = (float)(SYSCLOCK_ARM11 / 1000000);
	const int   n      = s_build_count ? s_build_count : 1;
	return (float)s_vis_ticks / per_us / (float)n;
}
int    chunkRenderRefusals(void) { return s_refusals; }
size_t chunkRenderBytes(void)    { return s_bytes; }
