#include "scene/crackoverlay.h"

#include "gfx/crackatlas.h"
#include "scene/chunk_render.h"   // for the world's projection, which this must match

#include "crack_shbin.h"   // generated by picasso from source/shaders/crack.v.pica

// Position plus texture coordinate, both float.
//
// Float positions rather than the world's packed 8-bit MeshVertex for the same reason
// scene/highlight.c's HlVertex uses them: the overlay sits CRACK_MARGIN outside the
// block's own faces, and a few thousandths of a block does not survive an 8-bit
// attribute. Float UVs because they are already normalised — see the note in
// source/shaders/crack.v.pica on why the sheet size is not divided in the shader.
typedef struct {
	float x, y, z;
	float u, v;
} CrackVertex;

// How far outside the block's own faces the overlay sits, in block units. This is the
// z-fighting guard: the overlay quad is otherwise exactly coplanar with the block face it
// covers, and two coplanar surfaces at the same depth interleave per-pixel into a mess
// that changes as the camera moves.
//
// 0.0015f, which is HL_MARGIN from scene/highlight.c to the digit. That value is already
// established in this project as "far enough outside a block face never to z-fight at any
// distance the camera can get to one, close enough still to read as being on that block",
// which is precisely the requirement here, so it is reused rather than a second unmeasured
// number being invented beside it. Sharing the number does NOT make the overlay fight the
// highlight cage: the cage's bars are boxes 0.025 thick spanning this plane rather than
// surfaces lying in it, so the two intersect and sort normally instead of interleaving.
//
// NOT verified on hardware from here — see the note at the bottom of this file.
#define CRACK_MARGIN  0.0015f

#define CRACK_FACES        6
#define CRACK_VERTS_PER_FACE 6                                   // two triangles, no index buffer
#define CRACK_VERTS_PER_STAGE (CRACK_FACES * CRACK_VERTS_PER_FACE)   // 36
#define CRACK_VERTS        (CRACK_STAGES * CRACK_VERTS_PER_STAGE)    // 288

// The six faces of the unit cube, each as four corners, each corner as a low/high
// selector per axis (0 = the cube's low side, 1 = its high side, axis order x, y, z).
//
// Corner order is bottom-left, bottom-right, top-right, top-left AS SEEN FROM OUTSIDE the
// cube, which does two jobs at once. It fixes the winding — cross(c1 - c0, c3 - c0) comes
// out along the face's outward normal, the same rule scene/highlight.c's addBox derives
// its boxes from and the same one world/mesher.c's kFaces follows — and it fixes the UV
// mapping, because "bottom-left to top-right" is exactly the order kFaceUV below assigns
// (0,0) to (1,1) in.
//
// For the four side faces "up" is +Y, so the crack art stands the right way up on a wall.
// The top and bottom faces have no natural up; they take -Z and +Z respectively, which is
// simply what falls out of keeping the winding rule above. Cracks are not lettering, so an
// arbitrary rotation there is invisible.
static const unsigned char kFaceCorners[CRACK_FACES][4][3] = {
	{ {1,0,1}, {1,0,0}, {1,1,0}, {1,1,1} },   // +X   right = -Z, up = +Y
	{ {0,0,0}, {0,0,1}, {0,1,1}, {0,1,0} },   // -X   right = +Z, up = +Y
	{ {0,1,1}, {1,1,1}, {1,1,0}, {0,1,0} },   // +Y   right = +X, up = -Z
	{ {0,0,0}, {1,0,0}, {1,0,1}, {0,0,1} },   // -Y   right = +X, up = +Z
	{ {0,0,1}, {1,0,1}, {1,1,1}, {0,1,1} },   // +Z   right = +X, up = +Y
	{ {1,0,0}, {0,0,0}, {0,1,0}, {1,1,0} },   // -Z   right = -X, up = +Y
};

// The corner-order-to-UV-corner mapping described above. u across, v up the face.
static const unsigned char kFaceUV[4][2] = { {0,0}, {1,0}, {1,1}, {0,1} };

// One shader program for the whole process, built the first time and never torn down.
//
// crackOverlayInit/crackOverlayExit run per session — join a world, leave, join again —
// and shaderProgramFree does not null program->vertexShader, while citro3d separately
// caches a pointer to the last program it bound. Freeing and rebuilding this static across
// a rejoin is the exact use-after-free that hard-crashes the console, already paid for once
// in this project; scene/highlight.c carries the same note and the same static for the same
// reason. The vertex buffer and the texture below are still released per session; only the
// shader is permanent.
static bool s_shader_ready;

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;

static CrackVertex* s_verts;      // linearAlloc'ed once per session, rebuilt never
static bool         s_ready;

// The V span of one stage's row on the crack sheet, normalised.
//
// Stage `stage` owns texture rows [stage*16, stage*16+16) of a 128-tall sheet, so the row
// runs from stage/CRACK_STAGES to (stage+1)/CRACK_STAGES. Texture v grows upwards, which
// is why tools/make_crack_atlas.py writes stage 0 to the LAST sixteen rows of the PNG; the
// two halves of that flip must agree or a different stage is sampled, silently.
static void crackStageV(int stage, float* v0, float* v1)
{
	*v0 = (float)stage / (float)CRACK_STAGES;
	*v1 = (float)(stage + 1) / (float)CRACK_STAGES;
}

// Fills verts with all CRACK_STAGES cubes back to back: stage s occupies vertices
// [s * CRACK_VERTS_PER_STAGE, (s+1) * CRACK_VERTS_PER_STAGE).
//
// Baking one cube per stage, rather than one cube plus a per-draw UV-offset uniform, is
// deliberate. It costs 5,760 bytes of linear memory, once, and in exchange the stage
// selection at draw time is a first-vertex offset into a buffer that was built correctly
// or not at all — there is no arithmetic left in the draw path that could put the UVs on
// the wrong row. Given that a wrong texture coordinate on this GPU renders *a* texture and
// never an error, moving the arithmetic to somewhere it runs eight times at startup
// instead of twenty times a second is worth the memory.
static void buildCubes(CrackVertex* verts)
{
	const float lo = -CRACK_MARGIN;
	const float hi = 1.0f + CRACK_MARGIN;

	int vi = 0;
	for (int stage = 0; stage < CRACK_STAGES; stage++) {
		float sv0, sv1;
		crackStageV(stage, &sv0, &sv1);

		for (int face = 0; face < CRACK_FACES; face++) {
			CrackVertex quad[4];
			for (int corner = 0; corner < 4; corner++) {
				const unsigned char* sel = kFaceCorners[face][corner];
				quad[corner].x = sel[0] ? hi : lo;
				quad[corner].y = sel[1] ? hi : lo;
				quad[corner].z = sel[2] ? hi : lo;
				quad[corner].u = kFaceUV[corner][0] ? 1.0f : 0.0f;
				quad[corner].v = kFaceUV[corner][1] ? sv1 : sv0;
			}
			// (c0, c1, c2) and (c0, c2, c3): the usual fan split of a quad, which keeps
			// both triangles wound the same way as the quad itself.
			verts[vi++] = quad[0];
			verts[vi++] = quad[1];
			verts[vi++] = quad[2];
			verts[vi++] = quad[0];
			verts[vi++] = quad[2];
			verts[vi++] = quad[3];
		}
	}
}

bool crackOverlayInit(void)
{
	if (!s_shader_ready) {
		s_dvlb = DVLB_ParseFile((u32*)crack_shbin, crack_shbin_size);
		if (!s_dvlb)
			return false;
		shaderProgramInit(&s_program);
		shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);

		s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
		s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
		s_shader_ready = true;
	}

	if (!crackAtlasInit())
		return false;

	s_verts = (CrackVertex*)linearAlloc(sizeof(CrackVertex) * CRACK_VERTS);
	if (!s_verts)
		return false;
	buildCubes(s_verts);

	// Built once by the CPU, read from RAM by the GPU. linearAlloc memory is cached, so
	// without this the GPU reads whatever the linear heap held before buildCubes ran —
	// the same flush scene/highlight.c and scene/chunk_render.c both perform, and for the
	// same reason.
	GSPGPU_FlushDataCache(s_verts, sizeof(CrackVertex) * CRACK_VERTS);

	s_ready = true;
	return true;
}

void crackOverlayExit(void)
{
	if (s_verts)
		linearFree(s_verts);
	s_verts = NULL;
	s_ready = false;

	crackAtlasExit();

	// The shader is deliberately not freed here — see s_shader_ready above. It costs one
	// DVLB and one shaderProgram_s for the life of the process, which is the price of not
	// handing citro3d a dangling shaderInstance the next time the player joins a world.
}

void crackOverlayDraw(const C3D_Mtx* view, int bx, int by, int bz, int stage)
{
	if (!s_ready)
		return;   // failed init degrades to "no crack overlay", not a crash

	// The clamp. Stated as two explicit comparisons rather than folded into the unsigned
	// trick world/atlas_uv.h's atlasRect() uses, because saturating is not the same as
	// clamping to a marker and the difference should be readable at a glance: there is no
	// missing-texture row to send an out-of-range stage to on an eight-row sheet, so it
	// pins to the ends instead.
	//
	// Without this, a stage of 8 would put the quad's v span at 8/8..9/8 — past the top of
	// the texture. GPU_CLAMP_TO_EDGE (gfx/crackatlas.c) would then smear the sheet's last
	// texel row across the whole face, which renders as a plausible-looking heavy crack and
	// never as an error. That is the failure mode this project has lost days to more than
	// once, so the guard is here rather than in the caller.
	if (stage < 0)
		stage = 0;
	if (stage > CRACK_STAGE_MAX)
		stage = CRACK_STAGE_MAX;

	// Nothing here is put back afterwards except the alpha test — see the GPU-state note in
	// crackoverlay.h. chunkRenderDraw re-establishes program, vertex format, TEV, depth,
	// cull and texture binding at the top of every call, so a second pass like this one
	// does not have to carry a stale duplicate of the world's state in order to restore it.
	C3D_BindProgram(&s_program);

	// This module's own attribute layout: position then texture coordinate.
	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);   // v0 = position
	AttrInfo_AddLoader(attr, 1, GPU_FLOAT, 2);   // v1 = texture coordinate

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(CrackVertex), 2, 0x10);

	// Takes texture unit 0 from the world atlas. Safe because chunkRenderDraw calls
	// atlasBind() at the top of every frame — see gfx/atlas.h's note on why that bind
	// exists at all, which step 8.3's sprite batch already made necessary.
	crackAtlasBind();

	// No fragment shader: TEV stage 0 REPLACEs with the crack sample. Not MODULATE against
	// the primary colour, which is what the world pass does — the overlay carries no baked
	// face shade or AO to modulate with, and shading the cracks by face would make the same
	// break look like a different one depending on which side of the block it is seen from.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, 0, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

	// The alpha TEST, not blending. The crack art is binary — a texel is a black crack or
	// it is nothing — so there is no partial coverage for a blend to resolve, and RGBA5551
	// could not carry one anyway with its single alpha bit. Same threshold and the same
	// GPU_GREATER as the transparent world pass (ALPHA_CUTOFF in scene/chunk_render.c):
	// the midpoint, so a filtered sample landing just off either extreme still lands on the
	// side it came from.
	C3D_AlphaTest(true, GPU_GREATER, 127);

	// Back faces culled with the same winding rule as the world, so only the three faces of
	// the cube actually facing the camera are rasterised. The other three would fail the
	// depth test against the block anyway; this skips them a stage earlier.
	C3D_CullFace(GPU_CULL_BACK_CCW);

	// Depth state is inherited from the world pass on purpose (GPU_GREATER, GPU_WRITE_ALL —
	// see chunk_render.c's pipelineBind). The overlay sits CRACK_MARGIN in front of the
	// block's own surface, so it passes; and because the alpha test rejects the transparent
	// texels before the depth write, the gaps between cracks leave the block's own depth
	// untouched.

	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, chunkRenderProjection());

	C3D_Mtx model, mv;
	Mtx_Identity(&model);
	Mtx_Translate(&model, (float)bx, (float)by, (float)bz, true);
	Mtx_Multiply(&mv, view, &model);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, &mv);

	// The stage selection: a first-vertex offset, not a uniform. See buildCubes.
	C3D_DrawArrays(GPU_TRIANGLES, stage * CRACK_VERTS_PER_STAGE, CRACK_VERTS_PER_STAGE);

	// Left off for whatever draws next, which is the one piece of state this pass does put
	// back. scene/chunk_render.c disables the alpha test at the end of its own draw and its
	// comment states that the later passes never set it — scene/highlight.c genuinely does
	// not — so an armed alpha test escaping from here would silently discard fragments in a
	// pass that has no idea it is being tested.
	C3D_AlphaTest(false, GPU_ALWAYS, 0);
}

// NOT VERIFIED FROM HERE, and stated rather than left implicit: nothing in this file has
// been compiled, linked or run. CRACK_MARGIN not z-fighting at long range, the crack art
// standing the right way up on a wall, and the winding in kFaceCorners producing the
// visible three faces rather than the hidden three are all VISUAL claims, and this project
// has a standing rule that a visual claim needs a look at the actual pixels. The checks
// that could be run without hardware — that the sheet is monotonic, binary-alpha and
// V-flipped the right way — live in tools/make_crack_atlas.py's verify_sheet().
