#include "scene/entitymodel.h"

#include "gfx/fogramp.h"          // the fade's shape, shared with the terrain pass
#include "gfx/fogtex.h"           // the ramp texture on unit 1, owned by gfx/, bound by both
#include "gfx/sprite.h"           // SPRITE_RGBA, which packs bytes the way the TEV wants
#include "scene/chunk_render.h"   // the world's projection and render boundary
#include "scene/frustum.h"

#include "highlight_shbin.h"   // generated by picasso from source/shaders/highlight.v.pica

// Lane A owns source/entity/animal.h and it does not exist yet. The four kind ids and the
// one-past-the-end sentinel are frozen in the blueprint's §11 contract, so they are spelled
// here as literals behind an include guard: the day animal.h lands this file picks up its
// definitions instead and the #defines below evaporate, with no edit and no chance of the
// two drifting apart. Nothing else about an animal is needed at P1 — the def table, the
// health, the drops and the AI are all Lane A's and none of them affect a draw call.
#if defined(__has_include)
#  if __has_include("entity/animal.h")
#    include "entity/animal.h"
#  endif
#endif

#ifndef ENT_KIND_PIG
#define ENT_KIND_PIG      1
#define ENT_KIND_COW      2
#define ENT_KIND_CHICKEN  3
#define ENT_KIND_SHEEP    4
#define ENT_KIND_COUNT    5   /* one past the last animal kind */
#endif

// Position-only float vertices, for playermodel.c's reasons exactly: no texture at P1, no
// per-vertex lighting, and dimensions in blocks that an 8-bit attribute cannot express. See
// entitymodel.h on why one attribute is also the thing that keeps the PICA alignment trap
// out of this phase.
typedef struct {
	float x, y, z;
} EmVertex;

#define EM_VERTS_PER_BOX  36              // 6 faces * 2 triangles * 3 vertices
#define EM_KINDS          (ENT_KIND_COUNT - ENT_KIND_PIG)   // 4
#define EM_VERTS          (EM_KINDS * EM_VERTS_PER_BOX)     // 144

// One box per kind, sized roughly like the animal it stands in for so that the fill-rate
// half of the measurement is not wildly off from what the real models will cost. Extents are
// half-width in x, full height in y, half-depth in z, with feet at the model origin — the
// same model space playermodel.c uses (feet at origin, +Y up, front facing -Z).
//
// These are placeholders and are meant to be thrown away by P7. They are NOT AnimalDef's
// width/height: Lane A owns those and this file must not become a second opinion about how
// big a cow is.
typedef struct {
	float    half_w, height, half_d;
	uint32_t colour;
} EmKind;

static const EmKind kKinds[EM_KINDS] = {
	/* pig     */ { 0.45f, 0.90f, 0.70f, SPRITE_RGBA(232, 152, 168, 255) },
	/* cow     */ { 0.45f, 1.30f, 0.75f, SPRITE_RGBA( 96,  72,  56, 255) },
	/* chicken */ { 0.20f, 0.70f, 0.20f, SPRITE_RGBA(232, 232, 216, 255) },
	/* sheep   */ { 0.45f, 1.20f, 0.65f, SPRITE_RGBA(216, 216, 208, 255) },
};

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;
static int             s_uloc_fogparams;

// The same -DFOG_DENSITY=0.0f override scene/chunk_render.c and scene/playermodel.c define,
// spelled the same way: a fog-off arm has to take the fade off the animals too or it would be
// measuring two different passes.
#ifndef FOG_DENSITY
#define FOG_DENSITY  (chunkRenderDistance()->fog_density)
#endif

// P1 measurement harness. A build with -DENTMODEL_PROBE_N=<n> draws n extra boxes laid out on
// a grid directly in front of the camera, in addition to whatever is really in the world.
// They are placed in VIEW space, not world space, so they are in front of the eye no matter
// where the player stands or looks — which is what makes N a controlled variable instead of a
// thing the player has to walk up to. In FRONT of the eye is not the same as VISIBLE, though:
// they are still depth-tested against the world, and the first probe run drew all 32 of them
// correctly behind a hillside four blocks away. See the placement knobs below.
// They pay the identical per-instance cost
// the real path pays (one modelView upload, one TEV constant write + dirty, one
// C3D_DrawArrays), because that per-instance cost is the entire quantity being measured.
// Default 0: a normal build contains the loop but never enters it.
#ifndef ENTMODEL_PROBE_N
#define ENTMODEL_PROBE_N 0
#endif

#define EM_PROBE_COLS   8       // 8 x 4 holds the 32 the blueprint's New-3DS cap asks for

// Where the grid sits, and whether it is depth-tested. Knobs rather than constants because
// the first probe run put the grid at 8 blocks while the player spawned looking down at
// ground 4 blocks away: all 32 boxes drew correctly and every one of them was hidden. Being
// able to move the grid and lift the depth test WITHOUT editing code is what separates "the
// draw path is broken" from "the boxes are behind a hill" — and those two are the same
// screenshot. ENTMODEL_PROBE_NODEPTH is for the visual check only, never a measurement arm:
// it removes the depth test and so removes exactly the early-Z rejection a real herd gets.
#ifndef ENTMODEL_PROBE_Z
#define ENTMODEL_PROBE_Z  (-8.0f)   // blocks in front of the eye; -Z is forward in view space
#endif
#ifndef ENTMODEL_PROBE_Y0
#define ENTMODEL_PROBE_Y0 (-1.5f)   // view-space y of the bottom row
#endif
#ifndef ENTMODEL_PROBE_NODEPTH
#define ENTMODEL_PROBE_NODEPTH 0
#endif

static EmVertex* s_verts;      // linearAlloc'ed once at init, rebuilt never
static bool      s_ready;

// Appends one axis-aligned box, six faces of two triangles each, and returns the index just
// past what it wrote. Copied from playermodel.c's addBox, winding and all, rather than shared
// — playermodel.h does not export it and a box builder is not worth a module. Culling is off
// during this draw (see entityModelDraw), so a transposed corner would show as a shading
// oddity rather than a hole. P7's models are script-generated and can afford GPU_CULL_BACK;
// hand-typing a winding at P1 to save triangles nobody has counted yet is the wrong order.
static int addBox(EmVertex* v, int vi, float x0, float y0, float z0,
                  float x1, float y1, float z1)
{
	// +X
	v[vi++] = (EmVertex){x1, y0, z0}; v[vi++] = (EmVertex){x1, y1, z0}; v[vi++] = (EmVertex){x1, y1, z1};
	v[vi++] = (EmVertex){x1, y0, z0}; v[vi++] = (EmVertex){x1, y1, z1}; v[vi++] = (EmVertex){x1, y0, z1};
	// -X
	v[vi++] = (EmVertex){x0, y0, z0}; v[vi++] = (EmVertex){x0, y0, z1}; v[vi++] = (EmVertex){x0, y1, z1};
	v[vi++] = (EmVertex){x0, y0, z0}; v[vi++] = (EmVertex){x0, y1, z1}; v[vi++] = (EmVertex){x0, y1, z0};
	// +Y
	v[vi++] = (EmVertex){x0, y1, z0}; v[vi++] = (EmVertex){x0, y1, z1}; v[vi++] = (EmVertex){x1, y1, z1};
	v[vi++] = (EmVertex){x0, y1, z0}; v[vi++] = (EmVertex){x1, y1, z1}; v[vi++] = (EmVertex){x1, y1, z0};
	// -Y
	v[vi++] = (EmVertex){x0, y0, z0}; v[vi++] = (EmVertex){x1, y0, z0}; v[vi++] = (EmVertex){x1, y0, z1};
	v[vi++] = (EmVertex){x0, y0, z0}; v[vi++] = (EmVertex){x1, y0, z1}; v[vi++] = (EmVertex){x0, y0, z1};
	// +Z
	v[vi++] = (EmVertex){x0, y0, z1}; v[vi++] = (EmVertex){x1, y0, z1}; v[vi++] = (EmVertex){x1, y1, z1};
	v[vi++] = (EmVertex){x0, y0, z1}; v[vi++] = (EmVertex){x1, y1, z1}; v[vi++] = (EmVertex){x0, y1, z1};
	// -Z
	v[vi++] = (EmVertex){x0, y0, z0}; v[vi++] = (EmVertex){x0, y1, z0}; v[vi++] = (EmVertex){x1, y1, z0};
	v[vi++] = (EmVertex){x0, y0, z0}; v[vi++] = (EmVertex){x1, y1, z0}; v[vi++] = (EmVertex){x1, y0, z0};

	return vi;
}

// All four kinds concatenated into one buffer, so the draw loop selects a kind by first-vertex
// offset and never rebinds a buffer. That is the shape §4.4 wants the textured renderer to
// keep, so P1 measures the same VBO topology P7 will ship.
static int kindFirst(uint8_t kind) { return (kind - ENT_KIND_PIG) * EM_VERTS_PER_BOX; }

static void buildBoxes(EmVertex* verts)
{
	int vi = 0;
	for (int k = 0; k < EM_KINDS; k++) {
		const EmKind* d = &kKinds[k];
		vi = addBox(verts, vi, -d->half_w, 0.0f,      -d->half_d,
		                        d->half_w, d->height,  d->half_d);
	}
	(void)vi;
}

_Static_assert(EM_VERTS == 144, "four kinds of one twelve-triangle box");

// One shader program for the whole process, built the first time and never torn down. Same
// reasoning as playermodel.c and highlight.c: init/exit run per session, and freeing and
// rebuilding this static across a rejoin is the citro3d use-after-free that hard-crashes the
// console. The vertex buffer below is still freed per session; only the shader is permanent.
static bool s_shader_ready;

bool entityModelInit(void)
{
	if (!s_shader_ready) {
		s_dvlb = DVLB_ParseFile((u32*)highlight_shbin, highlight_shbin_size);
		if (!s_dvlb)
			return false;
		shaderProgramInit(&s_program);
		shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);

		s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
		s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
		s_uloc_fogparams  = shaderInstanceGetUniformLocation(s_program.vertexShader, "fogParams");
		s_shader_ready = true;
	}

	s_verts = (EmVertex*)linearAlloc(sizeof(EmVertex) * EM_VERTS);
	if (!s_verts)
		return false;
	buildBoxes(s_verts);

	// linearAlloc memory is cached and the GPU reads it straight out of RAM. Without this
	// flush the GPU sees whatever the linear heap held before buildBoxes ran — the same
	// defect, fix and consequence as the flush in chunkRenderBuild and playerModelInit.
	GSPGPU_FlushDataCache(s_verts, sizeof(EmVertex) * EM_VERTS);

	s_ready = true;
	return true;
}

void entityModelExit(void)
{
	if (s_verts)
		linearFree(s_verts);
	s_verts = NULL;
	s_ready = false;

	// The shader is deliberately not freed here — see s_shader_ready above.
}

// One instance: compose the model matrix onto the view, upload it, set the flat colour and
// draw. Split out only because the world path and the probe path differ in how they arrive at
// `mv` and in nothing else, and the whole point of the measurement is that both pay exactly
// the same per-instance cost.
static void drawOne(C3D_TexEnv* env, const C3D_Mtx* mv, uint8_t kind)
{
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, mv);

	// C3D_TexEnvColor is a plain write into citro3d's shadow copy of the stage and does not
	// mark it dirty — only C3D_GetTexEnv and C3D_DirtyTexEnv do. Without the explicit dirty
	// the register uploads once and every animal after the first is drawn in the first one's
	// colour, which looks exactly like a working palette until two kinds are on screen at
	// once. playermodel.c:311-316 was bitten by this; it is spelled out again here.
	C3D_TexEnvColor(env, kKinds[kind - ENT_KIND_PIG].colour);
	C3D_DirtyTexEnv(env);

	C3D_DrawArrays(GPU_TRIANGLES, kindFirst(kind), EM_VERTS_PER_BOX);
}

void entityModelDraw(const C3D_Mtx* view, const EntityWorld* ew)
{
	if (!s_ready)
		return;   // failed init degrades to "no animals are drawn", not a crash

	const int live = ew ? entityCount(ew) : 0;
	if (live <= 0 && ENTMODEL_PROBE_N == 0)
		return;   // nothing in the world and no probe: the common case today, costs nothing

	// Nothing set here is put back afterwards, deliberately — see entitymodel.h and the same
	// note in playermodel.c. chunkRenderDraw re-establishes its entire pipeline at the top of
	// every call, so one owner of that state is better than two copies.
	C3D_BindProgram(&s_program);

	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(EmVertex), 1, 0x0);

	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_CONSTANT, 0, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

	// TEV stage 1 and the fog unit, owned here rather than inherited — the same block
	// playermodel.c:240-274 explains at length. An animal can be at any distance out to the
	// load boundary, so it genuinely wants the fade, and it must be the SAME fade the terrain
	// behind it gets: same ramp texture, same fogShapeFor(), same boundary. One curve.
	fogTexBind();

	C3D_TexEnv* fog = C3D_GetTexEnv(1);
	C3D_TexEnvInit(fog);
	C3D_TexEnvSrc(fog, C3D_RGB, GPU_CONSTANT, GPU_PREVIOUS, GPU_TEXTURE1);
	C3D_TexEnvOpRgb(fog, GPU_TEVOP_RGB_SRC_COLOR, GPU_TEVOP_RGB_SRC_COLOR,
	                GPU_TEVOP_RGB_SRC_ALPHA);
	C3D_TexEnvFunc(fog, C3D_RGB, GPU_INTERPOLATE);
	C3D_TexEnvSrc(fog, C3D_Alpha, GPU_PREVIOUS, 0, 0);
	C3D_TexEnvFunc(fog, C3D_Alpha, GPU_REPLACE);
	C3D_TexEnvColor(fog, SKY_FOG_BGR | 0xFF000000u);

	// The hardware fog unit stays off: its LUT is indexed by 1/w and is the exact ceiling
	// v1.9.0 removed, so leaving it on would fog these boxes twice on two different curves.
	C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);

	const RenderDist* rd  = chunkRenderDistance();   // documented never-NULL
	const FogShape    fog_shape = fogShapeFor(rd->boundary, FOG_DENSITY);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, s_uloc_fogparams,
	              fog_shape.inv_range, fog_shape.bias, 0.0f, 0.0f);

	// Culling off, matching playerModelDraw and highlightDraw. See addBox.
	C3D_CullFace(GPU_CULL_NONE);

	const C3D_Mtx* proj = chunkRenderProjection();
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, proj);

	// ---- culling setup, done once for the whole pass ------------------------------------
	//
	// The frustum comes out of projection x view, multiplied in the same order the draw uses,
	// so the cull agrees with the rasteriser at the screen edges. Do not re-derive the plane
	// extraction: the PICA's clip z range is [-w,0], not GL's [-w,w], and getting the far
	// plane backwards was measured on this project as culling the entire world.
	C3D_Mtx vp;
	Mtx_Multiply(&vp, proj, view);
	Frustum frustum;
	frustumFromMatrix(&frustum, &vp);

	// Camera position, for the cheap distance reject that runs before the frustum test.
	// A view matrix is R * Translate(-eye) with R orthonormal — scene/camera.c builds
	// RotateX(pitch) * RotateY(yaw) * Translate(-eye), as playermodel.c:298-301 states — so
	// the eye is -R^T applied to the view's translation column. No inverse, no square root,
	// and it holds for as long as nothing puts a scale into the view matrix.
	const float t0 = view->r[0].w, t1 = view->r[1].w, t2 = view->r[2].w;
	const float cam_x = -(view->r[0].x * t0 + view->r[1].x * t1 + view->r[2].x * t2);
	const float cam_y = -(view->r[0].y * t0 + view->r[1].y * t1 + view->r[2].y * t2);
	const float cam_z = -(view->r[0].z * t0 + view->r[1].z * t1 + view->r[2].z * t2);
	(void)cam_y;   // the distance reject is horizontal; see below

	// Squared, against the boundary the fog fades to, so an animal is never popped while it
	// is still visible. Horizontal only: the load boundary is a horizontal radius and a
	// vertical term would cull a sheep on a hilltop the player can plainly see.
	const float cull_r2 = rd->boundary * rd->boundary;

	// ---- the real animals ---------------------------------------------------------------
	//
	// entity.h:259-265's own documented reading pattern, verbatim: entityCount is the
	// early-out, entityGet is the iterator, the Entity's fields are the pose. No draw list,
	// no per-frame copy, no callback from entity/ into scene/.
	for (int i = 0; i < ENTITY_SLOTS; i++) {
		const Entity* e = entityGet(ew, i);
		if (!e)
			continue;
		if (e->kind < ENT_KIND_PIG || e->kind >= ENT_KIND_COUNT)
			continue;   // not an animal — v1.8.16's problem, not this file's

		const float dx = e->body.x - cam_x;
		const float dz = e->body.z - cam_z;
		if (dx * dx + dz * dz > cull_r2)
			continue;

		// The AABB is the box's world extent with yaw ignored: the largest horizontal
		// half-extent is used on both axes, which over-estimates the footprint of a rotated
		// long body and can therefore only ever keep a box that should have been culled.
		// That costs one draw call; the opposite error erases an animal the player can see.
		const EmKind* d = &kKinds[e->kind - ENT_KIND_PIG];
		const float   r = d->half_w > d->half_d ? d->half_w : d->half_d;
		if (!frustumTestAABB(&frustum,
		                     e->body.x - r, e->body.y,            e->body.z - r,
		                     e->body.x + r, e->body.y + d->height, e->body.z + r))
			continue;

		// Rotate then translate, which in citro3d's post-multiplying convention means
		// calling Translate before RotateY. The yaw sign is negative for playermodel.c's
		// reason: the view matrix rotates the world by +yaw about Y, so a model authored
		// facing -Z reaches the heading of an entity with yaw y under RotateY(-y).
		C3D_Mtx model, mv;
		Mtx_Identity(&model);
		Mtx_Translate(&model, e->body.x, e->body.y, e->body.z, true);
		Mtx_RotateY(&model, -e->yaw, true);
		Mtx_Multiply(&mv, view, &model);

		drawOne(env, &mv, e->kind);
	}

	// ---- P1 probe -----------------------------------------------------------------------
	//
	// Compiled out entirely at the default ENTMODEL_PROBE_N of 0. Built directly in view
	// space — the model matrix IS the modelView — so every box is in front of the eye and
	// inside the frustum by construction, whatever the player is doing. That is the point:
	// N is the variable, and "how many did the player happen to be looking at" must not be.
#if ENTMODEL_PROBE_N > 0
#if ENTMODEL_PROBE_NODEPTH
	// Visual-check arm only. chunkRenderDraw's pipelineBind re-establishes
	// C3D_DepthTest(true, GPU_GREATER, GPU_WRITE_ALL) at the top of every frame
	// (chunk_render.c:1237), so this heals itself exactly like every other piece of state
	// this file deliberately does not restore.
	C3D_DepthTest(false, GPU_ALWAYS, GPU_WRITE_COLOR);
#endif
	for (int i = 0; i < ENTMODEL_PROBE_N; i++) {
		const int col = i % EM_PROBE_COLS;
		const int row = i / EM_PROBE_COLS;

		C3D_Mtx mv;
		Mtx_Identity(&mv);
		Mtx_Translate(&mv,
		              -3.5f + (float)col * 1.0f,
		              ENTMODEL_PROBE_Y0 + (float)row * 1.0f,
		              ENTMODEL_PROBE_Z, true);

		// Cycled across all four kinds so the pass writes a different TEV constant for every
		// draw, exactly as a real mixed herd would. A probe that drew one colour would let the
		// hardware coalesce state the shipping path never gets to coalesce.
		drawOne(env, &mv, (uint8_t)(ENT_KIND_PIG + (i & 3)));
	}
#endif
}
