#include "scene/entitymodel.h"

#include <tex3ds.h>

#include "gfx/fogramp.h"          // the fade's shape and curve, shared with the terrain pass
#include "gfx/sprite.h"           // SPRITE_RGBA, which packs bytes the way the TEV wants
#include "scene/chunk_render.h"   // the world's projection and render boundary
#include "scene/frustum.h"

#include "animals_t3x.h"       // generated by tex3ds from gfx/animals.t3s
#include "crack_shbin.h"       // generated by picasso from source/shaders/crack.v.pica

// The four kind ids and the one-past-the-end sentinel. source/entity/animal.h owns them;
// this include guard predates that file and is kept because it costs nothing and the
// alternative — a hard include — is a build break for anyone bisecting across the commit
// that added it.
#if defined(__has_include)
#  if __has_include("entity/animal.h")
#    include "entity/animal.h"
#  endif
#endif

#ifndef ENT_KIND_PIG
#define ENT_KIND_PIG      1
#define ENT_KIND_COW      2
#define ENT_KIND_CHICKEN  3
#define ENT_KIND_SHEEP    4
#define ENT_KIND_COUNT    5   /* one past the last animal kind */
#endif

// entitymodel.h's kEmBoxes is indexed 0..3 in the id order below, and nothing in this file
// re-derives that mapping — kindFirst() is (kind - ENT_KIND_PIG). If a fifth animal is
// appended, or the ids are ever renumbered, this is what stops the build instead of
// silently drawing a sheep where a cow should be.
_Static_assert(EM_KINDS == ENT_KIND_COUNT - ENT_KIND_PIG,
               "entitymodel.h's EM_KINDS must equal the number of animal kind ids");
_Static_assert(ENT_KIND_COW == ENT_KIND_PIG + 1 && ENT_KIND_CHICKEN == ENT_KIND_PIG + 2
               && ENT_KIND_SHEEP == ENT_KIND_PIG + 3,
               "kEmBoxes is in pig, cow, chicken, sheep order and is indexed by id offset");

// ── the flat-colour fallback ─────────────────────────────────────────────────────────────
//
// One colour per kind, used ONLY when gfx/animals.t3x could not be imported. That is the
// v1.8.14 probe's entire renderer, kept because "the texture did not load" must degrade to
// an untextured pig rather than to no animals or to a crash — the same degrade-to-nothing
// posture playerModelInit() and highlightInit() have, one notch softer.
//
// These are NOT the sheet's palette and are not kept in step with it. They exist to make a
// failed texture obvious at a glance (flat, unshaded, plainly wrong) rather than to
// impersonate the real art badly enough that nobody notices the sheet is missing.
static const uint32_t kFlatColour[EM_KINDS] = {
	/* pig     */ SPRITE_RGBA(223, 143, 156, 255),
	/* cow     */ SPRITE_RGBA(236, 232, 222, 255),
	/* chicken */ SPRITE_RGBA(241, 237, 221, 255),
	/* sheep   */ SPRITE_RGBA(229, 225, 217, 255),
};

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;

// The same -DFOG_DENSITY=0.0f override scene/chunk_render.c and scene/playermodel.c define,
// spelled the same way: a fog-off arm has to take the fade off the animals too or it would be
// measuring two different passes.
#ifndef FOG_DENSITY
#define FOG_DENSITY  (chunkRenderDistance()->fog_density)
#endif

// P1 measurement harness, kept verbatim from v1.8.14. A build with -DENTMODEL_PROBE_N=<n>
// draws n extra animals laid out on a grid directly in front of the camera, in addition to
// whatever is really in the world. They are placed in VIEW space, not world space, so they
// are in front of the eye no matter where the player stands or looks — which is what makes N
// a controlled variable instead of a thing the player has to walk up to. In FRONT of the eye
// is not the same as VISIBLE, though: they are still depth-tested against the world, and the
// first probe run drew all 32 of them correctly behind a hillside four blocks away. See the
// placement knobs below. They pay the identical per-instance cost the real path pays (one
// modelView upload, one TEV constant write + dirty, one C3D_DrawArrays), because that
// per-instance cost is the entire quantity being measured.
// Default 0: a normal build contains the loop but never enters it.
#ifndef ENTMODEL_PROBE_N
#define ENTMODEL_PROBE_N 0
#endif

#define EM_PROBE_COLS   8       // 8 x 4 holds the 32 the blueprint's New-3DS cap asks for

// Where the grid sits, and whether it is depth-tested. Knobs rather than constants because
// the first probe run put the grid at 8 blocks while the player spawned looking down at
// ground 4 blocks away: all 32 boxes drew correctly and every one of them was hidden. Being
// able to move the grid and lift the depth test WITHOUT editing code is what separates "the
// draw path is broken" from "the boxes are behind a hill" — and those two are the same
// screenshot. ENTMODEL_PROBE_NODEPTH is for the visual check only, never a measurement arm:
// it removes the depth test and so removes exactly the early-Z rejection a real herd gets.
#ifndef ENTMODEL_PROBE_Z
#define ENTMODEL_PROBE_Z  (-8.0f)   // blocks in front of the eye; -Z is forward in view space
#endif
#ifndef ENTMODEL_PROBE_Y0
#define ENTMODEL_PROBE_Y0 (-1.5f)   // view-space y of the bottom row
#endif
#ifndef ENTMODEL_PROBE_NODEPTH
#define ENTMODEL_PROBE_NODEPTH 0
#endif

static EmVertex* s_verts;      // linearAlloc'ed once per session, rebuilt never
static bool      s_ready;

static C3D_Tex   s_tex;
static bool      s_textured;   // false => the flat-colour fallback above

// Per-kind culling extents, derived from kEmBoxes at init by emKindExtent(). Cached rather
// than recomputed per draw only because it is a loop over 24 boxes and the draw runs it once
// per visible animal per eye; the values themselves are not a second opinion about how big a
// cow is, they are the table's own answer.
static float s_half_horiz[EM_KINDS];
static float s_height[EM_KINDS];

// All four kinds concatenated into one buffer, so the draw loop selects a kind by
// first-vertex offset and never rebinds a buffer. One draw call per animal, six boxes deep.
static int kindFirst(uint8_t kind) { return (kind - ENT_KIND_PIG) * EM_VERTS_PER_KIND; }

// One shader program for the whole process, built the first time and never torn down. Same
// reasoning as playermodel.c, crackoverlay.c and highlight.c: init/exit run per session, and
// freeing and rebuilding this static across a rejoin is the citro3d use-after-free that
// hard-crashes the console. The vertex buffer and the texture below are still freed per
// session; only the shader is permanent.
//
// The program is source/shaders/crack.v.pica, reused verbatim — not a new shader. It already
// does exactly what this pass needs and nothing it does not: projection and modelView as two
// separate uniforms (a per-animal model matrix rules out particle.v.pica's single combined
// viewProj), a float3 position, and a float2 texcoord passed straight through with no uvScale
// to keep in step. scene/playermodel.c reuses scene/highlight.c's program the same way, and
// two shaderPrograms over one DVLB'd binary is the established shape here.
static bool s_shader_ready;

// v1.8.16: the fade is PER ANIMAL, not per vertex, and that is a real change from the
// v1.8.14 probe — worth writing down because it looks like a downgrade and is not.
//
// The probe drew through highlight.v.pica, which emits a fog coordinate on texcoord1 that TEV
// stage 1 turned into a fade by sampling gfx/fogtex.c's ramp. crack.v.pica writes no
// texcoord1 (it spends that output on texcoord0, which is the entire point of using it), and
// this lane does not own source/shaders/, so the fade is computed here on the CPU instead and
// delivered as the stage's constant colour: the ramp coordinate for the animal's own
// eye-space depth, through fogRampCurve() — the SAME curve gfx/fogramp.c bakes into the
// texture the terrain samples, so an animal and the hill behind it still fade on one curve.
//
// What is lost is the variation ACROSS one animal, and it is negligible by construction: the
// fade spans from 0.25*end to end (FOG_START_FRAC, gfx/fogramp.h), which at the smallest
// shipping render distance is tens of blocks, against a model at most 1.5 blocks long. What
// is gained is that the cost is unchanged — the probe already wrote and dirtied one TEV
// constant per animal, and this is that same write moved from stage 0 to stage 1.
//
// NOT the same as the fixed-function fog unit, which stays off below for the reason v1.9.0
// removed it everywhere: its LUT is indexed by 1/w and cannot bend past ~20 blocks.
static uint8_t fogAlphaFor(const FogShape* shape, float depth_blocks)
{
	float u = depth_blocks * shape->inv_range + shape->bias;
	// fogRampCurve clamps to [0,1] itself, which is the CPU-side equivalent of the ramp
	// texture's GPU_CLAMP_TO_EDGE — see gfx/fogramp.c.
	const float f = fogRampCurve(u);
	const int   a = (int)(f * 255.0f + 0.5f);
	return (uint8_t)(a < 0 ? 0 : (a > 255 ? 255 : a));
}

bool entityModelInit(void)
{
	if (!s_shader_ready) {
		s_dvlb = DVLB_ParseFile((u32*)crack_shbin, crack_shbin_size);
		if (!s_dvlb)
			return false;
		shaderProgramInit(&s_program);
		shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);

		s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
		s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
		s_shader_ready = true;
	}

	s_verts = (EmVertex*)linearAlloc(sizeof(EmVertex) * EM_VERTS);
	if (!s_verts)
		return false;
	for (int k = 0; k < EM_KINDS; k++) {
		emBuildKind(k, s_verts + k * EM_VERTS_PER_KIND);
		emKindExtent(k, &s_half_horiz[k], &s_height[k]);
	}

	// linearAlloc memory is cached and the GPU reads it straight out of RAM. Without this
	// flush the GPU sees whatever the linear heap held before the build ran — the same
	// defect, fix and consequence as the flush in chunkRenderBuild and crackOverlayInit.
	GSPGPU_FlushDataCache(s_verts, sizeof(EmVertex) * EM_VERTS);

	// ── the sheet ────────────────────────────────────────────────────────────────────────
	//
	// A separate texture from the block atlas, following gfx/crackatlas.c's precedent and for
	// a stronger version of its reason: the animal pass binds its own shader and its own
	// texture unit state anyway, the block sheet's slots are 16 px square and an animal net is
	// 60 px wide, and folding this in would mean sampling two regions of one sheet from a
	// shader that has one layout. 128x128 at RGBA5551 is 32,768 bytes of VRAM — computed from
	// the sheet, not measured on-device.
	//
	// vram = true, same as the world atlas and the crack sheet: texture reads out of VRAM are
	// the cheap ones on this GPU.
	Tex3DS_Texture t3x = Tex3DS_TextureImport(animals_t3x, animals_t3x_size, &s_tex, NULL, true);
	if (t3x) {
		Tex3DS_TextureFree(t3x);   // the descriptor only describes the layout; pixels are in s_tex

		// Nearest on both filters and no mipmaps, exactly as gfx/atlas.c and gfx/crackatlas.c
		// ask for. This is pixel art at 16 texels to the block and the look depends on the
		// texels staying square; more to the point the four animals' quadrants are directly
		// adjacent with no gutter, so a mip chain would average a pig's flank into a cow's.
		// gfx/animals.t3s passes tex3ds only "-f rgba5551 -z auto" with no -m, and neither
		// filter here is a GPU_*_MIPMAP_* mode, so no level beyond the base is ever sampled.
		C3D_TexSetFilter(&s_tex, GPU_NEAREST, GPU_NEAREST);

		// CLAMP_TO_EDGE on BOTH axes, as the design requires and for gfx/crackatlas.c's
		// reason: nothing here merges or tiles, every UV this file bakes is inside [0,1] on
		// both axes by construction, and GPU_REPEAT would turn a future arithmetic slip into a
		// plausible-looking tiled animal instead of an obvious smear. On a sheet with four
		// different animals on it, "plausible-looking" is the expensive failure.
		C3D_TexSetWrap(&s_tex, GPU_CLAMP_TO_EDGE, GPU_CLAMP_TO_EDGE);
		s_textured = true;
	} else {
		// Not a failure of init. See kFlatColour above and entitymodel.h.
		s_textured = false;
	}

	s_ready = true;
	return true;
}

void entityModelExit(void)
{
	if (s_verts)
		linearFree(s_verts);
	s_verts = NULL;

	if (s_textured)
		C3D_TexDelete(&s_tex);
	s_textured = false;

	s_ready = false;

	// The shader is deliberately not freed here — see s_shader_ready above.
}

bool entityModelTextured(void)
{
	return s_textured;
}

// One instance: compose the model matrix onto the view, upload it, set this animal's fade
// and draw. Split out only because the world path and the probe path differ in how they
// arrive at `mv` and in nothing else, and the whole point of the measurement the probe still
// supports is that both pay exactly the same per-instance cost.
//
// `fog` is the stage whose CONSTANT carries the fade; `flat` is the stage-0 fallback stage,
// NULL when the sheet loaded. C3D_TexEnvColor is a plain write into citro3d's shadow copy of
// the stage and does not mark it dirty — only C3D_GetTexEnv and C3D_DirtyTexEnv do. Without
// the explicit dirty the register uploads once and every animal after the first is drawn with
// the first one's fade, which looks exactly like working fog until two animals are at two
// distances at once. playermodel.c:311-316 was bitten by this; it is spelled out again here.
static void drawOne(C3D_TexEnv* fog, C3D_TexEnv* flat, const C3D_Mtx* mv,
                    uint8_t kind, uint8_t fog_alpha)
{
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, mv);

	C3D_TexEnvColor(fog, SKY_FOG_BGR | ((uint32_t)fog_alpha << 24));
	C3D_DirtyTexEnv(fog);

	if (flat) {
		C3D_TexEnvColor(flat, kFlatColour[kind - ENT_KIND_PIG]);
		C3D_DirtyTexEnv(flat);
	}

	C3D_DrawArrays(GPU_TRIANGLES, kindFirst(kind), EM_VERTS_PER_KIND);
}

void entityModelDraw(const C3D_Mtx* view, const EntityWorld* ew)
{
	if (!s_ready)
		return;   // failed init degrades to "no animals are drawn", not a crash

	const int live = ew ? entityCount(ew) : 0;
	if (live <= 0 && ENTMODEL_PROBE_N == 0)
		return;   // nothing in the world and no probe: the common case today, costs nothing

	// Nothing set here is put back afterwards, deliberately — see entitymodel.h and the same
	// note in playermodel.c. chunkRenderDraw re-establishes its entire pipeline at the top of
	// every call, so one owner of that state is better than two copies.
	C3D_BindProgram(&s_program);

	// Position then texture coordinate. Both GPU_FLOAT, so attribute 1 lands on byte offset
	// 12 and every attribute in the vertex is 4-byte aligned by construction — the PICA
	// alignment trap needs a sub-4-byte component to exist at all. entitymodel.h's header
	// comment carries the full account; chunk_render.c:1196-1213 carries the hardware capture.
	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);   // v0 = position
	AttrInfo_AddLoader(attr, 1, GPU_FLOAT, 2);   // v1 = texture coordinate

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(EmVertex), 2, 0x10);

	// ONE bind for the whole pass, not one per animal: all four kinds live on one sheet and
	// a kind is a first-vertex offset, so nothing in the loop below touches a texture unit.
	// Taking unit 0 from the world atlas is safe for gfx/crackatlas.h's stated reason —
	// scene/chunk_render.c's pipelineBind calls atlasBind() at the top of every frame's draw,
	// and this pass runs after the world pass.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnv* flat = NULL;
	if (s_textured) {
		C3D_TexBind(0, &s_tex);
		// REPLACE with the sample, not MODULATE against the primary colour: the animals carry
		// no baked face shade or AO for a primary colour to mean anything, and crack.v.pica
		// writes a constant white there anyway.
		C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, 0, 0);
		C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);
	} else {
		C3D_TexEnvSrc(env, C3D_Both, GPU_CONSTANT, 0, 0);
		C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);
		flat = env;
	}

	// TEV stage 1: the distance fade, owned here rather than inherited — the same discipline
	// crackoverlay.c, highlight.c, sprite.c and particles.c all follow. INTERPOLATE computes
	// src0*src2 + src1*(1-src2), so with the sky colour in the constant's RGB, the animal in
	// PREVIOUS, and the fade in the constant's ALPHA, a fog_alpha of 0 leaves the animal
	// untouched and 255 replaces it with the sky. See fogAlphaFor() for where the number comes
	// from and why it is per animal.
	C3D_TexEnv* fog = C3D_GetTexEnv(1);
	C3D_TexEnvInit(fog);
	C3D_TexEnvSrc(fog, C3D_RGB, GPU_CONSTANT, GPU_PREVIOUS, GPU_CONSTANT);
	C3D_TexEnvOpRgb(fog, GPU_TEVOP_RGB_SRC_COLOR, GPU_TEVOP_RGB_SRC_COLOR,
	                GPU_TEVOP_RGB_SRC_ALPHA);
	C3D_TexEnvFunc(fog, C3D_RGB, GPU_INTERPOLATE);
	C3D_TexEnvSrc(fog, C3D_Alpha, GPU_PREVIOUS, 0, 0);
	C3D_TexEnvFunc(fog, C3D_Alpha, GPU_REPLACE);

	// Texture unit 1 stays bound to the fog ramp from the world pass (citro3d has no unbind —
	// see gfx/fogtex.c), but no stage sources it here, so nothing samples it. That is why this
	// file no longer calls fogTexBind().

	// The hardware fog unit stays off: its LUT is indexed by 1/w and is the exact ceiling
	// v1.9.0 removed, so leaving it on would fog these animals twice on two different curves.
	C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);

	const RenderDist* rd  = chunkRenderDistance();   // documented never-NULL
	const FogShape    fog_shape = fogShapeFor(rd->boundary, FOG_DENSITY);

	// Culling off, matching playerModelDraw and highlightDraw. The six boxes of an animal
	// overlap at every joint, so back faces are hidden by the depth test rather than by the
	// winding, and a transposed corner in emBoxFaceQuad would show as a shading oddity rather
	// than as a hole.
	C3D_CullFace(GPU_CULL_NONE);

	const C3D_Mtx* proj = chunkRenderProjection();
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, proj);

	// ---- culling setup, done once for the whole pass ------------------------------------
	//
	// The frustum comes out of projection x view, multiplied in the same order the draw uses,
	// so the cull agrees with the rasteriser at the screen edges. Do not re-derive the plane
	// extraction: the PICA's clip z range is [-w,0], not GL's [-w,w], and getting the far
	// plane backwards was measured on this project as culling the entire world.
	C3D_Mtx vp;
	Mtx_Multiply(&vp, proj, view);
	Frustum frustum;
	frustumFromMatrix(&frustum, &vp);

	// Camera position, for the cheap distance reject that runs before the frustum test.
	// A view matrix is R * Translate(-eye) with R orthonormal — scene/camera.c builds
	// RotateX(pitch) * RotateY(yaw) * Translate(-eye), as playermodel.c:298-301 states — so
	// the eye is -R^T applied to the view's translation column. No inverse, no square root,
	// and it holds for as long as nothing puts a scale into the view matrix.
	const float t0 = view->r[0].w, t1 = view->r[1].w, t2 = view->r[2].w;
	const float cam_x = -(view->r[0].x * t0 + view->r[1].x * t1 + view->r[2].x * t2);
	const float cam_y = -(view->r[0].y * t0 + view->r[1].y * t1 + view->r[2].y * t2);
	const float cam_z = -(view->r[0].z * t0 + view->r[1].z * t1 + view->r[2].z * t2);
	(void)cam_y;   // the distance reject is horizontal; see below

	// Squared, against the boundary the fog fades to, so an animal is never popped while it
	// is still visible. Horizontal only: the load boundary is a horizontal radius and a
	// vertical term would cull a sheep on a hilltop the player can plainly see.
	const float cull_r2 = rd->boundary * rd->boundary;

	// ---- the real animals ---------------------------------------------------------------
	//
	// entity.h:259-265's own documented reading pattern, verbatim: entityCount is the
	// early-out, entityGet is the iterator, the Entity's fields are the pose. No draw list,
	// no per-frame copy, no callback from entity/ into scene/.
	for (int i = 0; i < ENTITY_SLOTS; i++) {
		const Entity* e = entityGet(ew, i);
		if (!e)
			continue;
		if (e->kind < ENT_KIND_PIG || e->kind >= ENT_KIND_COUNT)
			continue;   // not an animal — v1.8.16's problem, not this file's

		const float dx = e->body.x - cam_x;
		const float dz = e->body.z - cam_z;
		if (dx * dx + dz * dz > cull_r2)
			continue;

		// The AABB is the model's world extent with yaw ignored: the largest horizontal
		// half-extent is used on both axes, which over-estimates the footprint of a rotated
		// long body and can therefore only ever keep an animal that should have been culled.
		// That costs one draw call; the opposite error erases an animal the player can see.
		// Both numbers come from emKindExtent() over kEmBoxes — not from a second table.
		const int   ki = e->kind - ENT_KIND_PIG;
		const float r  = s_half_horiz[ki];
		if (!frustumTestAABB(&frustum,
		                     e->body.x - r, e->body.y,                e->body.z - r,
		                     e->body.x + r, e->body.y + s_height[ki], e->body.z + r))
			continue;

		// Rotate then translate, which in citro3d's post-multiplying convention means
		// calling Translate before RotateY. The yaw sign is negative for playermodel.c's
		// reason: the view matrix rotates the world by +yaw about Y, so a model authored
		// facing -Z reaches the heading of an entity with yaw y under RotateY(-y).
		C3D_Mtx model, mv;
		Mtx_Identity(&model);
		Mtx_Translate(&model, e->body.x, e->body.y, e->body.z, true);
		Mtx_RotateY(&model, -e->yaw, true);
		Mtx_Multiply(&mv, view, &model);

		// EYE-SPACE DEPTH, not the horizontal distance the cull above used, and not a
		// Euclidean length: -z_eye is what source/shaders/world_dynamic.v.pica feeds the
		// terrain's fog coordinate, and matching it is the whole reason an animal fades on
		// the same curve as the hill behind it. Row 2 of the modelView already holds it —
		// the model matrix's translation column has been carried through the multiply — so
		// this is a read, not a dot product.
		const uint8_t fog_alpha = fogAlphaFor(&fog_shape, -mv.r[2].w);

		drawOne(fog, flat, &mv, e->kind, fog_alpha);
	}

	// ---- P1 probe -----------------------------------------------------------------------
	//
	// Compiled out entirely at the default ENTMODEL_PROBE_N of 0. Built directly in view
	// space — the model matrix IS the modelView — so every animal is in front of the eye and
	// inside the frustum by construction, whatever the player is doing. That is the point:
	// N is the variable, and "how many did the player happen to be looking at" must not be.
#if ENTMODEL_PROBE_N > 0
#if ENTMODEL_PROBE_NODEPTH
	// Visual-check arm only. chunkRenderDraw's pipelineBind re-establishes
	// C3D_DepthTest(true, GPU_GREATER, GPU_WRITE_ALL) at the top of every frame
	// (chunk_render.c:1237), so this heals itself exactly like every other piece of state
	// this file deliberately does not restore.
	C3D_DepthTest(false, GPU_ALWAYS, GPU_WRITE_COLOR);
#endif
	for (int i = 0; i < ENTMODEL_PROBE_N; i++) {
		const int col = i % EM_PROBE_COLS;
		const int row = i / EM_PROBE_COLS;

		C3D_Mtx mv;
		Mtx_Identity(&mv);
		Mtx_Translate(&mv,
		              -3.5f + (float)col * 1.0f,
		              ENTMODEL_PROBE_Y0 + (float)row * 1.0f,
		              ENTMODEL_PROBE_Z, true);

		// Cycled across all four kinds so the pass writes a different TEV constant for every
		// draw, exactly as a real mixed herd would. A probe that drew one colour would let the
		// hardware coalesce state the shipping path never gets to coalesce.
		drawOne(fog, flat, &mv, (uint8_t)(ENT_KIND_PIG + (i & 3)),
		        fogAlphaFor(&fog_shape, -mv.r[2].w));
	}
#endif
}
