#include "scene/highlight.h"

#include "scene/chunk_render.h"   // for the world's projection, which this must match

#include "highlight_shbin.h"   // generated by picasso from source/shaders/highlight.v.pica

// The cage is twelve thin boxes rather than a wireframe because the PICA200 has no line
// primitive — see the file header in highlight.h for the full reasoning. Each box is a
// plain axis-aligned cuboid, six faces of two triangles, so building one is the only
// piece of geometry logic this file needs; the twelve edges are twelve calls to it with
// different bounds.
//
// Position-only vertex, floats rather than the game's 8-byte MeshVertex: the cage has
// no texture and no per-vertex lighting or AO, so there is nothing else to carry per
// vertex, and the geometry needs fractional-block precision (HL_MARGIN below is a few
// thousandths of a block) that an 8-bit attribute cannot represent. Colour comes from a
// TEV constant instead of a vertex attribute, which is also why there is no colour
// field here.
typedef struct {
	float x, y, z;
} HlVertex;

// How far outside the block's own faces the cage sits, in block units. Big enough that
// the cage never z-fights with the block's own triangles at any distance the camera can
// get to a block face; small enough that the cage still reads as "around this block"
// rather than "around roughly this area".
#define HL_MARGIN      0.0015f

// Half-thickness of each bar, in block units. 0.025 total thickness: thin enough to
// read as an outline rather than a fat box, thick enough not to vanish to sub-pixel at
// typical play distance on a 400x240 screen.
#define HL_HALF_THICK  0.0125f

#define HL_BOXES        12
#define HL_TRIS_PER_BOX 12                        // 6 faces * 2 triangles
#define HL_VERTS        (HL_BOXES * HL_TRIS_PER_BOX * 3)   // 432, no index buffer

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;

static HlVertex* s_verts;      // linearAlloc'ed once, rebuilt never
static bool      s_ready;

// Appends one axis-aligned box (six faces, two CCW-from-outside triangles each) to
// verts starting at index vi, and returns the index just past what it wrote.
//
// Winding is derived the same way source/world/mesher.c derives kFaces: each face's
// two triangles are (corner0, corner1, corner2) and (corner0, corner2, corner3) walking
// the corners so that (corner1 - corner0) x (corner3 - corner0) points outward. This is
// only worked out once here, by hand, rather than looked up from kFaces, because kFaces
// lives in world/ (out of scope for this file to touch or depend on) and because a
// box's faces are axis-aligned regardless of which block they cage. Correct winding is
// belt; GPU_CULL_NONE during this draw (see highlightDraw) is the braces, in case a
// corner got transposed somewhere below.
static int addBox(HlVertex* v, int vi, float x0, float y0, float z0,
                   float x1, float y1, float z1)
{
	// +X
	v[vi++] = (HlVertex){x1, y0, z0}; v[vi++] = (HlVertex){x1, y1, z0}; v[vi++] = (HlVertex){x1, y1, z1};
	v[vi++] = (HlVertex){x1, y0, z0}; v[vi++] = (HlVertex){x1, y1, z1}; v[vi++] = (HlVertex){x1, y0, z1};
	// -X
	v[vi++] = (HlVertex){x0, y0, z0}; v[vi++] = (HlVertex){x0, y0, z1}; v[vi++] = (HlVertex){x0, y1, z1};
	v[vi++] = (HlVertex){x0, y0, z0}; v[vi++] = (HlVertex){x0, y1, z1}; v[vi++] = (HlVertex){x0, y1, z0};
	// +Y
	v[vi++] = (HlVertex){x0, y1, z0}; v[vi++] = (HlVertex){x0, y1, z1}; v[vi++] = (HlVertex){x1, y1, z1};
	v[vi++] = (HlVertex){x0, y1, z0}; v[vi++] = (HlVertex){x1, y1, z1}; v[vi++] = (HlVertex){x1, y1, z0};
	// -Y
	v[vi++] = (HlVertex){x0, y0, z0}; v[vi++] = (HlVertex){x1, y0, z0}; v[vi++] = (HlVertex){x1, y0, z1};
	v[vi++] = (HlVertex){x0, y0, z0}; v[vi++] = (HlVertex){x1, y0, z1}; v[vi++] = (HlVertex){x0, y0, z1};
	// +Z
	v[vi++] = (HlVertex){x0, y0, z1}; v[vi++] = (HlVertex){x1, y0, z1}; v[vi++] = (HlVertex){x1, y1, z1};
	v[vi++] = (HlVertex){x0, y0, z1}; v[vi++] = (HlVertex){x1, y1, z1}; v[vi++] = (HlVertex){x0, y1, z1};
	// -Z
	v[vi++] = (HlVertex){x0, y0, z0}; v[vi++] = (HlVertex){x0, y1, z0}; v[vi++] = (HlVertex){x1, y1, z0};
	v[vi++] = (HlVertex){x0, y0, z0}; v[vi++] = (HlVertex){x1, y1, z0}; v[vi++] = (HlVertex){x1, y0, z0};

	return vi;
}

// Fills verts (HL_VERTS long) with the twelve edge boxes of a unit cube expanded by
// HL_MARGIN. For each axis, the edge runs the cube's full length along that axis and
// sits as a thin bar centred on each of the four corners formed by pinning the other
// two axes to the cube's low or high face — the usual "picture frame" cage. Looping
// over axis/low-high like this, rather than typing out twelve boxes by hand, is what
// makes HL_MARGIN and HL_HALF_THICK single-point-of-change constants instead of twelve
// places each.
static void buildCage(HlVertex* verts)
{
	const float lo = -HL_MARGIN;
	const float hi = 1.0f + HL_MARGIN;

	int vi = 0;

	for (int axis = 0; axis < 3; axis++) {
		const int ob1 = (axis + 1) % 3;
		const int ob2 = (axis + 2) % 3;

		for (int hi1 = 0; hi1 < 2; hi1++) {
			for (int hi2 = 0; hi2 < 2; hi2++) {
				const float c1 = hi1 ? hi : lo;
				const float c2 = hi2 ? hi : lo;

				float mn[3], mx[3];
				mn[axis] = lo;              mx[axis] = hi;
				mn[ob1]  = c1 - HL_HALF_THICK; mx[ob1] = c1 + HL_HALF_THICK;
				mn[ob2]  = c2 - HL_HALF_THICK; mx[ob2] = c2 + HL_HALF_THICK;

				vi = addBox(verts, vi, mn[0], mn[1], mn[2], mx[0], mx[1], mx[2]);
			}
		}
	}
}

bool highlightInit(void)
{
	s_dvlb = DVLB_ParseFile((u32*)highlight_shbin, highlight_shbin_size);
	shaderProgramInit(&s_program);
	shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);

	s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
	s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");

	s_verts = (HlVertex*)linearAlloc(sizeof(HlVertex) * HL_VERTS);
	if (!s_verts)
		return false;
	buildCage(s_verts);

	// Built once by the CPU, read from RAM by the GPU. linearAlloc memory is cached, so without
	// this the GPU reads whatever the linear heap held before buildCage ran. See the flush in
	// scene/chunk_render.c's chunkRenderBuild for what a stale read costs.
	GSPGPU_FlushDataCache(s_verts, sizeof(HlVertex) * HL_VERTS);

	s_ready = true;
	return true;
}

void highlightExit(void)
{
	if (s_verts)
		linearFree(s_verts);
	s_verts = NULL;
	s_ready = false;

	shaderProgramFree(&s_program);
	DVLB_Free(s_dvlb);
}

void highlightDraw(const C3D_Mtx* view, const RayHit* hit)
{
	if (!s_ready)
		return;   // failed init degrades to "no highlight", not a crash

	if (!hit->hit)
		return;   // nothing aimed at — hit->x/y/z are zero-initialised, not a real block

	// Nothing here is put back afterwards, deliberately: chunkRenderDraw re-establishes
	// its whole pipeline — program, vertex format, TEV, depth, cull and shade uniforms —
	// at the top of every call, precisely so that a second pass like this one does not
	// have to carry a duplicate copy of the world's state in order to restore it. A copy
	// is what rots; this way there is one owner.
	C3D_BindProgram(&s_program);

	// This module's own attribute layout: one register, three floats, nothing else.
	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(HlVertex), 1, 0x0);

	// Flat constant colour through TEV stage 0, no texture: a dark but not pure black
	// grey, which is what "slightly translucent-looking" is asked to be here without
	// actually enabling the alpha-blend unit (untouched, and left off — see highlight.h
	// and the task notes this file was written against). Channel order in the packed
	// u32 does not matter for this call because R, G and B are all the same value.
	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_CONSTANT, 0, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);
	C3D_TexEnvColor(env, 0xFF202020);

	// Winding should already be correct (see addBox), but the cage is only 144 triangles
	// and a transposed corner would show up as bars missing from one side only, which is
	// an annoying thing to chase. Culling off is cheap insurance at this triangle count.
	C3D_CullFace(GPU_CULL_NONE);

	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, chunkRenderProjection());

	C3D_Mtx model, mv;
	Mtx_Identity(&model);
	Mtx_Translate(&model, (float)hit->x, (float)hit->y, (float)hit->z, true);
	Mtx_Multiply(&mv, view, &model);
	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, &mv);

	C3D_DrawArrays(GPU_TRIANGLES, 0, HL_VERTS);
}
