#include "scene/playermodel.h"

#include <stdio.h>

#include "gfx/font.h"
#include "gfx/fogramp.h"          // the fade's shape, shared with the terrain pass
#include "gfx/fogtex.h"           // the ramp texture on unit 1, owned by gfx/, bound by both
#include "gfx/sprite.h"
#include "net/networld.h"
#include "scene/chunk_render.h"   // for the world's projection, which this must match
#include "world/physics.h"        // PLAYER_WIDTH / PLAYER_HEIGHT — one source of proportions

#include "highlight_shbin.h"   // generated by picasso from source/shaders/highlight.v.pica

// The highlight shader is reused verbatim rather than copied into a playermodel.v.pica of
// its own. It is exactly what this file needs and nothing more — one position attribute,
// a modelView and a projection uniform, colour supplied by the TEV constant — so a second
// shader would be the same forty-five lines of PICA assembly under a different name, with
// the usual consequence that one of the two gets fixed and the other does not. This module
// keeps its own shaderProgram_s and its own uniform locations, so nothing is shared with
// scene/highlight.c at runtime and neither can disturb the other's state.
//
// Position-only float vertices, for the same reasons highlight.c gives: no texture, no
// per-vertex lighting, and dimensions (0.6 blocks wide, 1.8 tall) that an 8-bit attribute
// cannot express.
typedef struct {
	float x, y, z;
} PmVertex;

// Body proportions come from world/physics.h so the box a remote player is drawn as is the
// same size as the box they actually collide with. If PLAYER_WIDTH or PLAYER_HEIGHT is
// ever retuned, the model follows without anyone remembering this file exists.
#define PM_HALF_W     (PLAYER_WIDTH * 0.5f)             // 0.30
#define PM_HEAD_H     0.45f                             // head occupies the top 0.45
#define PM_SHOULDER   (PLAYER_HEIGHT - PM_HEAD_H)       // 1.35, where body ends and head starts
#define PM_HEAD_HALF  0.25f                             // head is slightly narrower than the body

// The nose is not decoration. Yaw arrives in every pose and is applied to the model matrix,
// but a body and a head are both symmetric about their vertical axis, so without something
// that breaks that symmetry a player spinning on the spot looks completely static and the
// facing half of the pose payload is invisible. This is the cheapest thing that makes it
// visible: a small wedge on the head's front face, twelve triangles.
#define PM_NOSE_HALF_W 0.06f
#define PM_NOSE_BOT    1.50f
#define PM_NOSE_TOP    1.62f
#define PM_NOSE_OUT    0.06f                            // how far it protrudes past the head

#define PM_TRIS_PER_BOX 12                              // 6 faces * 2 triangles
#define PM_VERTS_PER_BOX (PM_TRIS_PER_BOX * 3)          // 36

// Body and head are drawn as one range in the player's colour; the nose is a second range
// in a fixed dark tone, because the TEV constant is per-draw-call and a nose the same
// colour as the head is invisible at any distance where it matters.
#define PM_BODY_FIRST  0
#define PM_BODY_COUNT  (2 * PM_VERTS_PER_BOX)           // body + head
#define PM_NOSE_FIRST  PM_BODY_COUNT
#define PM_NOSE_COUNT  PM_VERTS_PER_BOX
#define PM_VERTS       (PM_BODY_COUNT + PM_NOSE_COUNT)  // 108, no index buffer

#define PM_NOSE_COLOUR SPRITE_RGBA(32, 24, 32, 255)

// One palette drives both the body's TEV constant and the name tag's vertex colour, which
// works because gfx/sprite.h's SPRITE_RGBA packs bytes in exactly the order the PICA's TEV
// constant register expects (red in the low byte). Using the macro rather than raw hex
// keeps that coincidence stated instead of silently relied upon, and keeps someone's tag
// the same colour as their body.
//
// Eight entries, picked by the low bits of the sid, so two people standing next to each
// other are usually different colours. Not unique: with sixteen possible players and eight
// colours a collision is ordinary, and the name tag is what actually identifies someone.
static const uint32_t kPlayerColours[8] = {
	SPRITE_RGBA(232,  72,  72, 255),   // red
	SPRITE_RGBA( 72, 232,  72, 255),   // green
	SPRITE_RGBA( 72, 104, 232, 255),   // blue
	SPRITE_RGBA(232, 216,  72, 255),   // yellow
	SPRITE_RGBA( 72, 216, 232, 255),   // cyan
	SPRITE_RGBA(232,  72, 216, 255),   // magenta
	SPRITE_RGBA(240, 160,  64, 255),   // orange
	SPRITE_RGBA(232, 232, 232, 255),   // white
};

static DVLB_s*         s_dvlb;
static shaderProgram_s s_program;
static int             s_uloc_projection;
static int             s_uloc_modelview;
static int             s_uloc_fogparams;

// v1.9.0. The same override scene/chunk_render.c defines, spelled the same way and for the
// same reason: -DFOG_DENSITY=0.0f has to take the fog off the PLAYERS too, or the red arm
// would leave them fading against terrain that no longer fades and the check would be
// measuring two different things. The default expands to the field, so a normal build reads
// exactly what the terrain reads.
#ifndef FOG_DENSITY
#define FOG_DENSITY  (chunkRenderDistance()->fog_density)
#endif

static PmVertex* s_verts;      // linearAlloc'ed once at init, rebuilt never
static bool      s_ready;

// Appends one axis-aligned box, six faces of two triangles each, and returns the index just
// past what it wrote. Winding is CCW seen from outside, worked out the same way and to the
// same convention as scene/highlight.c's addBox — duplicated rather than shared because
// highlight.h does not export it and a box builder is not worth a third module. Culling is
// off during this draw anyway (see playerModelDraw), so a transposed corner would show up
// as a shading oddity rather than a hole.
static int addBox(PmVertex* v, int vi, float x0, float y0, float z0,
                  float x1, float y1, float z1)
{
	// +X
	v[vi++] = (PmVertex){x1, y0, z0}; v[vi++] = (PmVertex){x1, y1, z0}; v[vi++] = (PmVertex){x1, y1, z1};
	v[vi++] = (PmVertex){x1, y0, z0}; v[vi++] = (PmVertex){x1, y1, z1}; v[vi++] = (PmVertex){x1, y0, z1};
	// -X
	v[vi++] = (PmVertex){x0, y0, z0}; v[vi++] = (PmVertex){x0, y0, z1}; v[vi++] = (PmVertex){x0, y1, z1};
	v[vi++] = (PmVertex){x0, y0, z0}; v[vi++] = (PmVertex){x0, y1, z1}; v[vi++] = (PmVertex){x0, y1, z0};
	// +Y
	v[vi++] = (PmVertex){x0, y1, z0}; v[vi++] = (PmVertex){x0, y1, z1}; v[vi++] = (PmVertex){x1, y1, z1};
	v[vi++] = (PmVertex){x0, y1, z0}; v[vi++] = (PmVertex){x1, y1, z1}; v[vi++] = (PmVertex){x1, y1, z0};
	// -Y
	v[vi++] = (PmVertex){x0, y0, z0}; v[vi++] = (PmVertex){x1, y0, z0}; v[vi++] = (PmVertex){x1, y0, z1};
	v[vi++] = (PmVertex){x0, y0, z0}; v[vi++] = (PmVertex){x1, y0, z1}; v[vi++] = (PmVertex){x0, y0, z1};
	// +Z
	v[vi++] = (PmVertex){x0, y0, z1}; v[vi++] = (PmVertex){x1, y0, z1}; v[vi++] = (PmVertex){x1, y1, z1};
	v[vi++] = (PmVertex){x0, y0, z1}; v[vi++] = (PmVertex){x1, y1, z1}; v[vi++] = (PmVertex){x0, y1, z1};
	// -Z
	v[vi++] = (PmVertex){x0, y0, z0}; v[vi++] = (PmVertex){x0, y1, z0}; v[vi++] = (PmVertex){x1, y1, z0};
	v[vi++] = (PmVertex){x0, y0, z0}; v[vi++] = (PmVertex){x1, y1, z0}; v[vi++] = (PmVertex){x1, y0, z0};

	return vi;
}

// Model space: feet at the origin, +Y up, and the front of the model facing -Z. That last
// choice is not arbitrary — it is the direction scene/camera.c's view matrix leaves the
// camera looking down, so a model authored this way and rotated by the same yaw ends up
// pointing where its owner is pointing. See the rotation in playerModelDraw for the sign.
static void buildBody(PmVertex* verts)
{
	int vi = 0;

	// Body, then head — the two that share PM_BODY_FIRST/PM_BODY_COUNT's colour, so they
	// must stay adjacent and stay first.
	vi = addBox(verts, vi, -PM_HALF_W,    0.0f,        -PM_HALF_W,
	                        PM_HALF_W,    PM_SHOULDER,  PM_HALF_W);
	vi = addBox(verts, vi, -PM_HEAD_HALF, PM_SHOULDER, -PM_HEAD_HALF,
	                        PM_HEAD_HALF, PLAYER_HEIGHT, PM_HEAD_HALF);

	// Nose, protruding from the head's -Z face. Starts just inside the head so there is no
	// gap to see through at a grazing angle.
	vi = addBox(verts, vi, -PM_NOSE_HALF_W, PM_NOSE_BOT, -PM_HEAD_HALF - PM_NOSE_OUT,
	                        PM_NOSE_HALF_W, PM_NOSE_TOP, -PM_HEAD_HALF + 0.02f);

	(void)vi;   // PM_VERTS is asserted below; this silences an unused-value warning
}

_Static_assert(PM_VERTS == 108, "three boxes of twelve triangles");

// The label under which a remote player appears, both here and in the multiplayer menu's
// list. Derived from the low sixteen bits of the session id because the server never sends
// a name to clients — bsgame has no roster message — so a sid-derived tag is the honest
// placeholder. The format is deliberately identical to the one net/bsnet.c builds its
// player list from, so the tag over someone's head and the entry on the Multiplayer screen
// read the same.
static void playerLabel(char* out, size_t cap, uint32_t sid)
{
	snprintf(out, cap, "Player %04x", (unsigned)(sid & 0xffffu));
}

// One shader program for the whole process, built the first time and never torn down. Same
// reasoning as scene/highlight.c: playerModelInit/playerModelExit run per session, and freeing
// and rebuilding this static across a rejoin is the citro3d use-after-free that hard-crashes
// the console. The vertex buffer below is still freed per session; only the shader is permanent.
static bool s_shader_ready;

bool playerModelInit(void)
{
	if (!s_shader_ready) {
		s_dvlb = DVLB_ParseFile((u32*)highlight_shbin, highlight_shbin_size);
		if (!s_dvlb)
			return false;
		shaderProgramInit(&s_program);
		shaderProgramSetVsh(&s_program, &s_dvlb->DVLE[0]);

		s_uloc_projection = shaderInstanceGetUniformLocation(s_program.vertexShader, "projection");
		s_uloc_modelview  = shaderInstanceGetUniformLocation(s_program.vertexShader, "modelView");
		s_uloc_fogparams  = shaderInstanceGetUniformLocation(s_program.vertexShader, "fogParams");
		s_shader_ready = true;
	}

	s_verts = (PmVertex*)linearAlloc(sizeof(PmVertex) * PM_VERTS);
	if (!s_verts)
		return false;
	buildBody(s_verts);

	// Built once by the CPU, read from RAM by the GPU every frame another player is on screen.
	// linearAlloc memory is cached, so without this the GPU reads whatever the linear heap held
	// before buildBody ran. Same defect, same fix, same consequence as the flush in
	// scene/chunk_render.c's chunkRenderBuild — which is what froze real consoles up to v1.1.8.
	GSPGPU_FlushDataCache(s_verts, sizeof(PmVertex) * PM_VERTS);

	s_ready = true;
	return true;
}

void playerModelExit(void)
{
	if (s_verts)
		linearFree(s_verts);
	s_verts = NULL;
	s_ready = false;

	// The shader is deliberately not freed here — see s_shader_ready above.
}

void playerModelDraw(const C3D_Mtx* view)
{
	if (!s_ready)
		return;   // failed init degrades to "nobody is drawn", not a crash

	const int count = networldRemoteCount();
	if (count <= 0)
		return;   // single player, or nobody else has sent a pose yet

	// Nothing set here is put back afterwards, deliberately — see playermodel.h and the
	// same note in scene/highlight.c. chunkRenderDraw re-establishes its entire pipeline
	// at the top of every call, so one owner of that state is better than two copies.
	C3D_BindProgram(&s_program);

	C3D_AttrInfo* attr = C3D_GetAttrInfo();
	AttrInfo_Init(attr);
	AttrInfo_AddLoader(attr, 0, GPU_FLOAT, 3);

	C3D_BufInfo* buf = C3D_GetBufInfo();
	BufInfo_Init(buf);
	BufInfo_Add(buf, s_verts, sizeof(PmVertex), 1, 0x0);

	C3D_TexEnv* env = C3D_GetTexEnv(0);
	C3D_TexEnvInit(env);
	C3D_TexEnvSrc(env, C3D_Both, GPU_CONSTANT, 0, 0);
	C3D_TexEnvFunc(env, C3D_Both, GPU_REPLACE);

	// v1.9.0. TEV stage 1 and the fog unit, both explicitly OWNED here instead of inherited.
	// See the same block in scene/highlight.c for the pre-existing leak this closes.
	//
	// This is the one pass of the four that genuinely WANTS the fade. Player bodies were fogged
	// before v1.9.0, though by accident rather than design — the hardware fog unit the world
	// pass left switched on applied to them too — and unlike the cage and the crack overlay a
	// player can be at any distance, so a distant one really did fade toward the sky. Dropping
	// that with the fixed-function unit would have been a regression, and a conspicuous one at
	// this version's render distances: half-visibility moves from 14.34 blocks to 28.5 at
	// radius 3 and 47.5 at radius 5, so there is far more depth in which a player can stand at
	// full contrast against terrain that is fading out behind them.
	//
	// So the fade is reproduced deliberately, on the SAME curve rather than on a similar one:
	// source/shaders/highlight.v.pica now emits the identical fog coordinate world_dynamic
	// does, this binds the same ramp texture, and the uniform below is built by the same
	// fogShapeFor() from the same boundary. One curve, three call sites, no drift.
	fogTexBind();

	C3D_TexEnv* fog = C3D_GetTexEnv(1);
	C3D_TexEnvInit(fog);
	C3D_TexEnvSrc(fog, C3D_RGB, GPU_CONSTANT, GPU_PREVIOUS, GPU_TEXTURE1);
	C3D_TexEnvOpRgb(fog, GPU_TEVOP_RGB_SRC_COLOR, GPU_TEVOP_RGB_SRC_COLOR,
	                GPU_TEVOP_RGB_SRC_ALPHA);
	C3D_TexEnvFunc(fog, C3D_RGB, GPU_INTERPOLATE);
	// Alpha is passed through untouched. Stage 0 replaced it with the player-colour constant's
	// alpha and the blend unit is off in this pass, but writing it explicitly keeps the stage
	// from inheriting an alpha combiner from whatever ran before it.
	C3D_TexEnvSrc(fog, C3D_Alpha, GPU_PREVIOUS, 0, 0);
	C3D_TexEnvFunc(fog, C3D_Alpha, GPU_REPLACE);
	C3D_TexEnvColor(fog, SKY_FOG_BGR | 0xFF000000u);

	// The hardware unit stays off. It is not a second opinion about the same fade — its LUT is
	// indexed by 1/w and is the exact ceiling this version exists to remove — so leaving it on
	// would fog these bodies twice, once on the new curve and once on the old broken one.
	C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);

	// chunkRenderDistance() is documented never-NULL in scene/chunk_render.h. Read every draw
	// rather than cached at init, because chunkRenderSetDistance() can change the radius at
	// runtime and a cached shape would fade players on the previous render distance's curve.
	const FogShape pm_fog = fogShapeFor(chunkRenderDistance()->boundary, FOG_DENSITY);
	C3D_FVUnifSet(GPU_VERTEX_SHADER, s_uloc_fogparams,
	              pm_fog.inv_range, pm_fog.bias, 0.0f, 0.0f);

	// Culling off, matching highlightDraw: 36 triangles per player against at most fifteen
	// players is not a triangle count worth risking a hand-derived winding over.
	C3D_CullFace(GPU_CULL_NONE);

	C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_projection, chunkRenderProjection());

	for (int i = 0; i < count; i++) {
		NetworldRemote r;
		if (!networldRemoteGet(i, &r))
			continue;   // aged out between the count above and here; skip, do not stop

		// Rotate first, then translate, which in citro3d's post-multiplying convention
		// means calling Translate before RotateY: each call composes onto the right of
		// what is already in the matrix, so the last one applied is the innermost.
		//
		// The sign is negative because the view matrix rotates the *world* by +yaw about
		// Y (scene/camera.c builds RotateX(pitch) * RotateY(yaw) * Translate(-eye)), so
		// the direction a player with yaw y is looking is (sin y, 0, -cos y) in world
		// space. A model authored facing -Z reaches that heading under RotateY(-yaw).
		// Pitch is received and deliberately not applied: tilting a whole rigid body to
		// look at the sky is worse than not tilting it, and there is no neck to tilt yet.
		C3D_Mtx model, mv;
		Mtx_Identity(&model);
		Mtx_Translate(&model, r.x, r.y, r.z, true);
		Mtx_RotateY(&model, -r.yaw, true);
		Mtx_Multiply(&mv, view, &model);
		C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, s_uloc_modelview, &mv);

		// C3D_TexEnvColor is a plain write into citro3d's shadow copy of the TEV stage
		// (c3d/texenv.h) — it does not mark that copy dirty, and only C3D_GetTexEnv and
		// C3D_DirtyTexEnv do. Without the explicit dirty call the register is uploaded
		// once, on the first draw, and every player after the first is drawn in the first
		// one's colour. That is a bug that looks exactly like a working palette until two
		// people are on screen at once, which is why it is spelled out here.
		C3D_TexEnvColor(env, kPlayerColours[r.sid & 7u]);
		C3D_DirtyTexEnv(env);
		C3D_DrawArrays(GPU_TRIANGLES, PM_BODY_FIRST, PM_BODY_COUNT);

		C3D_TexEnvColor(env, PM_NOSE_COLOUR);
		C3D_DirtyTexEnv(env);
		C3D_DrawArrays(GPU_TRIANGLES, PM_NOSE_FIRST, PM_NOSE_COUNT);
	}
}

// How far above the top of the head the tag floats, in blocks.
#define PM_TAG_LIFT 0.35f

// Anything closer to the camera than this along the view axis is treated as behind it. Not
// zero: a w that small has already lost all its precision to the perspective divide, and a
// tag whipping across the screen as someone walks through the camera plane looks like a
// bug.
#define PM_TAG_MIN_W 0.05f

void playerModelDrawTags(const C3D_Mtx* view, float scr_w, float scr_h)
{
	if (!s_ready)
		return;

	const int count = networldRemoteCount();
	if (count <= 0)
		return;

	// One combined matrix for the whole batch rather than per player: the projection and
	// the view are the same for everyone on this eye.
	C3D_Mtx vp;
	Mtx_Multiply(&vp, chunkRenderProjection(), view);

	// The batch is opened even if every tag turns out to be off screen. Opening it is a
	// handful of register writes, and the alternative — deferring the batch until the
	// first visible tag — means the projection loop below has to run twice or buffer its
	// results, for no measurable gain at fifteen players.
	spriteBegin((int)scr_w, (int)scr_h);

	// fontDraw does not bind the font texture itself (see gfx/font.h) — it is left to the
	// caller so text and panels can share one batch without a flush between them. This
	// batch is text only, so one bind up front covers all of it.
	spriteTexture(fontTexture());

	for (int i = 0; i < count; i++) {
		NetworldRemote r;
		if (!networldRemoteGet(i, &r))
			continue;

		C3D_FVec world = FVec4_New(r.x, r.y + PLAYER_HEIGHT + PM_TAG_LIFT, r.z, 1.0f);
		C3D_FVec clip  = Mtx_MultiplyFVec4(&vp, world);

		if (clip.w < PM_TAG_MIN_W)
			continue;   // behind the camera, or on top of it

		const float inv_w = 1.0f / clip.w;
		const float ndc_x = clip.x * inv_w;
		const float ndc_y = clip.y * inv_w;

		// Both chunkRenderProjection()'s matrix and the sprite batch's own come from
		// citro3d's *Tilt variants, which post-multiply by the quarter-turn that accounts
		// for the 3DS framebuffer being stored rotated 90 degrees. That fix-up maps
		// (x, y) to (y, -x), and gfx/sprite.c builds its ortho with left/right = 0/w and
		// bottom/top = h/0 for a top-left origin. Composing and inverting the two gives
		// the mapping below, which is what turns clip space back into the same pixel
		// coordinates fontDraw takes.
		//
		// Derived on paper, so it is checked on screen: a tag that lands rotated or
		// mirrored relative to its body means this is wrong, and it is obvious at a
		// glance the first time two players stand in front of each other.
		const float sx = scr_w * (1.0f - ndc_y) * 0.5f;
		const float sy = scr_h * (1.0f - ndc_x) * 0.5f;

		char label[16];
		playerLabel(label, sizeof label, r.sid);

		// Centred on the body rather than left-aligned at it, so the tag stays over the
		// player instead of drifting off one shoulder.
		const float half = (float)fontTextWidth(label, 1) * 0.5f;
		if (sx + half < 0.0f || sx - half > scr_w || sy < 0.0f || sy > scr_h)
			continue;   // off screen; projecting it was cheap, drawing it would not be

		fontDraw(sx - half, sy, 1, kPlayerColours[r.sid & 7u], label);
	}

	spriteEnd();
}
