#!/usr/bin/env python3
"""Draws Blocksmith's block texture atlas from scratch.

Every tile here is generated by this script — nothing is traced, sampled or
copied from another game. The palette is deliberately its own: cooler greens and
a redder soil than the obvious reference, so the look reads as Blocksmith's.

Layout (v1.6.0 task 11 prerequisite): a ONE-TILE-WIDE STRIP. 16 px wide by
256 px tall, 16 tile slots of 16x16 stacked vertically, no padding anywhere.
Was a 128x128 sheet holding a 6x6 grid of 20x20 cells (16px of art inside a 2px
edge-extended border) up to v1.5.1.

Why the strip. Greedy meshing merges N co-planar faces into one quad, and that
quad needs the tile to REPEAT N times across it. On a packed grid it cannot:
stone's tile sat at atlas u 62..78, so a merge two blocks wide reached u 86,
which is sand. GPU_REPEAT did not help either, because the repeat period was the
whole 128px sheet — eight tiles, not one. With the sheet exactly one tile wide,
GPU_REPEAT in U has a period of exactly one tile, so u can run as far as a merge
needs and every block of the run shows a complete, correct tile. V is still
GPU_CLAMP_TO_EDGE and merging stays U-only: extending v walks into the next
slot, and that limit is accepted.

Why the 2px border is gone. Its job was stopping a neighbouring cell bleeding in
under GPU_NEAREST. In U there is no longer a neighbour at all — REPEAT wraps the
tile onto itself. In V the tiles are now directly adjacent with no gutter, which
would matter if the texture had a mip chain, because a mip level averages across
the boundary. It does not: gfx/atlas.t3s passes tex3ds only "-f rgba5551 -z auto"
with no -m/--mipmap, and the built build/atlas.t3x carries mipmapLevels = 0 in
its header (measured, byte 5 of the file). source/gfx/atlas.c also asks for
GPU_NEAREST on both the min and the mag filter, which is not a mipmapped filter
mode, so no level beyond the base is ever sampled.

Why 16 slots but only 15 addressable. MeshVertex.u/v are uint8_t (the format is
locked — see source/world/mesh_vertex.h), so a tile's TOP edge v1 must fit in
255. The topmost slot in texture space would need v1 = 256, which does not fit,
so slot 15 is left unaddressable. TILES holds 12, so there are 3 spare
addressable slots — 12 and 13, plus the reserved MARKER_SLOT 14, which is not
really spare at all. The next step up is a 16x512 sheet: 32 slots, 31
addressable, 16 KB of VRAM instead of 8 KB.

Why every unused slot is painted (v1.6.0 F7). It used to be left at the sheet's
background fill, and that was a defect: tex 10..14 address REAL, addressable
slots, so a block declared with one drew an opaque near-black solid. On a 240px
screen that reads as a dark block, not as an error. The block registry lets a
SERVER define block types over the wire, so a server shipping a wrong or
unsupported tex looked like a Blocksmith rendering bug instead of a server
misconfiguration — and this project has already lost days to exactly that, since
a wrong texture constant still renders *a* texture and never raises anything.

So every slot TILES does not fill — 12..14 today, and the unaddressable 15 as
well — is painted with tile_missing()'s magenta/black quadrant checker before art
goes down. Those spares are not wasted by this: the marker is simply the DEFAULT
content of an unclaimed slot, and each one gets overwritten by real art as TILES
grows. MARKER_SLOT (14) is the one exception and stays a marker forever, which
is what source/world/atlas_uv.h's ATLAS_TILE_MISSING clamps out-of-range tile ids
onto. It is the TOP of the addressable range on purpose: that is the last slot a
growing TILES list would ever reach, so reserving it costs nothing until the
sheet is full anyway, and place() refuses to paint art into it rather than
leaving the reservation as a comment somebody can walk past.

Slot order runs BOTTOM-UP in this PNG. Texture space has v growing upwards while
the PNG's rows run downwards, so tile 0 — which occupies texture rows 0..16, the
bottom of the sheet — is written to the LAST 16 PNG rows. See atlasRect() in
source/world/atlas_uv.h, which is the one definition of this arithmetic.

Nothing about the art changes. Every tile is drawn by the same painter from the
same seeded stream in the same TILES order and comes out pixel for pixel
identical; only its position on the sheet moves.

The three copies of the sheet size — here, ATLAS_W_PX/ATLAS_H_PX in
source/world/atlas_uv.h and the uvScale constant in source/shaders/world.v.pica
and source/shaders/world_dynamic.v.pica — must move together. A mismatch
re-textures every face in the game rather than failing loudly;
source/world/atlas_uv_shader_test.c is what makes the duplication safe.

Re-run after editing:
    python tools/make_atlas.py
"""

from __future__ import annotations

import random
from pathlib import Path

from PIL import Image

TILE_PX = 16
ATLAS_W_PX = TILE_PX             # exactly one tile wide, so GPU_REPEAT's U period is one tile
ATLAS_H_PX = 256                 # 16 slots; both dimensions must stay powers of two
SLOTS = ATLAS_H_PX // TILE_PX    # 16
# The top slot in texture space would need v1 = 256, which does not fit in MeshVertex's
# uint8_t v. So it is never addressed and never painted. Mirrors ATLAS_TILE_SLOTS in
# source/world/atlas_uv.h.
ADDRESSABLE_SLOTS = SLOTS - 1    # 15
# The slot reserved for the missing-texture marker, forever. Mirrors ATLAS_TILE_MISSING in
# source/world/atlas_uv.h, which is where out-of-range tile ids clamp to. place() refuses to
# paint art here, so TILES may fill 0..MARKER_SLOT-1 and no further.
MARKER_SLOT = ADDRESSABLE_SLOTS - 1   # 14

# Tile slot indices. These are the numbers the C side uses, so the order here is
# the contract — append, never reorder.
TILES = [
    "grass_top",
    "grass_side",
    "dirt",
    "stone",
    "sand",
    "sentinel",
    # Step 5.3's trees. Appended after the sentinel rather than next to sand,
    # because the order above is the contract with the C side and inserting
    # would silently re-texture every tile after the insertion point. The
    # sentinel is still adjacent to real art on both sides, so it goes on
    # doing its job.
    "wood_side",
    "wood_top",
    "leaves",
    # The first crafted block: one wood log makes four planks (world/crafting.c).
    # Appended, like the trees were, because the order above is the contract with
    # the C side. This is the tile that forced the sheet from 64x64 to 128x128 —
    # there was no tenth cell.
    "planks",
    # Roadmap tasks 17 and 19. Appended for the same reason everything since the
    # sentinel has been: this order is the contract with the C side (gfx/atlas.h's
    # TILE_* enum and world/block.h's BTEX_* mirror of it), and inserting would
    # silently re-texture every tile after the insertion point.
    #
    # These claim slots 10 and 11 of the four that were free (10..13). 12 and 13
    # stay as the missing-texture marker, which is what an unclaimed slot is
    # supposed to look like, and MARKER_SLOT (14) cannot be claimed at all.
    "water",
    "tall_grass",
]


def blend(a, b, t):
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))


def speckle(rng, size, shades, weights=None):
    """A flat field of randomly chosen shades — the base of most tiles."""
    img = Image.new("RGB", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(size):
            px[x, y] = rng.choices(shades, weights=weights)[0] if weights else rng.choice(shades)
    return img


def tile_grass_top(rng):
    greens = [(58, 112, 74), (66, 126, 82), (74, 138, 90), (50, 100, 66)]
    img = speckle(rng, TILE_PX, greens, weights=[4, 3, 2, 3])
    px = img.load()
    # A few brighter blades so the surface has some direction to it.
    for _ in range(18):
        x = rng.randrange(TILE_PX)
        y = rng.randrange(TILE_PX)
        px[x, y] = (88, 152, 100)
    return img


def tile_dirt(rng):
    browns = [(108, 72, 50), (96, 63, 44), (120, 82, 58), (86, 56, 40)]
    img = speckle(rng, TILE_PX, browns, weights=[4, 3, 2, 2])
    px = img.load()
    # Small pebbles: a two-tone dot, lit from the top left.
    for _ in range(7):
        x = rng.randrange(1, TILE_PX - 1)
        y = rng.randrange(1, TILE_PX - 1)
        px[x, y] = (138, 100, 74)
        px[x, y + 1] = (74, 48, 34)
    return img


def tile_grass_side(rng):
    img = tile_dirt(rng)
    px = img.load()
    greens = [(58, 112, 74), (66, 126, 82), (74, 138, 90)]
    # An irregular crust rather than a straight line — the depth of the green
    # varies per column, which is what stops a cube looking stamped.
    for x in range(TILE_PX):
        depth = 3 + rng.randrange(3)
        for y in range(depth):
            px[x, y] = rng.choice(greens)
        px[x, depth] = blend(rng.choice(greens), (96, 63, 44), 0.55)
    return img


def tile_stone(rng):
    greys = [(112, 118, 128), (102, 108, 118), (122, 128, 138), (94, 100, 110)]
    img = speckle(rng, TILE_PX, greys, weights=[4, 3, 2, 2])
    px = img.load()
    # Two short cracks, each a darker run walking downwards.
    for _ in range(2):
        x = rng.randrange(2, TILE_PX - 2)
        y = rng.randrange(1, TILE_PX - 6)
        for step in range(rng.randrange(4, 7)):
            px[max(0, min(TILE_PX - 1, x)), min(TILE_PX - 1, y + step)] = (78, 84, 94)
            x += rng.choice((-1, 0, 0, 1))
    return img


def tile_sand(rng):
    sands = [(214, 196, 148), (206, 186, 138), (222, 206, 160), (198, 178, 132)]
    return speckle(rng, TILE_PX, sands, weights=[4, 3, 2, 2])


def tile_wood_side(rng):
    """Bark: vertical grain, greyer and darker than dirt so a trunk reads as a
    trunk against the soil it stands in rather than as a column of it."""
    barks = [(92, 66, 44), (80, 57, 38), (104, 76, 52), (70, 50, 34)]
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    # Grain runs in columns, each column keeping one shade for a few pixels at a
    # time — a per-pixel speckle would read as noise, not bark.
    for x in range(TILE_PX):
        y = 0
        while y < TILE_PX:
            shade = rng.choices(barks, weights=[4, 3, 2, 2])[0]
            run = 2 + rng.randrange(5)
            for dy in range(run):
                if y + dy < TILE_PX:
                    px[x, y + dy] = shade
            y += run
    # Two deep grooves, full height, one pixel wide, so the cylinder reads at a
    # distance where the grain itself has blurred away.
    for x in (rng.randrange(2, 7), rng.randrange(9, 14)):
        for y in range(TILE_PX):
            px[x, y] = (58, 41, 28)
    return img


def tile_wood_top(rng):
    """The cut end: rings around an off-centre heart."""
    pale = (150, 116, 80)
    ring = (112, 84, 56)
    dark = (86, 62, 42)
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    cx = 7.5 + rng.uniform(-1.2, 1.2)
    cy = 7.5 + rng.uniform(-1.2, 1.2)
    for y in range(TILE_PX):
        for x in range(TILE_PX):
            d = ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5
            # Concentric bands two pixels apart, jittered so they are not perfect
            # circles — a clean bullseye looks machined.
            band = int(d + rng.uniform(-0.35, 0.35)) // 2
            px[x, y] = ring if band % 2 else pale
            if d > 7.4:
                px[x, y] = dark          # bark seen edge-on, framing the cut
    return img


def tile_leaves(rng):
    """Cutout canopy — step 7.5. Returns RGBA, and the holes are real alpha 0
    rather than dark pixels, so the transparent pass has something to key on.

    Alpha is 0 or 255 and never in between: the draw uses an alpha *test*, not
    blending, so a half-transparent pixel would not come out half-visible — it
    would land on one side of the threshold and look like a mistake.
    """
    leaf = [(38, 82, 52), (46, 96, 60), (30, 68, 44), (54, 110, 68)]
    img = speckle(rng, TILE_PX, leaf, weights=[4, 3, 3, 2]).convert("RGBA")
    px = img.load()
    # Clumps: a 2x2 of one shade, which is what stops the tile reading as static.
    for _ in range(12):
        x = rng.randrange(TILE_PX - 1)
        y = rng.randrange(TILE_PX - 1)
        shade = rng.choice(leaf) + (255,)
        for dy in range(2):
            for dx in range(2):
                px[x + dx, y + dy] = shade
    # Gaps. Singles scattered through, plus a few 2x1 tears, so the canopy breaks
    # up at more than one scale — a field of isolated single pixels reads as noise
    # on a 240p screen rather than as foliage.
    hole = (0, 0, 0, 0)
    for _ in range(24):
        px[rng.randrange(TILE_PX), rng.randrange(TILE_PX)] = hole
    for _ in range(6):
        x = rng.randrange(TILE_PX - 1)
        y = rng.randrange(TILE_PX)
        px[x, y] = hole
        px[x + 1, y] = hole
    # The tile's own border stays opaque. This used to be because place() edge-extended
    # the tile into a 2px padding ring, and a transparent edge pixel would be smeared
    # outward into a neighbour's sample. The padding is gone with the strip layout, and
    # the loop matters MORE now, not less: slots are directly adjacent in V, so a
    # transparent row at the very top or bottom of this tile sits one texel from the next
    # tile's art with nothing in between. The pixels this produces are unchanged.
    for i in range(TILE_PX):
        for x, y in ((i, 0), (i, TILE_PX - 1), (0, i), (TILE_PX - 1, i)):
            r, g, b, a = px[x, y]
            px[x, y] = (rng.choice(leaf) + (255,)) if a == 0 else (r, g, b, 255)
    return img


def tile_planks(rng):
    """Sawn boards — four horizontal planks with a dark seam between each.

    Deliberately distinct from wood_side at a glance on a 240p screen, because a
    log and its planks sit next to each other in the hotbar and reading them apart
    is the whole point of the block. Three things separate them: planks are paler
    and yellower than the log's bark, the grain runs the full width of a board
    instead of top to bottom, and the seams are horizontal where the log's are
    vertical. Shape, not just colour — the screen is small and the palette is only
    5 bits a channel.

    The board rows are 4px, so the tile tiles seamlessly against itself vertically:
    16 is a whole number of boards, and the seam sits at the top of each one rather
    than being centred, so two stacked blocks read as a continuous wall.
    """
    base = (168, 132, 88)
    warm = (182, 146, 100)
    cool = (150, 116, 78)
    seam = (96, 70, 46)

    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    board_h = 4
    for y in range(TILE_PX):
        # Each board gets its own slight tint, so four identical stripes do not
        # read as a printed pattern.
        board = y // board_h
        tint = blend(cool, warm, (board * 0.31 + 0.15) % 1.0)
        for x in range(TILE_PX):
            px[x, y] = tint if rng.random() < 0.55 else blend(tint, base, 0.5)

    # Grain: horizontal streaks a couple of pixels long, kept inside one board so
    # a streak never crosses a seam.
    for _ in range(22):
        board = rng.randrange(TILE_PX // board_h)
        y = board * board_h + rng.randrange(1, board_h)
        x = rng.randrange(TILE_PX - 3)
        shade = blend(px[x, y], seam, rng.uniform(0.18, 0.34))
        for dx in range(rng.randint(2, 4)):
            if x + dx < TILE_PX:
                px[x + dx, y] = shade

    # Seams. The top row of every board, jittered one pixel here and there so the
    # line is a joint between two sawn boards and not a ruled edge. Blended well
    # back toward the board colour rather than laid down as flat `seam`: at full
    # strength four hard dark lines 4px apart read as mortar courses, and the tile
    # came out looking like brickwork instead of a floor.
    for board in range(TILE_PX // board_h):
        y = board * board_h
        for x in range(TILE_PX):
            t = 0.62 if rng.random() < 0.88 else 0.40
            px[x, y] = blend(px[x, y], seam, t)

    # Butt joints: where two boards meet end to end. Only two of the four rows get
    # one, on opposite sides of the tile, for the same reason — a vertical break in
    # every row on a 4px pitch is a running bond, i.e. bricks. Two sparse joints
    # read as long boards that happen to be spliced.
    for board in (1, 3):
        x = 4 if board == 1 else 11
        for y in range(board * board_h + 1, (board + 1) * board_h):
            px[x, y] = blend(px[x, y], seam, 0.45)

    return img


def tile_water(rng):
    """Open water — roadmap task 17. Returns RGB, i.e. FULLY OPAQUE, and that is a
    decision rather than an oversight.

    The pass this block draws in is an alpha TEST, not alpha blending (see
    tile_leaves and source/gfx/atlas.c). RGBA5551 carries one bit of alpha, so a
    texel is either drawn or it is not and there is no value that comes out
    half-visible. Punching a dither of alpha-0 holes through the surface — the usual
    1-bit trick — would show the seabed through a stipple, and at 16x16 on a 240px
    screen a stipple reads as holes in the water, not as depth. So the surface is
    solid and the only depth cue is the art.

    The swell repeats on an 8px pitch, so the tile is seamless against itself in both
    directions: 16 px is exactly two swells. That matters more for this tile than for
    any other in the sheet. An ocean is the largest co-planar run greedy meshing will
    ever be handed, and GPU_REPEAT tiles this art up to ATLAS_MAX_MERGE_BLOCKS (15)
    times across a single quad — anything that reads as a ruled line here becomes a
    240 px ruler out there, which is why the glints below are broken into dashes for
    the same reason tools/make_atlas.py's planks seams are jittered.

    Blues, and no green in them: grass_top's greens sit at (58,112,74) and up, and a
    teal sea next to a green field on a 5-bit-per-channel sheet is two shades of the
    same thing. These are unambiguously blue.
    """
    trough = (26, 62, 118)
    base   = (36, 80, 140)
    crest  = (56, 112, 172)
    glint  = (112, 172, 212)

    # One swell, eight rows tall. Every step is at least 8 apart in some channel,
    # which is what it takes to survive RGBA5551's five bits — a smaller step is
    # quantised away and the band simply disappears (see the note in
    # tools/run_host_tests.sh about a 132 -> 133 sand edit the format swallowed).
    swell = [crest, crest, base, base, trough, trough, base, base]

    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    for y in range(TILE_PX):
        shade = swell[y % 8]
        # Mostly the row's own step, occasionally the one above it. A flat band per
        # row reads as a striped flag and per-pixel noise reads as static; mixing two
        # ADJACENT steps softens the edge without inventing a third colour the
        # quantiser would round back onto one of them anyway.
        above = swell[(y - 1) % 8]
        for x in range(TILE_PX):
            px[x, y] = shade if rng.random() < 0.78 else above

    # Glints riding the two crest rows: short bright dashes with gaps, never a
    # continuous line. Both rows are crest rows of the 8px swell, so this stays
    # seamless vertically.
    for crest_y in (0, 8):
        x = rng.randrange(4)
        while x < TILE_PX:
            for dx in range(2 + rng.randrange(3)):
                if x + dx < TILE_PX:
                    px[x + dx, crest_y] = glint
            x += 5 + rng.randrange(5)
    return img


def tile_tall_grass(rng):
    """Tall grass — roadmap task 19, and the first tile drawn for a BLOCK_SHAPE_CROSS
    block. Returns RGBA and is MOSTLY alpha 0.

    That is the whole point of it. A cross is two quads on the cell's diagonals
    (world/mesher.c's emitCross), so whatever is opaque in this tile is what the plant
    is; if the tile were opaque everywhere the block would render as two solid cards
    standing in an X, which is not a plant, it is a signpost. Alpha is 0 or 255 and
    never between, exactly as tile_leaves needs it to be and for the same reason: the
    draw is an alpha test, so a middling value lands on one side of the threshold and
    looks like a mistake either way.

    Deliberately NOT following tile_leaves' keep-the-border-opaque rule. Leaves does
    that because it is a full cube whose silhouette is the cell, so a transparent edge
    row costs nothing and buys a margin. A cross has no silhouette but its own art: an
    opaque border would draw a rectangle around every clump of grass in the world.
    Nothing bleeds in from the neighbouring slot regardless — gfx/atlas.c asks for
    GPU_NEAREST on both filters and the sheet carries no mip chain, so the only texels
    ever sampled are the ones inside this tile's own half-open rect.

    Image row 0 is the TOP of the block face (place() blits this image as-is into the
    slot, and slot_png_y() is what applies the sheet-wide V flip), so the blades are
    rooted on the last row and grow upwards.
    """
    blades = [(72, 132, 68), (86, 150, 78), (58, 112, 58)]
    tip    = (126, 184, 100)

    img = Image.new("RGBA", (TILE_PX, TILE_PX), (0, 0, 0, 0))
    px = img.load()

    # Roots spread evenly across the tile rather than scattered at random. A random
    # scatter leaves bare columns, and 16 px is too small to afford one: the X is seen
    # from every horizontal angle, so a gap that happens to line up with a viewing
    # direction reads as a hole in the plant rather than as a gap between blades.
    for root in range(1, TILE_PX, 2):
        x      = root
        height = 7 + rng.randrange(8)          # 7..14 of the 16 rows
        shade  = rng.choice(blades)
        top_y  = TILE_PX - 1
        for step in range(height):
            y = TILE_PX - 1 - step
            top_y = y
            px[x, y] = shade + (255,)
            # Two px wide for the first couple of rows, so the blade has a base. A
            # blade that is one pixel wide all the way down is a hair at 240p, and on
            # a cross that hair is the entire block near the ground.
            if step < 2 and x + 1 < TILE_PX:
                px[x + 1, y] = shade + (255,)
            # Lean: at most one column per row, so a blade curves instead of kinking.
            if step >= 2 and rng.random() < 0.34:
                x = max(0, min(TILE_PX - 1, x + rng.choice((-1, 1))))
        px[x, top_y] = tip + (255,)
    return img


def tile_sentinel(_rng):
    """Not art — a bleed alarm.

    This sits immediately next to the tiles the cube actually uses. If UVs or
    padding are ever wrong, magenta appears on a block face and the bug is
    unmissable instead of subtle.
    """
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    for y in range(TILE_PX):
        for x in range(TILE_PX):
            px[x, y] = (255, 0, 255) if ((x // 2 + y // 2) % 2 == 0) else (0, 0, 0)
    return img


def tile_missing(_rng):
    """Not art — the missing-texture marker.

    Every slot TILES does not fill gets this, and source/world/atlas_uv.h's
    atlasRect() clamps out-of-range tile ids onto MARKER_SLOT. Before v1.6.0 F7
    both cases drew something plausible instead: an unpainted slot drew the
    sheet's near-black background fill, and an out-of-range id drew grass.

    Magenta and black in half-tile quadrants — the same two colours as
    tile_sentinel() but at 8px instead of 2px, deliberately. The sentinel is a
    BLEED alarm and exists to be sampled by accident; if the two looked alike,
    one magenta face would mean either "the UVs bled" or "this texture does not
    exist", which is two different bugs wearing one face. At 16x16 on a 240px
    screen a 2px checker blurs to flat pink while four half-tile quadrants stay
    four blocks, so they are told apart on sight.

    Takes no randomness, and that is load-bearing: the ten painted tiles are
    drawn from one seeded stream in TILES order, so a marker that pulled from it
    would shift every tile after it and silently change the art.
    """
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    half = TILE_PX // 2
    for y in range(TILE_PX):
        for x in range(TILE_PX):
            px[x, y] = (255, 0, 255) if ((x // half + y // half) % 2 == 0) else (0, 0, 0)
    return img


PAINTERS = {
    "grass_top": tile_grass_top,
    "grass_side": tile_grass_side,
    "dirt": tile_dirt,
    "stone": tile_stone,
    "sand": tile_sand,
    "sentinel": tile_sentinel,
    "wood_side": tile_wood_side,
    "wood_top": tile_wood_top,
    "leaves": tile_leaves,
    "planks": tile_planks,
    "water": tile_water,
    "tall_grass": tile_tall_grass,
}


def slot_png_y(index: int) -> int:
    """The PNG row a slot's top edge sits on.

    Slot `index` owns texture rows [index*16, index*16+16), and texture v grows
    upwards while PNG rows run downwards, so the slot's PNG top row is
    ATLAS_H_PX - (index + 1) * TILE_PX. Slot 0 is therefore the LAST 16 rows of
    the image and slot 14 the first painted ones. This is the same flip
    atlasRect() applies in source/world/atlas_uv.h; the two must agree or every
    face draws the wrong tile without erroring.
    """
    return ATLAS_H_PX - (index + 1) * TILE_PX


def place(atlas: Image.Image, tile: Image.Image, index: int) -> None:
    """Blits a tile into its slot. No padding: see the module docstring."""
    if index >= ADDRESSABLE_SLOTS:
        raise ValueError(
            f"tile {index} has no addressable slot: only {ADDRESSABLE_SLOTS} of "
            f"{SLOTS} fit in MeshVertex's uint8_t v. Grow ATLAS_H_PX to 512 "
            f"(and ATLAS_H_PX in source/world/atlas_uv.h and both shaders' uvScale with it)."
        )
    if index >= MARKER_SLOT:
        raise ValueError(
            f"tile {index} would take slot {MARKER_SLOT}, which is reserved for the "
            f"missing-texture marker (ATLAS_TILE_MISSING in source/world/atlas_uv.h — it is "
            f"where out-of-range tile ids clamp to). The sheet is full: grow ATLAS_H_PX to 512 "
            f"(and ATLAS_H_PX in source/world/atlas_uv.h and both shaders' uvScale with it)."
        )
    # A painter that returned the wrong size would otherwise be SILENT: Image.paste places
    # whatever it is given at the offset and leaves the rest of the slot as whatever was
    # underneath, so a 15x15 tile comes out as a valid-looking sheet with a one-pixel seam of
    # the previous content down two edges — bad art, never an error. This is the same class of
    # failure the whole F7 fix is about, so it is refused here.
    if tile.size != (TILE_PX, TILE_PX):
        raise ValueError(
            f"tile {index} is {tile.size[0]}x{tile.size[1]}, not {TILE_PX}x{TILE_PX}. "
            f"Image.paste would place it anyway and leave the rest of the slot showing "
            f"whatever was underneath, which renders as art rather than as an error."
        )
    atlas.paste(tile, (0, slot_png_y(index)))


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    out_png = root / "gfx" / "atlas.png"
    out_png.parent.mkdir(parents=True, exist_ok=True)

    # Fixed seed: the atlas must be byte-identical on every re-run, or a rebuild
    # silently changes the art and any texture comparison becomes meaningless.
    rng = random.Random(20260817)

    # RGBA since step 7.5. This PNG is still saved at 8 bits per channel regardless of
    # what tex3ds quantises it to on import (rgba8888 through step 9.3a, rgba5551 from
    # 9.3a on — see gfx/atlas.t3s) — the alpha channel has been going to the GPU all
    # along, it was simply 255 everywhere because every painter returned RGB. Only the
    # leaves tile puts anything else in it, and that alpha is binary (0 or 255) by
    # construction, which is exactly what rgba5551's 1-bit alpha needs and loses nothing
    # of; the rest are converted and come out fully opaque, unchanged pixel for pixel.
    atlas = Image.new("RGBA", (ATLAS_W_PX, ATLAS_H_PX), (24, 20, 28, 255))

    # Every slot starts as the missing-texture marker, and art is blitted over the ones TILES
    # names. Painting the marker FIRST rather than filling only the leftovers afterwards means
    # there is no way to add a slot and forget it, and it is done before the TILES loop so the
    # marker cannot touch the seeded stream the art is drawn from. Note this covers slot 15 as
    # well, which place() will not accept: it is unaddressable today, but leaving one slot of
    # background fill on the sheet keeps the trap armed for whoever next grows ATLAS_H_PX.
    marker = tile_missing(None).convert("RGBA")
    for index in range(SLOTS):
        atlas.paste(marker, (0, slot_png_y(index)))

    for index, name in enumerate(TILES):
        place(atlas, PAINTERS[name](rng).convert("RGBA"), index)

    atlas.save(out_png)
    print(f"{out_png}  {ATLAS_W_PX}x{ATLAS_H_PX}  {len(TILES)} tiles  "
          f"{ADDRESSABLE_SLOTS} addressable slots of {SLOTS}  no padding  "
          f"marker slot {MARKER_SLOT}")
    for index, name in enumerate(TILES):
        y = slot_png_y(index)
        # v0/v1 are what atlasRect() returns for this slot — printed so the two
        # sides of the layout can be eyeballed against each other.
        print(f"  {index:3d}  {name:<11} png row {y:3d}..{y + TILE_PX - 1:3d}   "
              f"tex v {index * TILE_PX}..{index * TILE_PX + TILE_PX}")
    for index in range(len(TILES), SLOTS):
        y = slot_png_y(index)
        note = "missing-texture marker (RESERVED)" if index == MARKER_SLOT else \
               "missing-texture marker" if index < ADDRESSABLE_SLOTS else \
               "missing-texture marker (unaddressable)"
        print(f"  {index:3d}  {'-':<11} png row {y:3d}..{y + TILE_PX - 1:3d}   {note}")


if __name__ == "__main__":
    main()
