#!/usr/bin/env python3
"""Draws Blocksmith's block texture atlas from scratch.

Every tile here is generated by this script — nothing is traced, sampled or
copied from another game. The palette is deliberately its own: cooler greens and
a redder soil than the obvious reference, so the look reads as Blocksmith's.

Layout: 256x256 atlas, 12x12 grid of 20x20 cells. Each cell holds a 16x16 tile
with a 2px edge-extended border on every side. The border is why UVs can be
sampled with GPU_NEAREST at any distance without neighbouring tiles bleeding in,
and it is also why the grid is 12 cells wide and not 16.

Re-run after editing:
    python tools/make_atlas.py
"""

from __future__ import annotations

import random
from pathlib import Path

from PIL import Image

ATLAS_PX = 256
TILE_PX = 16
PAD_PX = 2
CELL_PX = TILE_PX + PAD_PX * 2   # 20
GRID = ATLAS_PX // CELL_PX       # 12 cells per row, 4px of slack at the far edge

# Tile slot indices. These are the numbers the C side uses, so the order here is
# the contract — append, never reorder.
TILES = [
    "grass_top",
    "grass_side",
    "dirt",
    "stone",
    "sand",
    "sentinel",
]


def blend(a, b, t):
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))


def speckle(rng, size, shades, weights=None):
    """A flat field of randomly chosen shades — the base of most tiles."""
    img = Image.new("RGB", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(size):
            px[x, y] = rng.choices(shades, weights=weights)[0] if weights else rng.choice(shades)
    return img


def tile_grass_top(rng):
    greens = [(58, 112, 74), (66, 126, 82), (74, 138, 90), (50, 100, 66)]
    img = speckle(rng, TILE_PX, greens, weights=[4, 3, 2, 3])
    px = img.load()
    # A few brighter blades so the surface has some direction to it.
    for _ in range(18):
        x = rng.randrange(TILE_PX)
        y = rng.randrange(TILE_PX)
        px[x, y] = (88, 152, 100)
    return img


def tile_dirt(rng):
    browns = [(108, 72, 50), (96, 63, 44), (120, 82, 58), (86, 56, 40)]
    img = speckle(rng, TILE_PX, browns, weights=[4, 3, 2, 2])
    px = img.load()
    # Small pebbles: a two-tone dot, lit from the top left.
    for _ in range(7):
        x = rng.randrange(1, TILE_PX - 1)
        y = rng.randrange(1, TILE_PX - 1)
        px[x, y] = (138, 100, 74)
        px[x, y + 1] = (74, 48, 34)
    return img


def tile_grass_side(rng):
    img = tile_dirt(rng)
    px = img.load()
    greens = [(58, 112, 74), (66, 126, 82), (74, 138, 90)]
    # An irregular crust rather than a straight line — the depth of the green
    # varies per column, which is what stops a cube looking stamped.
    for x in range(TILE_PX):
        depth = 3 + rng.randrange(3)
        for y in range(depth):
            px[x, y] = rng.choice(greens)
        px[x, depth] = blend(rng.choice(greens), (96, 63, 44), 0.55)
    return img


def tile_stone(rng):
    greys = [(112, 118, 128), (102, 108, 118), (122, 128, 138), (94, 100, 110)]
    img = speckle(rng, TILE_PX, greys, weights=[4, 3, 2, 2])
    px = img.load()
    # Two short cracks, each a darker run walking downwards.
    for _ in range(2):
        x = rng.randrange(2, TILE_PX - 2)
        y = rng.randrange(1, TILE_PX - 6)
        for step in range(rng.randrange(4, 7)):
            px[max(0, min(TILE_PX - 1, x)), min(TILE_PX - 1, y + step)] = (78, 84, 94)
            x += rng.choice((-1, 0, 0, 1))
    return img


def tile_sand(rng):
    sands = [(214, 196, 148), (206, 186, 138), (222, 206, 160), (198, 178, 132)]
    return speckle(rng, TILE_PX, sands, weights=[4, 3, 2, 2])


def tile_sentinel(_rng):
    """Not art — a bleed alarm.

    This sits immediately next to the tiles the cube actually uses. If UVs or
    padding are ever wrong, magenta appears on a block face and the bug is
    unmissable instead of subtle.
    """
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    for y in range(TILE_PX):
        for x in range(TILE_PX):
            px[x, y] = (255, 0, 255) if ((x // 2 + y // 2) % 2 == 0) else (0, 0, 0)
    return img


PAINTERS = {
    "grass_top": tile_grass_top,
    "grass_side": tile_grass_side,
    "dirt": tile_dirt,
    "stone": tile_stone,
    "sand": tile_sand,
    "sentinel": tile_sentinel,
}


def place(atlas: Image.Image, tile: Image.Image, index: int) -> None:
    """Blits a tile into its cell, then edge-extends it into the padding."""
    cx = (index % GRID) * CELL_PX
    cy = (index // GRID) * CELL_PX
    x0, y0 = cx + PAD_PX, cy + PAD_PX
    atlas.paste(tile, (x0, y0))

    # Edges, then corners. Edge extension (not a wrap, not black) is what makes
    # a bleeding sample read as the tile's own colour.
    for p in range(1, PAD_PX + 1):
        atlas.paste(tile.crop((0, 0, TILE_PX, 1)), (x0, y0 - p))                 # top
        atlas.paste(tile.crop((0, TILE_PX - 1, TILE_PX, TILE_PX)), (x0, y0 + TILE_PX + p - 1))
        atlas.paste(tile.crop((0, 0, 1, TILE_PX)), (x0 - p, y0))                 # left
        atlas.paste(tile.crop((TILE_PX - 1, 0, TILE_PX, TILE_PX)), (x0 + TILE_PX + p - 1, y0))
    for dx in (-PAD_PX, TILE_PX):
        for dy in (-PAD_PX, TILE_PX):
            corner = tile.getpixel((0 if dx < 0 else TILE_PX - 1, 0 if dy < 0 else TILE_PX - 1))
            for py in range(PAD_PX):
                for px_ in range(PAD_PX):
                    atlas.putpixel((x0 + dx + px_, y0 + dy + py), corner)


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    out_png = root / "gfx" / "atlas.png"
    out_png.parent.mkdir(parents=True, exist_ok=True)

    # Fixed seed: the atlas must be byte-identical on every re-run, or a rebuild
    # silently changes the art and any texture comparison becomes meaningless.
    rng = random.Random(20260817)

    atlas = Image.new("RGB", (ATLAS_PX, ATLAS_PX), (24, 20, 28))
    for index, name in enumerate(TILES):
        place(atlas, PAINTERS[name](rng), index)

    atlas.save(out_png)
    print(f"{out_png}  {ATLAS_PX}x{ATLAS_PX}  {len(TILES)} tiles  cell {CELL_PX}px  grid {GRID}x{GRID}")
    for index, name in enumerate(TILES):
        cx, cy = (index % GRID) * CELL_PX + PAD_PX, (index // GRID) * CELL_PX + PAD_PX
        print(f"  {index:3d}  {name:<11} px ({cx},{cy})")


if __name__ == "__main__":
    main()
