#!/usr/bin/env python3
"""Draws Blocksmith's block texture atlas from scratch.

Every tile here is generated by this script — nothing is traced, sampled or
copied from another game. The palette is deliberately its own: cooler greens and
a redder soil than the obvious reference, so the look reads as Blocksmith's.

Layout: 256x256 atlas, 12x12 grid of 20x20 cells. Each cell holds a 16x16 tile
with a 2px edge-extended border on every side. The border is why UVs can be
sampled with GPU_NEAREST at any distance without neighbouring tiles bleeding in,
and it is also why the grid is 12 cells wide and not 16.

Re-run after editing:
    python tools/make_atlas.py
"""

from __future__ import annotations

import random
from pathlib import Path

from PIL import Image

ATLAS_PX = 256
TILE_PX = 16
PAD_PX = 2
CELL_PX = TILE_PX + PAD_PX * 2   # 20
GRID = ATLAS_PX // CELL_PX       # 12 cells per row, 4px of slack at the far edge

# Tile slot indices. These are the numbers the C side uses, so the order here is
# the contract — append, never reorder.
TILES = [
    "grass_top",
    "grass_side",
    "dirt",
    "stone",
    "sand",
    "sentinel",
    # Step 5.3's trees. Appended after the sentinel rather than next to sand,
    # because the order above is the contract with the C side and inserting
    # would silently re-texture every tile after the insertion point. The
    # sentinel is still adjacent to real art on both sides, so it goes on
    # doing its job.
    "wood_side",
    "wood_top",
    "leaves",
]


def blend(a, b, t):
    return tuple(int(round(a[i] + (b[i] - a[i]) * t)) for i in range(3))


def speckle(rng, size, shades, weights=None):
    """A flat field of randomly chosen shades — the base of most tiles."""
    img = Image.new("RGB", (size, size))
    px = img.load()
    for y in range(size):
        for x in range(size):
            px[x, y] = rng.choices(shades, weights=weights)[0] if weights else rng.choice(shades)
    return img


def tile_grass_top(rng):
    greens = [(58, 112, 74), (66, 126, 82), (74, 138, 90), (50, 100, 66)]
    img = speckle(rng, TILE_PX, greens, weights=[4, 3, 2, 3])
    px = img.load()
    # A few brighter blades so the surface has some direction to it.
    for _ in range(18):
        x = rng.randrange(TILE_PX)
        y = rng.randrange(TILE_PX)
        px[x, y] = (88, 152, 100)
    return img


def tile_dirt(rng):
    browns = [(108, 72, 50), (96, 63, 44), (120, 82, 58), (86, 56, 40)]
    img = speckle(rng, TILE_PX, browns, weights=[4, 3, 2, 2])
    px = img.load()
    # Small pebbles: a two-tone dot, lit from the top left.
    for _ in range(7):
        x = rng.randrange(1, TILE_PX - 1)
        y = rng.randrange(1, TILE_PX - 1)
        px[x, y] = (138, 100, 74)
        px[x, y + 1] = (74, 48, 34)
    return img


def tile_grass_side(rng):
    img = tile_dirt(rng)
    px = img.load()
    greens = [(58, 112, 74), (66, 126, 82), (74, 138, 90)]
    # An irregular crust rather than a straight line — the depth of the green
    # varies per column, which is what stops a cube looking stamped.
    for x in range(TILE_PX):
        depth = 3 + rng.randrange(3)
        for y in range(depth):
            px[x, y] = rng.choice(greens)
        px[x, depth] = blend(rng.choice(greens), (96, 63, 44), 0.55)
    return img


def tile_stone(rng):
    greys = [(112, 118, 128), (102, 108, 118), (122, 128, 138), (94, 100, 110)]
    img = speckle(rng, TILE_PX, greys, weights=[4, 3, 2, 2])
    px = img.load()
    # Two short cracks, each a darker run walking downwards.
    for _ in range(2):
        x = rng.randrange(2, TILE_PX - 2)
        y = rng.randrange(1, TILE_PX - 6)
        for step in range(rng.randrange(4, 7)):
            px[max(0, min(TILE_PX - 1, x)), min(TILE_PX - 1, y + step)] = (78, 84, 94)
            x += rng.choice((-1, 0, 0, 1))
    return img


def tile_sand(rng):
    sands = [(214, 196, 148), (206, 186, 138), (222, 206, 160), (198, 178, 132)]
    return speckle(rng, TILE_PX, sands, weights=[4, 3, 2, 2])


def tile_wood_side(rng):
    """Bark: vertical grain, greyer and darker than dirt so a trunk reads as a
    trunk against the soil it stands in rather than as a column of it."""
    barks = [(92, 66, 44), (80, 57, 38), (104, 76, 52), (70, 50, 34)]
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    # Grain runs in columns, each column keeping one shade for a few pixels at a
    # time — a per-pixel speckle would read as noise, not bark.
    for x in range(TILE_PX):
        y = 0
        while y < TILE_PX:
            shade = rng.choices(barks, weights=[4, 3, 2, 2])[0]
            run = 2 + rng.randrange(5)
            for dy in range(run):
                if y + dy < TILE_PX:
                    px[x, y + dy] = shade
            y += run
    # Two deep grooves, full height, one pixel wide, so the cylinder reads at a
    # distance where the grain itself has blurred away.
    for x in (rng.randrange(2, 7), rng.randrange(9, 14)):
        for y in range(TILE_PX):
            px[x, y] = (58, 41, 28)
    return img


def tile_wood_top(rng):
    """The cut end: rings around an off-centre heart."""
    pale = (150, 116, 80)
    ring = (112, 84, 56)
    dark = (86, 62, 42)
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    cx = 7.5 + rng.uniform(-1.2, 1.2)
    cy = 7.5 + rng.uniform(-1.2, 1.2)
    for y in range(TILE_PX):
        for x in range(TILE_PX):
            d = ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5
            # Concentric bands two pixels apart, jittered so they are not perfect
            # circles — a clean bullseye looks machined.
            band = int(d + rng.uniform(-0.35, 0.35)) // 2
            px[x, y] = ring if band % 2 else pale
            if d > 7.4:
                px[x, y] = dark          # bark seen edge-on, framing the cut
    return img


def tile_leaves(rng):
    """Cutout canopy — step 7.5. Returns RGBA, and the holes are real alpha 0
    rather than dark pixels, so the transparent pass has something to key on.

    Alpha is 0 or 255 and never in between: the draw uses an alpha *test*, not
    blending, so a half-transparent pixel would not come out half-visible — it
    would land on one side of the threshold and look like a mistake.
    """
    leaf = [(38, 82, 52), (46, 96, 60), (30, 68, 44), (54, 110, 68)]
    img = speckle(rng, TILE_PX, leaf, weights=[4, 3, 3, 2]).convert("RGBA")
    px = img.load()
    # Clumps: a 2x2 of one shade, which is what stops the tile reading as static.
    for _ in range(12):
        x = rng.randrange(TILE_PX - 1)
        y = rng.randrange(TILE_PX - 1)
        shade = rng.choice(leaf) + (255,)
        for dy in range(2):
            for dx in range(2):
                px[x + dx, y + dy] = shade
    # Gaps. Singles scattered through, plus a few 2x1 tears, so the canopy breaks
    # up at more than one scale — a field of isolated single pixels reads as noise
    # on a 240p screen rather than as foliage.
    hole = (0, 0, 0, 0)
    for _ in range(24):
        px[rng.randrange(TILE_PX), rng.randrange(TILE_PX)] = hole
    for _ in range(6):
        x = rng.randrange(TILE_PX - 1)
        y = rng.randrange(TILE_PX)
        px[x, y] = hole
        px[x + 1, y] = hole
    # The tile's own border stays opaque. place() edge-extends the tile into its
    # 2px padding, so a transparent edge pixel would be smeared outward and could
    # put a hole into a neighbouring tile's sample at a grazing angle — which is
    # the exact bug the padding exists to prevent.
    for i in range(TILE_PX):
        for x, y in ((i, 0), (i, TILE_PX - 1), (0, i), (TILE_PX - 1, i)):
            r, g, b, a = px[x, y]
            px[x, y] = (rng.choice(leaf) + (255,)) if a == 0 else (r, g, b, 255)
    return img


def tile_sentinel(_rng):
    """Not art — a bleed alarm.

    This sits immediately next to the tiles the cube actually uses. If UVs or
    padding are ever wrong, magenta appears on a block face and the bug is
    unmissable instead of subtle.
    """
    img = Image.new("RGB", (TILE_PX, TILE_PX))
    px = img.load()
    for y in range(TILE_PX):
        for x in range(TILE_PX):
            px[x, y] = (255, 0, 255) if ((x // 2 + y // 2) % 2 == 0) else (0, 0, 0)
    return img


PAINTERS = {
    "grass_top": tile_grass_top,
    "grass_side": tile_grass_side,
    "dirt": tile_dirt,
    "stone": tile_stone,
    "sand": tile_sand,
    "sentinel": tile_sentinel,
    "wood_side": tile_wood_side,
    "wood_top": tile_wood_top,
    "leaves": tile_leaves,
}


def place(atlas: Image.Image, tile: Image.Image, index: int) -> None:
    """Blits a tile into its cell, then edge-extends it into the padding."""
    cx = (index % GRID) * CELL_PX
    cy = (index // GRID) * CELL_PX
    x0, y0 = cx + PAD_PX, cy + PAD_PX
    atlas.paste(tile, (x0, y0))

    # Edges, then corners. Edge extension (not a wrap, not black) is what makes
    # a bleeding sample read as the tile's own colour.
    for p in range(1, PAD_PX + 1):
        atlas.paste(tile.crop((0, 0, TILE_PX, 1)), (x0, y0 - p))                 # top
        atlas.paste(tile.crop((0, TILE_PX - 1, TILE_PX, TILE_PX)), (x0, y0 + TILE_PX + p - 1))
        atlas.paste(tile.crop((0, 0, 1, TILE_PX)), (x0 - p, y0))                 # left
        atlas.paste(tile.crop((TILE_PX - 1, 0, TILE_PX, TILE_PX)), (x0 + TILE_PX + p - 1, y0))
    for dx in (-PAD_PX, TILE_PX):
        for dy in (-PAD_PX, TILE_PX):
            corner = tile.getpixel((0 if dx < 0 else TILE_PX - 1, 0 if dy < 0 else TILE_PX - 1))
            for py in range(PAD_PX):
                for px_ in range(PAD_PX):
                    atlas.putpixel((x0 + dx + px_, y0 + dy + py), corner)


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    out_png = root / "gfx" / "atlas.png"
    out_png.parent.mkdir(parents=True, exist_ok=True)

    # Fixed seed: the atlas must be byte-identical on every re-run, or a rebuild
    # silently changes the art and any texture comparison becomes meaningless.
    rng = random.Random(20260817)

    # RGBA since step 7.5. atlas.t3s was already asking tex3ds for rgba8888, so the
    # alpha channel has been going to the GPU all along — it was simply 255 everywhere
    # because every painter returned RGB. Only the leaves tile puts anything else in it;
    # the rest are converted and come out fully opaque, unchanged pixel for pixel.
    atlas = Image.new("RGBA", (ATLAS_PX, ATLAS_PX), (24, 20, 28, 255))
    for index, name in enumerate(TILES):
        place(atlas, PAINTERS[name](rng).convert("RGBA"), index)

    atlas.save(out_png)
    print(f"{out_png}  {ATLAS_PX}x{ATLAS_PX}  {len(TILES)} tiles  cell {CELL_PX}px  grid {GRID}x{GRID}")
    for index, name in enumerate(TILES):
        cx, cy = (index % GRID) * CELL_PX + PAD_PX, (index // GRID) * CELL_PX + PAD_PX
        print(f"  {index:3d}  {name:<11} px ({cx},{cy})")


if __name__ == "__main__":
    main()
