#!/bin/sh
# Generates source/app/version_history_data.c — the data the in-app "VERSION HISTORY"
# browser (scene/title.c, app/version_history.c) reads — from every whatsnew<version>.txt
# this repo ships.
#
# steve's brief, in his words: "whenever you click on the button that says check for update,
# I want there to be a option in the top left ... version history. You click on that ...
# it should be displaying all the past versions up to the current latest version. What it
# added, what it changed, what it fixed, what it removed ... So that way players can see ...
# what they've missed out on."
#
# ── Why this reads whatsnew*.txt and not CHANGELOG.md ─────────────────────────────────
#
# CHANGELOG.md is a developer document: multi-paragraph, full of measured numbers and
# rejected alternatives, with ad hoc section headers ("### Why this build exists", "### What
# v1.1.6 said", ...) that vary release to release. It cannot be parsed into short player-
# facing lines without either a fragile heuristic or a second hand-maintained summary format
# — and either one is exactly the duplicate-of-the-changelog failure mode this task exists to
# avoid.
#
# whatsnew<version>.txt already IS that player-facing summary. tools/make_whatsnew.sh has
# produced one for every release since v1.6.0 (see its own header comment — "release gate 3
# of 8"), each one capped and checked by that script, and app/whatsnew.c/app/whatsnew.h
# already parse, word-wrap, scroll and draw the format — tested by tests/whatsnew_test.c and
# shipping today on the update screen for the single newest release. Baking these means the
# history browser reuses that exact, already-proven pipeline for every past version too,
# rather than inventing a parallel one.
#
# The two categories in that format (FEATURES ADDED, BUGS FIXED) are what this script bakes.
# There is no separate "changed" or "removed" bucket: every whatsnew file so far folds a
# change or a removal into whichever of the two reads naturally in one sentence ("X no longer
# does Y" is a fix; "X now does Y instead" is a feature), the same way the release author
# already chose when writing it. Splitting the format further would mean going back and
# hand-editing eleven already-shipped release notes files for a browser that is being added
# to the app version(s) after them — out of scope for this script.
#
# ── The CHANGELOG.md cross-check ───────────────────────────────────────────────────────
#
# Every version this script bakes must have a "## [<version>]" heading somewhere in
# CHANGELOG.md, or it refuses. That is the one thing checked against CHANGELOG.md: not its
# prose (never parsed), just that the version was actually released, so a stray or
# hand-typed whatsnew<version>.txt for a version that was never cut cannot make it into a
# player-facing history browser.
#
# ── Freshness ───────────────────────────────────────────────────────────────────────────
#
# This script does not check its own output is up to date — tools/run_host_tests.sh does
# that itself, the same way it already guards build/atlas.t3x against gfx/atlas.t3s: it
# regenerates into a scratch file with this script and cmp -s's the result against the
# committed source/app/version_history_data.c, failing loud on any difference. See that
# script for why (rebuild-and-diff, not an mtime and not a stamp file).
#
# Usage, from the project root:
#
#   sh tools/make_version_history.sh <output.c>
#   e.g. sh tools/make_version_history.sh source/app/version_history_data.c
set -e

cd "$(dirname "$0")/.."

OUT="$1"
if [ -z "$OUT" ]; then
	echo "usage: sh tools/make_version_history.sh <output.c>" >&2
	echo "  e.g.  sh tools/make_version_history.sh source/app/version_history_data.c" >&2
	exit 2
fi

# sort -V: natural version ordering (1.8.2 before 1.8.10), not the lexicographic ordering a
# plain sort would give (1.8.10 before 1.8.2). Oldest first, so the generated table reads
# top-to-bottom the same way CHANGELOG.md's entries read bottom-to-top.
FILES=$(printf '%s\n' whatsnew[0-9]*.txt 2>/dev/null | sort -V)
if [ -z "$FILES" ] || [ "$FILES" = "whatsnew[0-9]*.txt" ]; then
	echo "no whatsnew<version>.txt files found in $(pwd) - nothing to bake" >&2
	exit 3
fi

TMP="${OUT}.tmp$$"
trap 'rm -f "$TMP"' EXIT

{
	echo "// GENERATED by tools/make_version_history.sh - do not hand-edit."
	echo "//"
	echo "// One version's whole file, embedded verbatim as bytes (not a C string literal, so"
	echo "// nothing in the source text - quotes, backslashes - needs escaping), parsed at"
	echo "// runtime by the same app/whatsnew.c the update screen's single-version notes"
	echo "// already use. See app/version_history.c and app/version_history.h."
	echo "//"
	echo "// Regenerate: sh tools/make_version_history.sh source/app/version_history_data.c"
	echo "#include \"app/version_history.h\""
	echo
} > "$TMP"

INDEX="$TMP.index$$"
: > "$INDEX"
trap 'rm -f "$TMP" "$INDEX"' EXIT

COUNT=0
for f in $FILES; do
	VERSION=$(printf '%s' "$f" | sed -n 's/^whatsnew\(.*\)\.txt$/\1/p')
	if [ -z "$VERSION" ]; then
		echo "$f: could not read a version number out of the filename" >&2
		exit 4
	fi

	# Not a prose check - just "did this version actually get released". See the file
	# header above for why nothing here parses CHANGELOG.md's body text.
	if ! grep -q "^## \[$VERSION\]" CHANGELOG.md; then
		echo "$f: no \"## [$VERSION]\" heading in CHANGELOG.md - refusing to bake it" >&2
		echo "  nothing in CHANGELOG.md says this game ever released $VERSION. Add the" >&2
		echo "  changelog entry, or remove $f if it should not exist." >&2
		exit 5
	fi

	LEN=$(wc -c < "$f")
	if [ "$LEN" -eq 0 ]; then
		echo "$f: empty file - refusing to bake a version with no notes at all" >&2
		exit 6
	fi

	# od's byte columns are separated by runs of spaces, one row per 16 bytes by default;
	# tr -s squeezes both the inter-column spaces and the row-ending newlines down to single
	# commas, and the two sed passes drop the leading comma od's leading column gap leaves
	# and the trailing comma after the last byte. Verified byte-for-byte against the source
	# file with memcmp before this script was trusted with real data (see the session log).
	BYTES=$(od -An -v -tu1 "$f" | tr -s ' \n' ',' | sed 's/^,//; s/,$//')

	printf 'static const unsigned char s_vh_data_%d[] = {%s};\n' "$COUNT" "$BYTES" >> "$TMP"
	printf '\t{ "%s", s_vh_data_%d, %d },\n' "$VERSION" "$COUNT" "$LEN" >> "$INDEX"

	COUNT=$((COUNT + 1))
done

{
	echo
	echo "const VersionHistoryEntry VERSION_HISTORY[] = {"
	cat "$INDEX"
	echo "};"
	echo
	echo "const int VERSION_HISTORY_COUNT = $COUNT;"
} >> "$TMP"

mv "$TMP" "$OUT"
trap - EXIT
rm -f "$INDEX"

echo "wrote $OUT: $COUNT version(s) baked, $(wc -c < "$OUT") bytes of generated source"
