#!/usr/bin/env python3
"""Synthesises the CIA banner chime the 3DS Home Menu plays (roadmap task 44).

Nothing here is sampled, recorded, downloaded or lifted from another game - same rule as
tools/make_atlas.py and tools/make_font.py, and for the same reason. Every sample below is
computed from sine partials, a shaped noise burst and an envelope, using nothing but the
Python standard library (math, struct, wave). No Pillow, no numpy, no sound library.

This replaces the 0.1 s of digital silence tools/make_cia.sh used to write by hand with
printf. bannertool's makebanner refuses to build a banner with no audio track at all, so
that placeholder existed purely to satisfy the flag; this file makes the flag carry
something worth hearing.

Scope note, because it is easy to get wrong: this track is played by the 3DS Home Menu out
of the banner, NOT by Blocksmith. It needs no ndsp, no audio engine and nothing from
roadmap task 43 - it is a .wav handed to bannertool at package time and that is all.

Format: 22050 Hz, mono, 16-bit PCM. Measured (t44 blueprint 1.2) to be accepted by
bannertool v1.2.3's makecwav verbatim, with no resampling, downmix or compression - the PCM
goes into the .bnr as-is, so the format choice is a download-size choice. The same blueprint
measured the container arithmetic as `.bnr bytes = 3088 + PCM bytes`, which puts this track
at about 73.6 KB of banner against about 215 KB for the 32 kHz stereo equivalent. A
four-note chime is not a stereo image.

Deterministic by construction: the noise burst comes from the integer LCG below rather than
the random module, so a re-run produces a byte-identical file.

Re-run after editing:
    python tools/make_banner_audio.py [output.wav]

Default output: cia/build/chime.wav (build output, gitignored, regenerated by make_cia.sh).
"""

from __future__ import annotations

import math
import struct
import sys
import wave
from pathlib import Path

# ── Format ────────────────────────────────────────────────────────────────────────────
RATE = 22050           # Hz. Accepted by bannertool makecwav, measured, not assumed.
CHANNELS = 1
SAMPLE_BYTES = 2       # 16-bit signed PCM
DURATION_S = 1.6       # whole track, including the final note's ring-out

# ── The figure ────────────────────────────────────────────────────────────────────────
#
# Four notes: rise, octave, then settle onto the third rather than back onto the root, so
# it reads as an opening rather than a full stop. Four notes because four blocks going down
# is this game's own subject matter.
#
# The degrees are semitones above the root and are the shape of the tune; the root itself is
# a free choice of key. A3 is low enough to stay warm on two small 3DS speakers and high
# enough that the third partial is still inside the band.
ROOT_HZ = 220.0                    # A3
DEGREES = (0, 7, 12, 4)            # root, fifth, octave, major third
ONSET_S = (0.00, 0.16, 0.32, 0.48)  # 0.28 s notes overlapping by 0.12 s
NOTE_LEN_S = 0.28                  # nominal; the LAST note rings to the end of the track

# ── Timbre ────────────────────────────────────────────────────────────────────────────
#
# Additive, three partials. The odd/even mix is what stops it reading as a sine beep; the
# noise transient is what makes it read as something struck rather than something switched
# on. A pure-sine chime on a 3DS speaker sounds like a test tone.
HARMONICS = ((1, 1.00), (2, 0.35), (3, 0.12))

ATTACK_S = 0.006       # a hard zero-length attack puts an audible click in uncompressed PCM
DECAY_TAU_S = 0.22     # exponential; the note is at 1/e after this long
RELEASE_S = 0.040      # ramp to zero at a non-final note's end, so it does not cut

TRANSIENT_S = 0.024    # noise burst length at each onset
TRANSIENT_TAU_S = 0.012  # its exponential shaping
#
# The one number the blueprint did not specify. 0.45 of the note's own peak: loud enough to
# be the attack of the sound rather than a separate tick, quiet enough that the pitch, not
# the noise, is what the ear takes away. Raise it and the chime turns percussive; drop it to
# 0 and every note starts as a soft swell with no strike in it.
TRANSIENT_AMP = 0.45

# ── Master ────────────────────────────────────────────────────────────────────────────
PEAK_DBFS = -3.0       # headroom, so the console's own mix has somewhere to go
END_FADE_S = 0.030     # linear, to a guaranteed zero last sample


def lcg_noise(seed: int):
    """Deterministic white noise in [-1, 1).

    A plain 32-bit LCG (Numerical Recipes constants) rather than `random`, so the output
    cannot move if the interpreter's PRNG implementation ever does. Byte-identical re-runs
    are a requirement of every generator in this folder, not a nicety.
    """
    state = seed & 0xFFFFFFFF
    while True:
        state = (state * 1664525 + 1013904223) & 0xFFFFFFFF
        yield state / 2147483648.0 - 1.0


def note_amplitude(t: float, length_s: float | None) -> float:
    """Envelope of one note, `t` seconds after its own onset. 0 outside the note."""
    if t < 0.0:
        return 0.0
    if length_s is not None and t >= length_s:
        return 0.0

    if t < ATTACK_S:
        env = t / ATTACK_S
    else:
        env = math.exp(-(t - ATTACK_S) / DECAY_TAU_S)

    # Non-final notes ramp out over their last RELEASE_S so the end of the note is a fade
    # and not a step. A step here is a click, and an uncompressed banner track has nothing
    # to hide it behind.
    if length_s is not None:
        left = length_s - t
        if left < RELEASE_S:
            env *= left / RELEASE_S

    return env


def synthesise() -> list[float]:
    """The whole track as floats, before normalisation."""
    total = int(round(DURATION_S * RATE))
    buf = [0.0] * total
    noise = lcg_noise(0xB10CC)  # the project's own UniqueId, so the seed is not a mystery

    for index, (degree, onset) in enumerate(zip(DEGREES, ONSET_S)):
        freq = ROOT_HZ * (2.0 ** (degree / 12.0))
        last = index == len(DEGREES) - 1
        # The final note is not cut at NOTE_LEN_S: it rings out under the master fade, which
        # is what makes the figure resolve instead of stopping.
        length_s = None if last else NOTE_LEN_S

        start = int(round(onset * RATE))
        end = total if last else min(total, start + int(round(NOTE_LEN_S * RATE)))

        for n in range(start, end):
            t = (n - start) / RATE
            env = note_amplitude(t, length_s)
            if env == 0.0:
                continue
            tone = 0.0
            for mult, weight in HARMONICS:
                tone += weight * math.sin(2.0 * math.pi * freq * mult * t)
            buf[n] += env * tone

        # The strike. Its own short envelope, drawn from the same deterministic stream, so
        # each note's transient differs from its neighbours' the way real strikes do.
        burst = int(round(TRANSIENT_S * RATE))
        for n in range(start, min(total, start + burst)):
            t = (n - start) / RATE
            shape = math.exp(-t / TRANSIENT_TAU_S)
            if t < ATTACK_S:
                shape *= t / ATTACK_S  # the burst gets the same soft edge as the tone
            buf[n] += TRANSIENT_AMP * shape * next(noise)

    return buf


def master(buf: list[float]) -> list[float]:
    """Peak-normalise to PEAK_DBFS, then fade the tail to a hard zero."""
    peak = max(abs(v) for v in buf)
    if peak <= 0.0:
        raise ValueError("synthesis produced silence - refusing to write a dead track")

    gain = (10.0 ** (PEAK_DBFS / 20.0)) / peak
    out = [v * gain for v in buf]

    fade = int(round(END_FADE_S * RATE))
    total = len(out)
    for i in range(fade):
        n = total - fade + i
        out[n] *= (fade - 1 - i) / fade  # last sample multiplied by exactly 0

    return out


def to_pcm16(buf: list[float]) -> bytes:
    frames = bytearray()
    for v in buf:
        s = int(round(v * 32767.0))
        if s > 32767:
            s = 32767
        elif s < -32768:
            s = -32768
        frames += struct.pack("<h", s)
    return bytes(frames)


def write_wav(path: Path, pcm: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(CHANNELS)
        w.setsampwidth(SAMPLE_BYTES)
        w.setframerate(RATE)
        w.writeframes(pcm)


def report(path: Path) -> None:
    """Read the file back and print what its OWN header says.

    Not the constants above - the header. A generator that prints its inputs proves nothing
    about its output.
    """
    with wave.open(str(path), "rb") as w:
        rate = w.getframerate()
        ch = w.getnchannels()
        width = w.getsampwidth()
        frames = w.getnframes()
        data = w.readframes(frames)

    first = struct.unpack_from("<h", data, 0)[0]
    last = struct.unpack_from("<h", data, len(data) - 2)[0]
    peak = max(abs(v) for v in struct.unpack("<%dh" % frames, data))

    print("make_banner_audio.py: wrote %s" % path)
    print("  bytes      : %d" % path.stat().st_size)
    print("  sample rate: %d Hz" % rate)
    print("  channels   : %d" % ch)
    print("  bit depth  : %d" % (width * 8))
    print("  frames     : %d" % frames)
    print("  duration   : %.4f s" % (frames / rate))
    print("  first/last : %d / %d  (both must be 0, or it clicks)" % (first, last))
    print("  peak       : %d of 32767 (%.2f dBFS)" % (peak, 20.0 * math.log10(peak / 32767.0)))


def main(argv: list[str]) -> int:
    root = Path(__file__).resolve().parent.parent
    out = Path(argv[1]) if len(argv) > 1 else root / "cia" / "build" / "chime.wav"

    pcm = to_pcm16(master(synthesise()))
    write_wav(out, pcm)
    report(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
